// exercises_db.js — Exercise library (365 exercises)
// Автогенерируется скриптом tools/sync_exercises.js — не редактировать вручную

export const EXERCISE_CATEGORIES = [
    { id: 'abdominals', nameRu: 'Пресс' },
    { id: 'abductors', nameRu: 'Отводящие' },
    { id: 'adductors', nameRu: 'Приводящие' },
    { id: 'biceps', nameRu: 'Бицепс' },
    { id: 'calves', nameRu: 'Икры' },
    { id: 'cardio', nameRu: 'Кардио' },
    { id: 'chest', nameRu: 'Грудь' },
    { id: 'forearms', nameRu: 'Предплечья' },
    { id: 'glutes', nameRu: 'Ягодицы' },
    { id: 'hamstrings', nameRu: 'Бицепс бедра' },
    { id: 'lats', nameRu: 'Широчайшие' },
    { id: 'lower_back', nameRu: 'Нижняя спина' },
    { id: 'neck', nameRu: 'Шея' },
    { id: 'quadriceps', nameRu: 'Квадрицепс' },
    { id: 'shoulders', nameRu: 'Плечи' },
    { id: 'traps', nameRu: 'Трапеции' },
    { id: 'triceps', nameRu: 'Трицепс' },
    { id: 'upper_back', nameRu: 'Верхняя спина' },
];

export const EXERCISE_DB = [
    // === Пресс (31) ===
    { nameRu: 'Велосипедные скручивания', name: 'Bicycle Crunch', category: 'abdominals' },
    { nameRu: 'Вращение корпуса', name: 'Torso Rotation', category: 'abdominals' },
    { nameRu: 'Вращение корпуса на блоке (сверху вниз)', name: 'Cable Twist (Up to down)', category: 'abdominals' },
    { nameRu: 'Вращение корпуса на блоке (снизу вверх)', name: 'Cable Twist (Down to up)', category: 'abdominals' },
    { nameRu: 'Жим Палоффа (на блоке)', name: 'Cable Core Palloff Press', category: 'abdominals' },
    { nameRu: 'Касание носков', name: 'Toe Touch', category: 'abdominals' },
    { nameRu: 'Косые скручивания', name: 'Oblique Crunch', category: 'abdominals' },
    { nameRu: 'Локоть к колену', name: 'Elbow to Knee', category: 'abdominals' },
    { nameRu: 'Лэндмайн 180', name: 'Landmine 180', category: 'abdominals' },
    { nameRu: 'Наклон в сторону', name: 'Side Bend', category: 'abdominals' },
    { nameRu: 'Наклон в сторону (с гантелей)', name: 'Side Bend (Dumbbell)', category: 'abdominals' },
    { nameRu: 'Ножницы на пресс', name: 'Ab Scissors', category: 'abdominals' },
    { nameRu: 'Носки к перекладине', name: 'Toes to Bar', category: 'abdominals' },
    { nameRu: 'Обратные скручивания', name: 'Reverse Crunch', category: 'abdominals' },
    { nameRu: 'Подъём коленей в висе', name: 'Hanging Knee Raise', category: 'abdominals' },
    { nameRu: 'Подъём коленей на брусьях', name: 'Knee Raise Parallel Bars', category: 'abdominals' },
    { nameRu: 'Подъём корпуса (с отягощением)', name: 'Sit Up (Weighted)', category: 'abdominals' },
    { nameRu: 'Подъём ног в висе', name: 'Hanging Leg Raise', category: 'abdominals' },
    { nameRu: 'Подъём ног лёжа', name: 'Lying Leg Raise', category: 'abdominals' },
    { nameRu: 'Подъём ног на брусьях', name: 'Leg Raise Parallel Bars', category: 'abdominals' },
    { nameRu: 'Ролик для пресса', name: 'Ab Wheel', category: 'abdominals' },
    { nameRu: 'Русский твист (без отягощения)', name: 'Russian Twist (Bodyweight)', category: 'abdominals' },
    { nameRu: 'Русский твист (с отягощением)', name: 'Russian Twist (Weighted)', category: 'abdominals' },
    { nameRu: 'Складка', name: 'Jackknife Sit Up', category: 'abdominals' },
    { nameRu: 'Складка (в петлях TRX)', name: 'Jack Knife (Suspension)', category: 'abdominals' },
    { nameRu: 'Скручивание', name: 'Crunch', category: 'abdominals' },
    { nameRu: 'Скручивание (в тренажёре)', name: 'Crunch (Machine)', category: 'abdominals' },
    { nameRu: 'Скручивание (с отягощением)', name: 'Crunch (Weighted)', category: 'abdominals' },
    { nameRu: 'Скручивание на блоке', name: 'Cable Crunch', category: 'abdominals' },
    { nameRu: 'Скручивание на наклонной скамье', name: 'Decline Crunch', category: 'abdominals' },
    { nameRu: 'Скручивание на наклонной скамье (с отягощением)', name: 'Decline Crunch (Weighted)', category: 'abdominals' },
    // === Отводящие (1) ===
    { nameRu: 'Разведение ног (в тренажёре)', name: 'Hip Abduction (Machine)', category: 'abductors' },
    // === Приводящие (1) ===
    { nameRu: 'Сведение ног (в тренажёре)', name: 'Hip Adduction (Machine)', category: 'adductors' },
    // === Бицепс (32) ===
    { nameRu: 'Концентрированное сгибание обратным хватом', name: 'Reverse Grip Concentration Curl', category: 'biceps' },
    { nameRu: 'Концентрированный подъём на бицепс', name: 'Concentration Curl', category: 'biceps' },
    { nameRu: 'Молотковый подъём (на блоке)', name: 'Hammer Curl (Cable)', category: 'biceps' },
    { nameRu: 'Молотковый подъём (с гантелями)', name: 'Hammer Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Молотковый подъём (с резиной)', name: 'Hammer Curl (Band)', category: 'biceps' },
    { nameRu: 'Паучьи сгибания (с гантелями)', name: 'Spider Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Паучьи сгибания (со штангой)', name: 'Spider Curl (Barbell)', category: 'biceps' },
    { nameRu: 'Перекрёстный подъём хватом молот', name: 'Cross Body Hammer Curl', category: 'biceps' },
    { nameRu: 'Подъём Зоттмана (с гантелями)', name: 'Zottman Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс (в петлях TRX)', name: 'Bicep Curl (Suspension)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс (в тренажёре)', name: 'Bicep Curl (Machine)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс (на блоке)', name: 'Bicep Curl (Cable)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс (с EZ-грифом)', name: 'EZ Bar Biceps Curl', category: 'biceps' },
    { nameRu: 'Подъём на бицепс (с гантелями)', name: 'Bicep Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс (с гирей)', name: 'Kettlebell Curl', category: 'biceps' },
    { nameRu: 'Подъём на бицепс (со штангой)', name: 'Bicep Curl (Barbell)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс 21', name: '21s Bicep Curl', category: 'biceps' },
    { nameRu: 'Подъём на бицепс на скамье Скотта (в тренажёре)', name: 'Preacher Curl (Machine)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс на скамье Скотта (с гантелями)', name: 'Preacher Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Подъём на бицепс на скамье Скотта (со штангой)', name: 'Preacher Curl (Barbell)', category: 'biceps' },
    { nameRu: 'Подъём штанги «протяжкой» вдоль тела', name: 'Drag Curl', category: 'biceps' },
    { nameRu: 'Сгибание «пинвил» (с гантелями)', name: 'Pinwheel Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Сгибание на бицепс из-за головы (на блоке)', name: 'Overhead Curl (Cable)', category: 'biceps' },
    { nameRu: 'Сгибание на бицепс с диском', name: 'Plate Curl', category: 'biceps' },
    { nameRu: 'Сгибание на бицепс с канатом (на блоке)', name: 'Rope Cable Curl', category: 'biceps' },
    { nameRu: 'Сгибание на наклонной скамье сидя (с гантелями)', name: 'Seated Incline Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Сгибание обратным хватом (на блоке)', name: 'Reverse Curl (Cable)', category: 'biceps' },
    { nameRu: 'Сгибание обратным хватом (с гантелями)', name: 'Reverse Curl (Dumbbell)', category: 'biceps' },
    { nameRu: 'Сгибание обратным хватом (со штангой)', name: 'Reverse Curl (Barbell)', category: 'biceps' },
    { nameRu: 'Сгибание одной рукой (на блоке)', name: 'Single Arm Curl (Cable)', category: 'biceps' },
    { nameRu: 'Сгибание рук за спиной (блок)', name: 'Behind the Back Curl (Cable)', category: 'biceps' },
    { nameRu: 'Сгибание рук официанта (гантель)', name: 'Waiter Curl (Dumbbell)', category: 'biceps' },
    // === Икры (12) ===
    { nameRu: 'Жим носками (в тренажёре)', name: 'Calf Press (Machine)', category: 'calves' },
    { nameRu: 'Подъём на носки (в тренажёре)', name: 'Calf Extension (Machine)', category: 'calves' },
    { nameRu: 'Подъём на носки сидя', name: 'Seated Calf Raise', category: 'calves' },
    { nameRu: 'Подъём на носки стоя', name: 'Standing Calf Raise', category: 'calves' },
    { nameRu: 'Подъём на носки стоя (в Смите)', name: 'Standing Calf Raise (Smith)', category: 'calves' },
    { nameRu: 'Подъём на носки стоя (в тренажёре)', name: 'Standing Calf Raise (Machine)', category: 'calves' },
    { nameRu: 'Подъём на носки стоя (с гантелями)', name: 'Standing Calf Raise (Dumbbell)', category: 'calves' },
    { nameRu: 'Подъём на носки стоя (со штангой)', name: 'Standing Calf Raise (Barbell)', category: 'calves' },
    { nameRu: 'Подъём на носок стоя на одной ноге', name: 'Single Leg Standing Calf Raise', category: 'calves' },
    { nameRu: 'Подъём на носок стоя на одной ноге (в тренажёре)', name: 'Single Leg Standing Calf Raise (Machine)', category: 'calves' },
    { nameRu: 'Подъём на носок стоя на одной ноге (с гантелей)', name: 'Single Leg Standing Calf Raise (Dumbbell)', category: 'calves' },
    { nameRu: 'Подъём на носок стоя на одной ноге (со штангой)', name: 'Single Leg Standing Calf Raise (Barbell)', category: 'calves' },
    // === Кардио (22) ===
    { nameRu: 'Аэробика', name: 'Aerobics', category: 'cardio' },
    { nameRu: 'Бег', name: 'Running', category: 'cardio' },
    { nameRu: 'Беговая дорожка', name: 'Treadmill', category: 'cardio' },
    { nameRu: 'Бокс', name: 'Boxing', category: 'cardio' },
    { nameRu: 'Велосипед', name: 'Cycling', category: 'cardio' },
    { nameRu: 'Велосипед в воздухе', name: 'Air Bike', category: 'cardio' },
    { nameRu: 'Гребной тренажёр', name: 'Rowing Machine', category: 'cardio' },
    { nameRu: 'Канатные волны', name: 'Battle Ropes', category: 'cardio' },
    { nameRu: 'Лыжи', name: 'Skiing', category: 'cardio' },
    { nameRu: 'Пеший поход', name: 'Hiking', category: 'cardio' },
    { nameRu: 'Плавание', name: 'Swimming', category: 'cardio' },
    { nameRu: 'Сайклинг', name: 'Spinning', category: 'cardio' },
    { nameRu: 'Скакалка', name: 'Jump Rope', category: 'cardio' },
    { nameRu: 'Скалолазание', name: 'Climbing', category: 'cardio' },
    { nameRu: 'Скольжение (скейтинг)', name: 'Skating', category: 'cardio' },
    { nameRu: 'Сноуборд', name: 'Snowboarding', category: 'cardio' },
    { nameRu: 'Спринт', name: 'Sprints', category: 'cardio' },
    { nameRu: 'Степпер', name: 'Stair Machine', category: 'cardio' },
    { nameRu: 'Степпер (шаги)', name: 'Stair Machine (Steps)', category: 'cardio' },
    { nameRu: 'Степпер (этажи)', name: 'Stair Machine (Floors)', category: 'cardio' },
    { nameRu: 'Ходьба', name: 'Walking', category: 'cardio' },
    { nameRu: 'Эллиптический тренажёр', name: 'Elliptical Trainer', category: 'cardio' },
    // === Грудь (48) ===
    { nameRu: 'Бабочка (пек-дек)', name: 'Butterfly (Pec Deck)', category: 'chest' },
    { nameRu: 'Вокруг света', name: 'Around The World', category: 'chest' },
    { nameRu: 'Жим гантелей нейтральным хватом (с гантелями)', name: 'Hex Press (Dumbbell)', category: 'chest' },
    { nameRu: 'Жим гантелей с сжатием', name: 'Dumbbell Squeeze Press', category: 'chest' },
    { nameRu: 'Жим лёжа (в Смите)', name: 'Bench Press (Smith Machine)', category: 'chest' },
    { nameRu: 'Жим лёжа (на блоке)', name: 'Bench Press (Cable)', category: 'chest' },
    { nameRu: 'Жим лёжа (с гантелями)', name: 'Bench Press (Dumbbell)', category: 'chest' },
    { nameRu: 'Жим лёжа (со штангой)', name: 'Bench Press (Barbell)', category: 'chest' },
    { nameRu: 'Жим лёжа на наклонной скамье (в Смите)', name: 'Incline Bench Press (Smith Machine)', category: 'chest' },
    { nameRu: 'Жим лёжа на наклонной скамье (с гантелями)', name: 'Incline Bench Press (Dumbbell)', category: 'chest' },
    { nameRu: 'Жим лёжа на наклонной скамье (со штангой)', name: 'Incline Bench Press (Barbell)', category: 'chest' },
    { nameRu: 'Жим лёжа на наклонной скамье вниз (в Смите)', name: 'Decline Bench Press (Smith Machine)', category: 'chest' },
    { nameRu: 'Жим лёжа на наклонной скамье вниз (в тренажёре)', name: 'Decline Bench Press (Machine)', category: 'chest' },
    { nameRu: 'Жим лёжа на наклонной скамье вниз (с гантелями)', name: 'Decline Bench Press (Dumbbell)', category: 'chest' },
    { nameRu: 'Жим лёжа на наклонной скамье вниз (со штангой)', name: 'Decline Bench Press (Barbell)', category: 'chest' },
    { nameRu: 'Жим лёжа с поднятыми ногами', name: 'Feet Up Bench Press (Barbell)', category: 'chest' },
    { nameRu: 'Жим лёжа с пола (с гантелями)', name: 'Floor Press (Dumbbell)', category: 'chest' },
    { nameRu: 'Жим лёжа с пола (со штангой)', name: 'Floor Press (Barbell)', category: 'chest' },
    { nameRu: 'Жим лёжа широким хватом (со штангой)', name: 'Bench Press - Wide Grip (Barbell)', category: 'chest' },
    { nameRu: 'Жим от груди (в тренажёре)', name: 'Chest Press (Machine)', category: 'chest' },
    { nameRu: 'Жим от груди (с резиной)', name: 'Chest Press (Band)', category: 'chest' },
    { nameRu: 'Жим от груди на наклонной скамье (в тренажёре)', name: 'Incline Chest Press (Machine)', category: 'chest' },
    { nameRu: 'Жим от груди раздельный (в тренажёре)', name: 'Iso-Lateral Chest Press (Machine)', category: 'chest' },
    { nameRu: 'Жим с диском', name: 'Plate Press', category: 'chest' },
    { nameRu: 'Отжимание', name: 'Push Up', category: 'chest' },
    { nameRu: 'Отжимание (с отягощением)', name: 'Push Up (Weighted)', category: 'chest' },
    { nameRu: 'Отжимание из планки', name: 'Plank Pushup', category: 'chest' },
    { nameRu: 'Отжимание одной рукой', name: 'One Arm Push Up', category: 'chest' },
    { nameRu: 'Отжимание узким хватом', name: 'Push Up - Close Grip', category: 'chest' },
    { nameRu: 'Отжимания на брусьях (на грудь)', name: 'Chest Dip', category: 'chest' },
    { nameRu: 'Отжимания на брусьях на грудь (с отягощением)', name: 'Chest Dip (Weighted)', category: 'chest' },
    { nameRu: 'Отжимания на брусьях на грудь (с помощью)', name: 'Chest Dip (Assisted)', category: 'chest' },
    { nameRu: 'Отжимания на кольцах', name: 'Ring Dips', category: 'chest' },
    { nameRu: 'Отжимания на кольцах', name: 'Ring Push Up', category: 'chest' },
    { nameRu: 'Отжимания с колен', name: 'Kneeling Push Up', category: 'chest' },
    { nameRu: 'Отжимания с ногами на возвышении', name: 'Decline Push Up', category: 'chest' },
    { nameRu: 'Отжимания с руками на возвышении', name: 'Incline Push Ups', category: 'chest' },
    { nameRu: 'Отжимания с хлопком', name: 'Clap Push Ups', category: 'chest' },
    { nameRu: 'Разведение на грудь (в петлях TRX)', name: 'Chest Fly (Suspension)', category: 'chest' },
    { nameRu: 'Разведение на грудь (в тренажёре)', name: 'Chest Fly (Machine)', category: 'chest' },
    { nameRu: 'Разведение на грудь (с гантелями)', name: 'Chest Fly (Dumbbell)', category: 'chest' },
    { nameRu: 'Разведение на грудь (с резиной)', name: 'Chest Fly (Band)', category: 'chest' },
    { nameRu: 'Разведение на наклонной скамье (с гантелями)', name: 'Incline Chest Fly (Dumbbell)', category: 'chest' },
    { nameRu: 'Разведение на наклонной скамье вниз (с гантелями)', name: 'Decline Chest Fly (Dumbbell)', category: 'chest' },
    { nameRu: 'Сведение одной рукой (на блоке)', name: 'Single Arm Cable Crossover', category: 'chest' },
    { nameRu: 'Сведение рук в кроссовере', name: 'Cable Fly Crossovers', category: 'chest' },
    { nameRu: 'Сведение рук в кроссовере снизу', name: 'Low Cable Fly Crossovers', category: 'chest' },
    { nameRu: 'Сведение рук сидя (на блоке)', name: 'Seated Chest Flys (Cable)', category: 'chest' },
    // === Предплечья (4) ===
    { nameRu: 'Разгибание запястий сидя (со штангой)', name: 'Seated Wrist Extension (Barbell)', category: 'forearms' },
    { nameRu: 'Роллер для запястий', name: 'Wrist Roller', category: 'forearms' },
    { nameRu: 'Сгибание запястий за спиной (со штангой)', name: 'Behind the Back Bicep Wrist Curl (Barbell)', category: 'forearms' },
    { nameRu: 'Сгибание запястий сидя ладонями вверх', name: 'Seated Palms Up Wrist Curl', category: 'forearms' },
    // === Ягодицы (25) ===
    { nameRu: 'Лягушачий мост (с гантелью)', name: 'Frog Pumps (Dumbbell)', category: 'glutes' },
    { nameRu: 'Обратная гиперэкстензия', name: 'Reverse Hyperextension', category: 'glutes' },
    { nameRu: 'Отведение ноги назад (в тренажёре)', name: 'Glute Kickback (Machine)', category: 'glutes' },
    { nameRu: 'Отведение ноги назад (тренажёр)', name: 'Rear Kick (Machine)', category: 'glutes' },
    { nameRu: 'Отведение ноги назад на полу', name: 'Glute Kickback on Floor', category: 'glutes' },
    { nameRu: 'Отведение ноги назад стоя (на блоке)', name: 'Standing Cable Glute Kickbacks', category: 'glutes' },
    { nameRu: 'Пожарный гидрант', name: 'Fire Hydrants', category: 'glutes' },
    { nameRu: 'Протяжка на блоке между ног', name: 'Cable Pull Through', category: 'glutes' },
    { nameRu: 'Ракушка', name: 'Clamshell', category: 'glutes' },
    { nameRu: 'Становая тяга (в Смите)', name: 'Deadlift (Smith Machine)', category: 'glutes' },
    { nameRu: 'Становая тяга (с гантелями)', name: 'Deadlift (Dumbbell)', category: 'glutes' },
    { nameRu: 'Становая тяга (с резиной)', name: 'Deadlift (Band)', category: 'glutes' },
    { nameRu: 'Становая тяга (с трэп-грифом)', name: 'Deadlift (Trap bar)', category: 'glutes' },
    { nameRu: 'Становая тяга (со штангой)', name: 'Deadlift (Barbell)', category: 'glutes' },
    { nameRu: 'Становая тяга сумо', name: 'Sumo Deadlift', category: 'glutes' },
    { nameRu: 'Ходьба с резиной в стороны', name: 'Lateral Band Walks', category: 'glutes' },
    { nameRu: 'Частичный ягодичный мост со штангой', name: 'Partial Glute Bridge (Barbell)', category: 'glutes' },
    { nameRu: 'Ягодичный мост', name: 'Hip Thrust', category: 'glutes' },
    { nameRu: 'Ягодичный мост (в тренажёре)', name: 'Hip Thrust (Machine)', category: 'glutes' },
    { nameRu: 'Ягодичный мост (со штангой)', name: 'Hip Thrust (Barbell)', category: 'glutes' },
    { nameRu: 'Ягодичный мост в Смите', name: 'Hip Thrust (Smith Machine)', category: 'glutes' },
    { nameRu: 'Ягодичный мост на одной ноге', name: 'Single Leg Hip Thrust', category: 'glutes' },
    { nameRu: 'Ягодичный мост на одной ноге (с гантелей)', name: 'Single Leg Hip Thrust (Dumbbell)', category: 'glutes' },
    { nameRu: 'Ягодичный мостик', name: 'Glute Bridge', category: 'glutes' },
    { nameRu: 'Ягодичный мостик на одной ноге', name: 'Single Leg Glute Bridge', category: 'glutes' },
    // === Бицепс бедра (11) ===
    { nameRu: 'Гуд морнинг (со штангой)', name: 'Good Morning (Barbell)', category: 'hamstrings' },
    { nameRu: 'Нордические сгибания (на бицепс бедра)', name: 'Nordic Hamstrings Curls', category: 'hamstrings' },
    { nameRu: 'Румынская тяга (с гантелями)', name: 'Romanian Deadlift (Dumbbell)', category: 'hamstrings' },
    { nameRu: 'Румынская тяга (со штангой)', name: 'Romanian Deadlift (Barbell)', category: 'hamstrings' },
    { nameRu: 'Румынская тяга на одной ноге (с гантелей)', name: 'Single Leg Romanian Deadlift (Dumbbell)', category: 'hamstrings' },
    { nameRu: 'Румынская тяга на одной ноге (со штангой)', name: 'Single Leg Romanian Deadlift (Barbell)', category: 'hamstrings' },
    { nameRu: 'Сгибание ног лёжа (в тренажёре)', name: 'Lying Leg Curl (Machine)', category: 'hamstrings' },
    { nameRu: 'Сгибание ног сидя (в тренажёре)', name: 'Seated Leg Curl (Machine)', category: 'hamstrings' },
    { nameRu: 'Сгибание ног стоя', name: 'Standing Leg Curls', category: 'hamstrings' },
    { nameRu: 'Становая тяга на прямых ногах', name: 'Straight Leg Deadlift', category: 'hamstrings' },
    { nameRu: 'Ягодично-бедренный подъём (GHR)', name: 'Glute Ham Raise', category: 'hamstrings' },
    // === Широчайшие (26) ===
    { nameRu: 'Вертикальная тяга (тренажёр)', name: 'Vertical Traction (Machine)', category: 'lats' },
    { nameRu: 'Верхняя тяга раздельная (в тренажёре)', name: 'Iso-Lateral High Row (Machine)', category: 'lats' },
    { nameRu: 'Негативные подтягивания', name: 'Negative Pull Up', category: 'lats' },
    { nameRu: 'Подтягивание', name: 'Pull Up', category: 'lats' },
    { nameRu: 'Подтягивание (с отягощением)', name: 'Pull Up (Weighted)', category: 'lats' },
    { nameRu: 'Подтягивание (с помощью)', name: 'Pull Up (Assisted)', category: 'lats' },
    { nameRu: 'Подтягивание (с резиной)', name: 'Pull Up (Band)', category: 'lats' },
    { nameRu: 'Подтягивание к груди (Жиронда)', name: 'Sternum Pull up (Gironda)', category: 'lats' },
    { nameRu: 'Подтягивание киппингом', name: 'Kipping Pull Up', category: 'lats' },
    { nameRu: 'Подтягивание обратным хватом', name: 'Chin Up', category: 'lats' },
    { nameRu: 'Подтягивание обратным хватом (с отягощением)', name: 'Chin Up (Weighted)', category: 'lats' },
    { nameRu: 'Подтягивание обратным хватом (с помощью)', name: 'Chin Up (Assisted)', category: 'lats' },
    { nameRu: 'Подтягивание широким хватом', name: 'Wide Pull Up', category: 'lats' },
    { nameRu: 'Подтягивания на кольцах', name: 'Ring Pull Up', category: 'lats' },
    { nameRu: 'Пуловер (в тренажёре)', name: 'Pullover (Machine)', category: 'lats' },
    { nameRu: 'Пуловер (с гантелей)', name: 'Pullover (Dumbbell)', category: 'lats' },
    { nameRu: 'Тяга верхнего блока (в тренажёре)', name: 'Lat Pulldown (Machine)', category: 'lats' },
    { nameRu: 'Тяга верхнего блока (на блоке)', name: 'Lat Pulldown (Cable)', category: 'lats' },
    { nameRu: 'Тяга верхнего блока (с резиной)', name: 'Lat Pulldown (Band)', category: 'lats' },
    { nameRu: 'Тяга верхнего блока обратным хватом (на блоке)', name: 'Reverse Grip Lat Pulldown (Cable)', category: 'lats' },
    { nameRu: 'Тяга верхнего блока одной рукой', name: 'Single Arm Lat Pulldown', category: 'lats' },
    { nameRu: 'Тяга верхнего блока с колен (с резиной)', name: 'Kneeling Pulldown (band)', category: 'lats' },
    { nameRu: 'Тяга верхнего блока узким хватом (на блоке)', name: 'Lat Pulldown - Close Grip (Cable)', category: 'lats' },
    { nameRu: 'Тяга гантели в наклоне', name: 'Dumbbell Row', category: 'lats' },
    { nameRu: 'Тяга каната прямыми руками (на блоке)', name: 'Rope Straight Arm Pulldown', category: 'lats' },
    { nameRu: 'Тяга прямыми руками (на блоке)', name: 'Straight Arm Lat Pulldown (Cable)', category: 'lats' },
    // === Нижняя спина (3) ===
    { nameRu: 'Гиперэкстензия', name: 'Back Extension (Hyperextension)', category: 'lower_back' },
    { nameRu: 'Гиперэкстензия (с отягощением)', name: 'Back Extension (Weighted Hyperextension)', category: 'lower_back' },
    { nameRu: 'Разгибание спины (в тренажёре)', name: 'Back Extension (Machine)', category: 'lower_back' },
    // === Шея (4) ===
    { nameRu: 'Разгибание шеи лёжа', name: 'Lying Neck Extension', category: 'neck' },
    { nameRu: 'Разгибание шеи лёжа (с отягощением)', name: 'Lying Neck Extension (Weighted)', category: 'neck' },
    { nameRu: 'Сгибание шеи лёжа', name: 'Lying Neck Curls', category: 'neck' },
    { nameRu: 'Сгибание шеи лёжа (с отягощением)', name: 'Lying Neck Curls (Weighted)', category: 'neck' },
    // === Квадрицепс (52) ===
    { nameRu: 'Боковое приседание', name: 'Lateral Squat', category: 'quadriceps' },
    { nameRu: 'Боковой выпад', name: 'Lateral Lunge', category: 'quadriceps' },
    { nameRu: 'Боковой прыжок на тумбу', name: 'Lateral Box Jump', category: 'quadriceps' },
    { nameRu: 'Болгарские сплит-приседания', name: 'Bulgarian Split Squat', category: 'quadriceps' },
    { nameRu: 'Выпад', name: 'Lunge', category: 'quadriceps' },
    { nameRu: 'Выпад (с гантелями)', name: 'Lunge (Dumbbell)', category: 'quadriceps' },
    { nameRu: 'Выпад (со штангой)', name: 'Lunge (Barbell)', category: 'quadriceps' },
    { nameRu: 'Выпад с гантелей над головой', name: 'Overhead Dumbbell Lunge', category: 'quadriceps' },
    { nameRu: 'Выпады в движении (с гантелями)', name: 'Walking Lunge (Dumbbell)', category: 'quadriceps' },
    { nameRu: 'Выпады с прыжком', name: 'Jumping Lunge', category: 'quadriceps' },
    { nameRu: 'Гакк-присед (в тренажёре)', name: 'Hack Squat (Machine)', category: 'quadriceps' },
    { nameRu: 'Гакк-приседания', name: 'Hack Squat', category: 'quadriceps' },
    { nameRu: 'Гоблет-присед (кубковый присед)', name: 'Goblet Squat', category: 'quadriceps' },
    { nameRu: 'Гоблет-присед с гирей', name: 'Kettlebell Goblet Squat', category: 'quadriceps' },
    { nameRu: 'Горизонтальный жим ногами (в тренажёре)', name: 'Leg Press Horizontal (Machine)', category: 'quadriceps' },
    { nameRu: 'Жим ногами (в тренажёре)', name: 'Leg Press (Machine)', category: 'quadriceps' },
    { nameRu: 'Жим ногой (в тренажёре)', name: 'Single Leg Press (Machine)', category: 'quadriceps' },
    { nameRu: 'Зашагивание на платформу', name: 'Step Up', category: 'quadriceps' },
    { nameRu: 'Зашагивания с гантелями', name: 'Dumbbell Step Up', category: 'quadriceps' },
    { nameRu: 'Лягушачьи прыжки', name: 'Frog Jumps', category: 'quadriceps' },
    { nameRu: 'Маятниковые приседания (в тренажёре)', name: 'Pendulum Squat (Machine)', category: 'quadriceps' },
    { nameRu: 'Обратный выпад', name: 'Reverse Lunge', category: 'quadriceps' },
    { nameRu: 'Обратный выпад (с гантелями)', name: 'Reverse Lunge (Dumbbell)', category: 'quadriceps' },
    { nameRu: 'Обратный выпад (со штангой)', name: 'Reverse Lunge (Barbell)', category: 'quadriceps' },
    { nameRu: 'Перекрёстный выпад (с гантелями)', name: 'Curtsy Lunge (Dumbbell)', category: 'quadriceps' },
    { nameRu: 'Полное приседание', name: 'Full Squat', category: 'quadriceps' },
    { nameRu: 'Присед на ящик', name: 'Box Squat', category: 'quadriceps' },
    { nameRu: 'Присед на ящик (со штангой)', name: 'Box Squat (Barbell)', category: 'quadriceps' },
    { nameRu: 'Присед с поясом (тренажёр)', name: 'Belt Squat (Machine)', category: 'quadriceps' },
    { nameRu: 'Приседание «пистолетик»', name: 'Pistol Squat', category: 'quadriceps' },
    { nameRu: 'Приседание «пистолетик» (с помощью)', name: 'Assisted Pistol Squats', category: 'quadriceps' },
    { nameRu: 'Приседание (в петлях TRX)', name: 'Squat (Suspension)', category: 'quadriceps' },
    { nameRu: 'Приседание (в Смите)', name: 'Squat (Smith Machine)', category: 'quadriceps' },
    { nameRu: 'Приседание (в тренажёре)', name: 'Squat (Machine)', category: 'quadriceps' },
    { nameRu: 'Приседание (с гантелями)', name: 'Squat (Dumbbell)', category: 'quadriceps' },
    { nameRu: 'Приседание (с резиной)', name: 'Squat (Band)', category: 'quadriceps' },
    { nameRu: 'Приседание (с собственным весом)', name: 'Squat (Bodyweight)', category: 'quadriceps' },
    { nameRu: 'Приседание (со штангой)', name: 'Squat (Barbell)', category: 'quadriceps' },
    { nameRu: 'Приседание Зерхера', name: 'Zercher Squat', category: 'quadriceps' },
    { nameRu: 'Приседание с выпрыгиванием', name: 'Jump Squat', category: 'quadriceps' },
    { nameRu: 'Приседание с паузой (со штангой)', name: 'Pause Squat (Barbell)', category: 'quadriceps' },
    { nameRu: 'Приседание сумо', name: 'Sumo Squat', category: 'quadriceps' },
    { nameRu: 'Приседание сумо (с гантелями)', name: 'Sumo Squat (Dumbbell)', category: 'quadriceps' },
    { nameRu: 'Приседание сумо (с гирей)', name: 'Sumo Squat (Kettlebell)', category: 'quadriceps' },
    { nameRu: 'Приседание сумо (со штангой)', name: 'Sumo Squat (Barbell)', category: 'quadriceps' },
    { nameRu: 'Прыжки на тумбу', name: 'Box Jump', category: 'quadriceps' },
    { nameRu: 'Разгибание ног (в тренажёре)', name: 'Leg Extension (Machine)', category: 'quadriceps' },
    { nameRu: 'Разгибание одной ногой', name: 'Single Leg Extensions', category: 'quadriceps' },
    { nameRu: 'Сисси-приседание (с отягощением)', name: 'Sissy Squat (Weighted)', category: 'quadriceps' },
    { nameRu: 'Сплит-приседание (с гантелями)', name: 'Split Squat (Dumbbell)', category: 'quadriceps' },
    { nameRu: 'Стульчик у стены', name: 'Wall Sit', category: 'quadriceps' },
    { nameRu: 'Фронтальное приседание', name: 'Front Squat', category: 'quadriceps' },
    // === Плечи (40) ===
    { nameRu: 'Y-подъёмы с упором в скамью (с гантелями)', name: 'Chest Supported Y Raise (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Армейский жим стоя (со штангой)', name: 'Standing Military Press (Barbell)', category: 'shoulders' },
    { nameRu: 'Вращение гири вокруг тела', name: 'Kettlebell Around the World', category: 'shoulders' },
    { nameRu: 'Жим (с гирей)', name: 'Kettlebell Shoulder Press', category: 'shoulders' },
    { nameRu: 'Жим Арнольда (с гантелями)', name: 'Arnold Press (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Жим на плечи (в тренажёре)', name: 'Shoulder Press (Machine)', category: 'shoulders' },
    { nameRu: 'Жим на плечи (с гантелями)', name: 'Shoulder Press (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Жим над головой (в Смите)', name: 'Overhead Press (Smith Machine)', category: 'shoulders' },
    { nameRu: 'Жим над головой (с гантелями)', name: 'Overhead Press (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Жим над головой (со штангой)', name: 'Overhead Press (Barbell)', category: 'shoulders' },
    { nameRu: 'Жим над головой сидя (с гантелями)', name: 'Seated Overhead Press (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Жим над головой сидя (со штангой)', name: 'Seated Overhead Press (Barbell)', category: 'shoulders' },
    { nameRu: 'Жим одной рукой в лэндмайне (со штангой)', name: 'Single Arm Landmine Press (Barbell)', category: 'shoulders' },
    { nameRu: 'Касание плеч в планке', name: 'Shoulder Taps', category: 'shoulders' },
    { nameRu: 'Махи в сторону одной рукой (на блоке)', name: 'Single Arm Lateral Raise (Cable)', category: 'shoulders' },
    { nameRu: 'Махи в стороны (в тренажёре)', name: 'Lateral Raise (Machine)', category: 'shoulders' },
    { nameRu: 'Махи в стороны (на блоке)', name: 'Lateral Raise (Cable)', category: 'shoulders' },
    { nameRu: 'Махи в стороны (с гантелями)', name: 'Lateral Raise (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Махи в стороны (с резиной)', name: 'Lateral Raise (Band)', category: 'shoulders' },
    { nameRu: 'Махи в стороны сидя (с гантелями)', name: 'Seated Lateral Raise (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Обратные разведения с упором в скамью (с гантелями)', name: 'Chest Supported Reverse Fly (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Отжимание уголком', name: 'Pike Pushup', category: 'shoulders' },
    { nameRu: 'Отжимания в стойке на руках', name: 'Handstand Push Up', category: 'shoulders' },
    { nameRu: 'Подъём блина над головой', name: 'Overhead Plate Raise', category: 'shoulders' },
    { nameRu: 'Подъём диска перед собой', name: 'Plate Front Raise', category: 'shoulders' },
    { nameRu: 'Подъём перед собой (в петлях TRX)', name: 'Front Raise (Suspension)', category: 'shoulders' },
    { nameRu: 'Подъём перед собой (на блоке)', name: 'Front Raise (Cable)', category: 'shoulders' },
    { nameRu: 'Подъём перед собой (с гантелями)', name: 'Front Raise (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Подъём перед собой (с резиной)', name: 'Front Raise (Band)', category: 'shoulders' },
    { nameRu: 'Подъём перед собой (со штангой)', name: 'Front Raise (Barbell)', category: 'shoulders' },
    { nameRu: 'Разведение на заднюю дельту (в тренажёре)', name: 'Rear Delt Reverse Fly (Machine)', category: 'shoulders' },
    { nameRu: 'Разведение на заднюю дельту (на блоке)', name: 'Rear Delt Reverse Fly (Cable)', category: 'shoulders' },
    { nameRu: 'Разведение на заднюю дельту (с гантелями)', name: 'Rear Delt Reverse Fly (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Разведение одной рукой (на блоке)', name: 'Reverse Fly Single Arm (Cable)', category: 'shoulders' },
    { nameRu: 'Разведение рук с резиной', name: 'Band Pullaparts', category: 'shoulders' },
    { nameRu: 'Тяга к подбородку (на блоке)', name: 'Upright Row (Cable)', category: 'shoulders' },
    { nameRu: 'Тяга к подбородку (с гантелями)', name: 'Upright Row (Dumbbell)', category: 'shoulders' },
    { nameRu: 'Тяга к подбородку (со штангой)', name: 'Upright Row (Barbell)', category: 'shoulders' },
    { nameRu: 'Фейс-пул (тяга к лицу)', name: 'Face Pull', category: 'shoulders' },
    { nameRu: 'Швунг жимовой', name: 'Push Press', category: 'shoulders' },
    // === Трапеции (5) ===
    { nameRu: 'Шраги (в Смите)', name: 'Shrug (Smith Machine)', category: 'traps' },
    { nameRu: 'Шраги (в тренажёре)', name: 'Shrug (Machine)', category: 'traps' },
    { nameRu: 'Шраги (на блоке)', name: 'Shrug (Cable)', category: 'traps' },
    { nameRu: 'Шраги (с гантелями)', name: 'Shrug (Dumbbell)', category: 'traps' },
    { nameRu: 'Шраги (со штангой)', name: 'Shrug (Barbell)', category: 'traps' },
    // === Трицепс (26) ===
    { nameRu: 'JM-жим (со штангой)', name: 'JM Press (Barbell)', category: 'triceps' },
    { nameRu: 'Алмазные отжимания', name: 'Diamond Push Up', category: 'triceps' },
    { nameRu: 'Жим лёжа узким хватом (со штангой)', name: 'Bench Press - Close Grip (Barbell)', category: 'triceps' },
    { nameRu: 'Жим на трицепс сидя', name: 'Seated Triceps Press', category: 'triceps' },
    { nameRu: 'Жим на трицепс широким хватом (гантели)', name: 'Wide-Elbow Triceps Press (Dumbbell)', category: 'triceps' },
    { nameRu: 'Обратные отжимания от пола на трицепс', name: 'Floor Triceps Dip', category: 'triceps' },
    { nameRu: 'Обратные отжимания от скамьи', name: 'Bench Dip', category: 'triceps' },
    { nameRu: 'Отведение на трицепс (на блоке)', name: 'Triceps Kickback (Cable)', category: 'triceps' },
    { nameRu: 'Отведение на трицепс (с гантелей)', name: 'Triceps Kickback (Dumbbell)', category: 'triceps' },
    { nameRu: 'Отжимание на брусьях', name: 'Triceps Dip', category: 'triceps' },
    { nameRu: 'Отжимание на брусьях (с отягощением)', name: 'Triceps Dip (Weighted)', category: 'triceps' },
    { nameRu: 'Отжимание на брусьях (с помощью)', name: 'Triceps Dip (Assisted)', category: 'triceps' },
    { nameRu: 'Отжимание на брусьях сидя (в тренажёре)', name: 'Seated Dip Machine', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс (в петлях TRX)', name: 'Triceps Extension (Suspension)', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс (в тренажёре)', name: 'Triceps Extension (Machine)', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс (на блоке)', name: 'Triceps Extension (Cable)', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс (с гантелей)', name: 'Triceps Extension (Dumbbell)', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс (со штангой)', name: 'Triceps Extension (Barbell)', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс на блоке', name: 'Triceps Pressdown', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс одной рукой (на блоке)', name: 'Single Arm Triceps Pushdown (Cable)', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс одной рукой (с гантелей)', name: 'Single Arm Tricep Extension (Dumbbell)', category: 'triceps' },
    { nameRu: 'Разгибание на трицепс с канатом (на блоке)', name: 'Triceps Rope Pushdown', category: 'triceps' },
    { nameRu: 'Разгибание рук на верхнем блоке', name: 'Triceps Pushdown', category: 'triceps' },
    { nameRu: 'Разгибание рук над головой (блок)', name: 'Overhead Triceps Extension (Cable)', category: 'triceps' },
    { nameRu: 'Французский жим лёжа (с гантелями)', name: 'Skullcrusher (Dumbbell)', category: 'triceps' },
    { nameRu: 'Французский жим лёжа (со штангой)', name: 'Skullcrusher (Barbell)', category: 'triceps' },
    // === Верхняя спина (22) ===
    { nameRu: 'Австралийские подтягивания (горизонтальная тяга)', name: 'Inverted Row', category: 'upper_back' },
    { nameRu: 'Вис на перекладине', name: 'Dead Hang', category: 'upper_back' },
    { nameRu: 'Нижняя тяга раздельная', name: 'Iso-Lateral Low Row', category: 'upper_back' },
    { nameRu: 'Низкая тяга (в петлях TRX)', name: 'Low Row (Suspension)', category: 'upper_back' },
    { nameRu: 'Подтягивания на лопатки', name: 'Scapular Pull Ups', category: 'upper_back' },
    { nameRu: 'Тяга «горилла» (с гирей)', name: 'Gorilla Row (Kettlebell)', category: 'upper_back' },
    { nameRu: 'Тяга в наклоне (с гантелями)', name: 'Bent Over Row (Dumbbell)', category: 'upper_back' },
    { nameRu: 'Тяга в наклоне (с резиной)', name: 'Bent Over Row (Band)', category: 'upper_back' },
    { nameRu: 'Тяга в наклоне (со штангой)', name: 'Bent Over Row (Barbell)', category: 'upper_back' },
    { nameRu: 'Тяга лэндмайн', name: 'Landmine Row', category: 'upper_back' },
    { nameRu: 'Тяга Мэдоуза (со штангой)', name: 'Meadows Rows (Barbell)', category: 'upper_back' },
    { nameRu: 'Тяга нижнего блока сидя — V-рукоять (на блоке)', name: 'Seated Cable Row - V Grip (Cable)', category: 'upper_back' },
    { nameRu: 'Тяга нижнего блока сидя — прямой гриф', name: 'Seated Cable Row - Bar Grip', category: 'upper_back' },
    { nameRu: 'Тяга нижнего блока сидя — широкий хват', name: 'Seated Cable Row - Bar Wide Grip', category: 'upper_back' },
    { nameRu: 'Тяга одной рукой (на блоке)', name: 'Single Arm Cable Row', category: 'upper_back' },
    { nameRu: 'Тяга Пендли (со штангой)', name: 'Pendlay Row (Barbell)', category: 'upper_back' },
    { nameRu: 'Тяга раздельная (в тренажёре)', name: 'Iso-Lateral Row (Machine)', category: 'upper_back' },
    { nameRu: 'Тяга ренегата (с гантелями)', name: 'Renegade Row (Dumbbell)', category: 'upper_back' },
    { nameRu: 'Тяга с плинтов (рэк-пулл)', name: 'Rack Pull', category: 'upper_back' },
    { nameRu: 'Тяга с упором в наклонную скамью (с гантелями)', name: 'Chest Supported Incline Row (Dumbbell)', category: 'upper_back' },
    { nameRu: 'Тяга сидя (в тренажёре)', name: 'Seated Row (Machine)', category: 'upper_back' },
    { nameRu: 'Тяга Т-грифа', name: 'T Bar Row', category: 'upper_back' },
];
