// exercises_db.js — Exercise library for program builder

const EXERCISE_CATEGORIES = [
    { id: 'chest',     nameRu: 'Грудь' },
    { id: 'back',      nameRu: 'Спина' },
    { id: 'legs',      nameRu: 'Ноги' },
    { id: 'glutes',    nameRu: 'Ягодицы' },
    { id: 'shoulders', nameRu: 'Плечи' },
    { id: 'arms',      nameRu: 'Руки' },
    { id: 'core',      nameRu: 'Пресс' },
    { id: 'cardio',    nameRu: 'Кардио' }
];

const EXERCISE_DB = [
    // === Грудь ===
    { nameRu: 'Жим штанги лёжа',              name: 'Barbell Bench Press',         category: 'chest' },
    { nameRu: 'Жим гантелей лёжа',            name: 'Dumbbell Bench Press',        category: 'chest' },
    { nameRu: 'Жим на наклонной скамье',       name: 'Incline Bench Press',         category: 'chest' },
    { nameRu: 'Жим гантелей на наклонной',     name: 'Incline Dumbbell Press',      category: 'chest' },
    { nameRu: 'Жим на наклонной в Смите',      name: 'Smith Incline Press',         category: 'chest' },
    { nameRu: 'Жим на наклонной вниз',         name: 'Decline Bench Press',         category: 'chest' },
    { nameRu: 'Жим в тренажёре на грудь',      name: 'Chest Press Machine',         category: 'chest' },
    { nameRu: 'Жим в тренажёре (конвергентный)', name: 'Converging Chest Press',    category: 'chest' },
    { nameRu: 'Разводка гантелей',             name: 'Dumbbell Flyes',              category: 'chest' },
    { nameRu: 'Разводка в тренажёре',          name: 'Machine Flyes',               category: 'chest' },
    { nameRu: 'Сведение рук в кроссовере',     name: 'Cable Crossover',             category: 'chest' },
    { nameRu: 'Сведение рук на нижних блоках', name: 'Low Cable Crossover',         category: 'chest' },
    { nameRu: 'Сведение в тренажёре (Pec Deck)', name: 'Pec Deck Machine',          category: 'chest' },
    { nameRu: 'Отжимания от пола',             name: 'Push-ups',                    category: 'chest' },
    { nameRu: 'Отжимания на брусьях',          name: 'Dips (Chest)',                category: 'chest' },
    { nameRu: 'Отжимания в тренажёре (грудь)', name: 'Machine Chest Dips',          category: 'chest' },
    { nameRu: 'Пуловер с гантелей',            name: 'Dumbbell Pullover',           category: 'chest' },

    // === Спина ===
    { nameRu: 'Подтягивания',                  name: 'Pull-ups',                    category: 'back' },
    { nameRu: 'Тяга верхнего блока',           name: 'Lat Pulldown',                category: 'back' },
    { nameRu: 'Тяга верхнего блока узким хватом', name: 'Close-Grip Pulldown',      category: 'back' },
    { nameRu: 'Тяга верхнего блока одной рукой', name: 'Single Arm Pulldown',       category: 'back' },
    { nameRu: 'Тяга верхнего блока (унилатеральная)', name: 'Unilateral Pulldown',  category: 'back' },
    { nameRu: 'Тяга штанги в наклоне',         name: 'Barbell Row',                 category: 'back' },
    { nameRu: 'Тяга штанги с опорой',          name: 'Supported Barbell Row',       category: 'back' },
    { nameRu: 'Тяга гантели в наклоне',        name: 'Dumbbell Row',                category: 'back' },
    { nameRu: 'Тяга гантелей на наклонной скамье', name: 'Incline Dumbbell Row',    category: 'back' },
    { nameRu: 'Тяга нижнего блока',            name: 'Seated Cable Row',            category: 'back' },
    { nameRu: 'Тяга нижнего блока одной рукой', name: 'Single Arm Cable Row',       category: 'back' },
    { nameRu: 'Тяга Т-грифа',                  name: 'T-Bar Row',                   category: 'back' },
    { nameRu: 'Тяга Т-грифа с опорой',         name: 'Supported T-Bar Row',         category: 'back' },
    { nameRu: 'Тяга с опорой на грудь',        name: 'Chest Supported Row',         category: 'back' },
    { nameRu: 'Тяга Дориана',                  name: 'Dorian Row',                  category: 'back' },
    { nameRu: 'Тяга Хаммер (верхняя)',         name: 'Hammer High Row',             category: 'back' },
    { nameRu: 'Тяга Хаммер (нижняя)',          name: 'Hammer Low Row',              category: 'back' },
    { nameRu: 'Тяга Хаммер одной рукой (верхняя)', name: 'Single Arm Hammer High Row', category: 'back' },
    { nameRu: 'Тяга Хаммер одной рукой (нижняя)', name: 'Single Arm Hammer Low Row',  category: 'back' },
    { nameRu: 'Тяга в тренажёре с упором',     name: 'Supported Row Machine',       category: 'back' },
    { nameRu: 'Горизонтальная тяга в тренажёре', name: 'Seated Row Machine',        category: 'back' },
    { nameRu: 'Тяга сверху в тренажёре (поочерёдно)', name: 'Alternating Pulldown Machine', category: 'back' },
    { nameRu: 'Гиперэкстензия',                name: 'Hyperextension',              category: 'back' },
    { nameRu: 'Шраги со штангой',              name: 'Barbell Shrugs',              category: 'back' },
    { nameRu: 'Шраги с гантелями',             name: 'Dumbbell Shrugs',             category: 'back' },

    // === Ноги ===
    { nameRu: 'Приседания со штангой',          name: 'Barbell Squat',               category: 'legs' },
    { nameRu: 'Фронтальные приседания',         name: 'Front Squat',                 category: 'legs' },
    { nameRu: 'Присед в Смите',                name: 'Smith Machine Squat',         category: 'legs' },
    { nameRu: 'Присед в маятниковом тренажёре', name: 'Pendulum Squat',             category: 'legs' },
    { nameRu: 'Гакк-приседания',               name: 'Hack Squat',                  category: 'legs' },
    { nameRu: 'Гакк-присед с резинкой (обратный)', name: 'Reverse Hack Squat',      category: 'legs' },
    { nameRu: 'Жим ногами',                    name: 'Leg Press',                   category: 'legs' },
    { nameRu: 'Жим ногами 45°',               name: 'Leg Press 45',                category: 'legs' },
    { nameRu: 'Жим одной ногой',               name: 'Single Leg Press',            category: 'legs' },
    { nameRu: 'Разгибание ног в тренажёре',    name: 'Leg Extension',               category: 'legs' },
    { nameRu: 'Разгибание ноги (поочерёдно)',  name: 'Single Leg Extension',        category: 'legs' },
    { nameRu: 'Сгибание ног лёжа',             name: 'Lying Leg Curl',              category: 'legs' },
    { nameRu: 'Сгибание ног сидя',             name: 'Seated Leg Curl',             category: 'legs' },
    { nameRu: 'Сгибание ноги сидя (поочерёдно)', name: 'Single Seated Leg Curl',   category: 'legs' },
    { nameRu: 'Сгибание ног стоя',             name: 'Standing Leg Curl',           category: 'legs' },
    { nameRu: 'Становая тяга',                 name: 'Deadlift',                    category: 'legs' },
    { nameRu: 'Румынская тяга',                name: 'Romanian Deadlift',           category: 'legs' },
    { nameRu: 'Румынская тяга в тренажёре',    name: 'Romanian Deadlift Machine',   category: 'legs' },
    { nameRu: 'Мёртвая тяга со штангой',       name: 'Stiff Legged Deadlift',       category: 'legs' },
    { nameRu: 'Мёртвая тяга с гантелями',      name: 'Dumbbell Stiff Legged Deadlift', category: 'legs' },
    { nameRu: 'Мёртвая тяга в Смите',          name: 'Smith Stiff Legged Deadlift', category: 'legs' },
    { nameRu: 'Выпады с гантелями',            name: 'Dumbbell Lunges',             category: 'legs' },
    { nameRu: 'Болгарские сплит-приседания',    name: 'Bulgarian Split Squat',       category: 'legs' },
    { nameRu: 'Подъём на носки стоя',           name: 'Standing Calf Raise',         category: 'legs' },
    { nameRu: 'Подъём на носки сидя',           name: 'Seated Calf Raise',           category: 'legs' },
    { nameRu: 'Подъём на носки (тренажёр)',     name: 'Calf Raise Machine',          category: 'legs' },
    { nameRu: 'Подъём передней части стопы',    name: 'Tibial Raise',                category: 'legs' },

    // === Ягодицы ===
    { nameRu: 'Ягодичный мост со штангой',      name: 'Barbell Hip Thrust',          category: 'glutes' },
    { nameRu: 'Ягодичный мост (тренажёр)',      name: 'Hip Thrust Machine',          category: 'glutes' },
    { nameRu: 'Ягодичный мост одной ногой',     name: 'Single Leg Hip Thrust',       category: 'glutes' },
    { nameRu: 'Отведение ноги назад (кабель)',  name: 'Cable Kickback',              category: 'glutes' },
    { nameRu: 'Отведение ноги назад (тренажёр)', name: 'Glute Kickback Machine',     category: 'glutes' },
    { nameRu: 'Отведение ноги назад (верхний блок)', name: 'High Cable Kickback',    category: 'glutes' },
    { nameRu: 'Разведение ног в тренажёре',     name: 'Hip Abduction Machine',       category: 'glutes' },
    { nameRu: 'Разведение ног (разминка)',      name: 'Hip Abduction Warmup',        category: 'glutes' },
    { nameRu: 'Сведение ног в тренажёре',       name: 'Hip Adduction Machine',       category: 'glutes' },
    { nameRu: 'Сведение ног (разминка)',        name: 'Hip Adduction Warmup',        category: 'glutes' },
    { nameRu: 'Сплит-присед на ягодицы',       name: 'Glute Split Squat',           category: 'glutes' },
    { nameRu: 'Средняя ягодичная на нижнем блоке', name: 'Cable Glute Med',         category: 'glutes' },
    { nameRu: 'Подъём на платформу (поочерёдно)', name: 'Step-up',                   category: 'glutes' },

    // === Плечи ===
    { nameRu: 'Жим штанги стоя',               name: 'Overhead Press',              category: 'shoulders' },
    { nameRu: 'Жим гантелей сидя',             name: 'Seated Dumbbell Press',       category: 'shoulders' },
    { nameRu: 'Жим в тренажёре на плечи',      name: 'Shoulder Press Machine',      category: 'shoulders' },
    { nameRu: 'Махи гантелями в стороны',       name: 'Lateral Raises',              category: 'shoulders' },
    { nameRu: 'Махи гантелями сидя',           name: 'Seated Lateral Raises',       category: 'shoulders' },
    { nameRu: 'Махи гантелями стоя',           name: 'Standing Lateral Raises',     category: 'shoulders' },
    { nameRu: 'Подъём гантелей в стороны (тренажёр)', name: 'Lateral Raise Machine', category: 'shoulders' },
    { nameRu: 'Махи в стороны в кроссовере',    name: 'Cable Lateral Raises',        category: 'shoulders' },
    { nameRu: 'Махи в тренажёре',              name: 'Machine Lateral Raises',      category: 'shoulders' },
    { nameRu: 'Махи гантелей перед собой',      name: 'Front Raises',                category: 'shoulders' },
    { nameRu: 'Махи гантелями на наклонной скамье', name: 'Incline Bench Lateral Raises', category: 'shoulders' },
    { nameRu: 'Разводка в наклоне (задняя дельта)', name: 'Rear Delt Flyes',         category: 'shoulders' },
    { nameRu: 'Обратные разведения в тренажёре', name: 'Reverse Pec Deck',           category: 'shoulders' },
    { nameRu: 'Разводка в тренажёре / Задние дельты на блоке', name: 'Rear Delt Machine/Cable', category: 'shoulders' },
    { nameRu: 'Тяга штанги к подбородку',       name: 'Upright Row',                 category: 'shoulders' },
    { nameRu: 'Тяга к лицу (Face Pull)',        name: 'Face Pull',                   category: 'shoulders' },
    { nameRu: '6 Ways (разминка плеч)',         name: '6 Ways Shoulder Warmup',      category: 'shoulders' },

    // === Руки ===
    { nameRu: 'Подъём штанги на бицепс',        name: 'Barbell Curl',                category: 'arms' },
    { nameRu: 'Подъём гантелей на бицепс',      name: 'Dumbbell Curl',               category: 'arms' },
    { nameRu: 'Подъём на нижнем блоке (поочерёдно)', name: 'Single Arm Cable Curl',  category: 'arms' },
    { nameRu: 'Молотковые сгибания',            name: 'Hammer Curl',                 category: 'arms' },
    { nameRu: 'Байесовские сгибания',           name: 'Bayesian Curl',               category: 'arms' },
    { nameRu: 'Сгибания на бицепс в кроссовере', name: 'Cable Curl',                 category: 'arms' },
    { nameRu: 'Сгибания на скамье Скотта',      name: 'Preacher Curl',               category: 'arms' },
    { nameRu: 'Сгибание на скамье Скотта (гантель, поочерёдно)', name: 'Single Arm Dumbbell Preacher Curl', category: 'arms' },
    { nameRu: 'Концентрированные сгибания',      name: 'Concentration Curl',          category: 'arms' },
    { nameRu: 'Французский жим лёжа',           name: 'Skull Crushers',              category: 'arms' },
    { nameRu: 'Французский жим стоя',           name: 'Overhead Tricep Extension',   category: 'arms' },
    { nameRu: 'Французский жим из-за головы',   name: 'Overhead Cable Tricep Extension', category: 'arms' },
    { nameRu: 'Французский жим на наклонной',   name: 'Incline Skull Crushers',      category: 'arms' },
    { nameRu: 'Разгибание рук на блоке',        name: 'Tricep Pushdown',             category: 'arms' },
    { nameRu: 'Разгибание рук с канатом',       name: 'Rope Tricep Pushdown',        category: 'arms' },
    { nameRu: 'Разгибания на блоке (двойной канат)', name: 'Double Rope Pushdown',   category: 'arms' },
    { nameRu: 'Разгибание одной рукой (канат)', name: 'Single Arm Rope Pushdown',    category: 'arms' },
    { nameRu: 'Отжимания на брусьях (трицепс)',  name: 'Dips (Triceps)',              category: 'arms' },
    { nameRu: 'Жим узким хватом',               name: 'Close-Grip Bench Press',      category: 'arms' },
    { nameRu: 'Сгибания в запястьях',            name: 'Wrist Curls',                 category: 'arms' },

    // === Пресс ===
    { nameRu: 'Скручивания',                    name: 'Crunches',                    category: 'core' },
    { nameRu: 'Подъём ног в висе',              name: 'Hanging Leg Raise',           category: 'core' },
    { nameRu: 'Подъём ног лёжа',               name: 'Lying Leg Raise',             category: 'core' },
    { nameRu: 'Скручивания на блоке',           name: 'Cable Crunch',                category: 'core' },
    { nameRu: 'Планка',                         name: 'Plank',                       category: 'core' },
    { nameRu: 'Боковая планка',                 name: 'Side Plank',                  category: 'core' },
    { nameRu: 'Русские скручивания',             name: 'Russian Twist',               category: 'core' },
    { nameRu: 'Скручивания в тренажёре',         name: 'Ab Crunch Machine',           category: 'core' },
    { nameRu: 'Велосипед',                      name: 'Bicycle Crunch',              category: 'core' },

    // === Кардио ===
    { nameRu: 'Беговая дорожка',                name: 'Treadmill',                   category: 'cardio' },
    { nameRu: 'Эллиптический тренажёр',          name: 'Elliptical',                  category: 'cardio' },
    { nameRu: 'Велотренажёр',                   name: 'Stationary Bike',             category: 'cardio' },
    { nameRu: 'Гребной тренажёр',               name: 'Rowing Machine',              category: 'cardio' },
    { nameRu: 'Степпер',                        name: 'Stair Stepper',               category: 'cardio' },
    { nameRu: 'Прыжки на скакалке',             name: 'Jump Rope',                   category: 'cardio' }
];
