-- Technogym equipment catalog
-- Generated 2026-03-22
-- 105 records

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
(445, 'Technogym', 'MNFP', 'Selection 900 Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNFP.jpg'),
(446, 'Technogym', 'MNTP', 'Selection 900 Pectoral', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNTP.jpg'),
(447, 'Technogym', 'MNXP', 'Selection 900 Reverse Fly', 'back', 'selectorized', 'rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNXP.jpg'),
(448, 'Technogym', 'MNEP', 'Selection 900 Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNEP.jpg'),
(449, 'Technogym', 'MNKP', 'Selection 900 Delts Machine', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNKP.jpg'),
(450, 'Technogym', 'MN3P', 'Selection 900 Multi Flight', 'shoulders', 'selectorized', 'lateral_raise,shrug', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MN3P.jpg'),
(451, 'Technogym', 'MNGP', 'Selection 900 Vertical Traction', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNGP.jpg'),
(452, 'Technogym', 'MNLP', 'Selection 900 Lat Machine', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNLP.jpg'),
(453, 'Technogym', 'MNVP', 'Selection 900 Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNVP.jpg'),
(454, 'Technogym', 'MNHP', 'Selection 900 Low Row', 'back', 'selectorized', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNHP.jpg'),
(455, 'Technogym', 'MNAP', 'Selection 900 Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNAP.jpg'),
(456, 'Technogym', 'MNJP', 'Selection 900 Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNJP.jpg'),
(457, 'Technogym', 'MNIP', 'Selection 900 Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNIP.jpg'),
(458, 'Technogym', 'MNUP', 'Selection 900 Prone Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNUP.jpg'),
(459, 'Technogym', 'MNPP', 'Selection 900 Abductor', 'glutes', 'selectorized', 'hip_abduction', NULL),
(460, 'Technogym', 'MNQP', 'Selection 900 Adductor', 'legs', 'selectorized', 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNQP.jpg'),
(461, 'Technogym', 'MN4P', 'Selection 900 Glute Press', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MN4P.jpg'),
(462, 'Technogym', 'MNP2', 'Selection 900 Hip Thrust', 'glutes', 'selectorized', 'hip_thrust', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNP2.jpg'),
(463, 'Technogym', 'MNDP', 'Selection 900 Multi Hip', 'glutes', 'selectorized', 'hip_abduction,hip_adduction,glute_kickback', NULL),
(464, 'Technogym', 'MN5P', 'Selection 900 Standing Calf', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MN5P.jpg'),
(465, 'Technogym', 'MNRP', 'Selection 900 Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNRP.jpg'),
(466, 'Technogym', 'MNSP', 'Selection 900 Arm Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNSP.jpg'),
(467, 'Technogym', 'MNBP', 'Selection 900 Abdominal Crunch', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNBP.jpg'),
(468, 'Technogym', 'MNZP', 'Selection 900 Total Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNZP.jpg'),
(469, 'Technogym', 'MNCP', 'Selection 900 Lower Back', 'core', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNCP.jpg'),
(470, 'Technogym', 'MNYP', 'Selection 900 Rotary Torso', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNYP.jpg'),
(471, 'Technogym', 'MNWP', 'Selection 900 Pulley', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNWP.jpg'),
(472, 'Technogym', 'MNFC', 'Selection 700 Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNFC.jpg'),
(473, 'Technogym', 'MNNC', 'Selection 700 Dual Pectoral / Reverse Fly', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNNC.jpg'),
(474, 'Technogym', 'MNEC', 'Selection 700 Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNEC.jpg'),
(475, 'Technogym', 'MNKC', 'Selection 700 Delts Machine', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNKC.jpg'),
(476, 'Technogym', 'MNGC', 'Selection 700 Vertical Traction', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNGC.jpg'),
(477, 'Technogym', 'MNLC', 'Selection 700 Lat Machine', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNLC.jpg'),
(478, 'Technogym', 'MNHC', 'Selection 700 Low Row', 'back', 'selectorized', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNHC.jpg'),
(479, 'Technogym', 'MNAC', 'Selection 700 Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNAC.jpg'),
(480, 'Technogym', 'MNJC', 'Selection 700 Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNJC.jpg'),
(481, 'Technogym', 'MNIC', 'Selection 700 Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNIC.jpg'),
(482, 'Technogym', 'MNMC', 'Selection 700 Dual Leg Extension / Curl', 'legs', 'selectorized', 'leg_extension,leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNMC.jpg'),
(483, 'Technogym', 'MNOC', 'Selection 700 Dual Abductor / Adductor', 'glutes', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNOC.jpg'),
(484, 'Technogym', 'MNDC', 'Selection 700 Multi Hip', 'glutes', 'selectorized', 'hip_abduction,hip_adduction,glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNDC.jpg'),
(485, 'Technogym', 'MNBC', 'Selection 700 Abdominal Crunch', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNBC.jpg'),
(486, 'Technogym', 'MNCC', 'Selection 700 Lower Back', 'core', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MNCC.jpg'),
(487, 'Technogym', 'MG0500', 'Pure Strength Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG0500.jpg'),
(488, 'Technogym', 'MG1000', 'Pure Strength Wide Chest Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(489, 'Technogym', 'MG1500', 'Pure Strength Incline Chest Press', 'chest', 'plate-loaded', 'incline_press', NULL),
(490, 'Technogym', 'MG9000', 'Pure Strength Pullover', 'chest', 'plate-loaded', 'pullover', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG9000.jpg'),
(491, 'Technogym', 'MG3500', 'Pure Strength Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG3500.jpg'),
(492, 'Technogym', 'MG2000', 'Pure Strength Pulldown', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(493, 'Technogym', 'MG2500', 'Pure Strength Low Row', 'back', 'plate-loaded', 'low_row', NULL),
(494, 'Technogym', 'MG3000', 'Pure Strength Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG3000.jpg'),
(495, 'Technogym', 'MG5000', 'Pure Strength Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG5000.jpg'),
(496, 'Technogym', 'MG7500', 'Pure Strength Linear Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG7500.jpg'),
(497, 'Technogym', 'MG8500', 'Pure Strength Hack Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG8500.jpg'),
(498, 'Technogym', 'MG6500', 'Pure Strength Leg Extension', 'legs', 'plate-loaded', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG6500.jpg'),
(499, 'Technogym', 'MG7000', 'Pure Strength Standing Leg Curl', 'legs', 'plate-loaded', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG7000.jpg'),
(500, 'Technogym', 'MG4000', 'Pure Strength Rear Kick', 'glutes', 'plate-loaded', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG4000.jpg'),
(501, 'Technogym', 'MG8000', 'Pure Strength Hip Thrust', 'glutes', 'plate-loaded', 'hip_thrust', NULL),
(502, 'Technogym', 'MG9500', 'Pure Strength Standing Abductor', 'glutes', 'plate-loaded', 'hip_abduction', NULL),
(503, 'Technogym', 'MG4500', 'Pure Strength Calf', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG4500.jpg'),
(504, 'Technogym', 'MG5500', 'Pure Strength Seated Dip', 'arms', 'plate-loaded', 'tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG5500.jpg'),
(505, 'Technogym', 'MG6000', 'Pure Strength Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG6000.jpg'),
(506, 'Technogym', 'MG86', 'Pure Strength Belt Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG86.jpg'),
(507, 'Technogym', 'MG87', 'Pure Strength Deadlift', 'back', 'plate-loaded', 'deadlift', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MG87.jpg'),
(508, 'Technogym', 'PG04', 'Pure Strength Adjustable Bench', 'full_body', 'bench', 'chest_press,incline_press,shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/PG04.jpg'),
(509, 'Technogym', 'PG07', 'Pure Strength Olympic Flat Bench', 'chest', 'bench', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/PG07.jpg'),
(510, 'Technogym', 'PG01', 'Pure Strength Olympic Incline Bench', 'chest', 'bench', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/PG01.jpg'),
(511, 'Technogym', 'PG23', 'Pure Strength Olympic Decline Bench', 'chest', 'bench', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/PG23.jpg'),
(512, 'Technogym', 'PG08', 'Pure Strength Olympic Military Bench', 'shoulders', 'bench', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/PG08.jpg'),
(513, 'Technogym', 'PG14', 'Pure Strength Flat Bench', 'chest', 'bench', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/PG14.jpg'),
(514, 'Technogym', 'PG03', 'Pure Strength Adjustable Decline Ab Crunch', 'core', 'bench', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/PG03.jpg'),
(515, 'Technogym', 'PG11', 'Pure Strength Olympic Power Rack', 'full_body', 'rack', 'squat,chest_press,shoulder_press', NULL),
(516, 'Technogym', 'MB20', 'Element+ Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB20.jpg'),
(517, 'Technogym', 'MB70', 'Element+ Pectoral', 'chest', 'selectorized', 'chest_fly', NULL),
(518, 'Technogym', 'MB15', 'Element+ Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB15.jpg'),
(519, 'Technogym', 'MB25', 'Element+ Vertical Traction', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB25.jpg'),
(520, 'Technogym', 'MB40', 'Element+ Lat Machine', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB40.jpg'),
(521, 'Technogym', 'MB95', 'Element+ Low Row', 'back', 'selectorized', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB95.jpg'),
(522, 'Technogym', 'MB50', 'Element+ Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(523, 'Technogym', 'MB30', 'Element+ Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB30.jpg'),
(524, 'Technogym', 'MB35', 'Element+ Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB35.jpg'),
(525, 'Technogym', 'MB10', 'Element+ Abductor', 'glutes', 'selectorized', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB10.jpg'),
(526, 'Technogym', 'MB05', 'Element+ Adductor', 'legs', 'selectorized', 'hip_adduction', NULL),
(527, 'Technogym', 'MB75', 'Element+ Glute', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB75.jpg'),
(528, 'Technogym', 'MB55', 'Element+ Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB55.jpg'),
(529, 'Technogym', 'MB60', 'Element+ Arm Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB60.jpg'),
(530, 'Technogym', 'MB65', 'Element+ Abdominal Crunch', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB65.jpg'),
(531, 'Technogym', 'MB45', 'Element+ Lower Back', 'core', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MB45.jpg'),
(532, 'Technogym', 'MM70', 'Biostrength Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM70.jpg'),
(533, 'Technogym', 'MM13', 'Biostrength Pectoral', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM13.jpg'),
(534, 'Technogym', 'MM31', 'Biostrength Reverse Fly', 'back', 'selectorized', 'rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM31.jpg'),
(535, 'Technogym', 'MM69', 'Biostrength Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM69.jpg'),
(536, 'Technogym', 'MM71', 'Biostrength Vertical Traction', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM71.jpg'),
(537, 'Technogym', 'MM80', 'Biostrength Low Row', 'back', 'selectorized', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM80.jpg'),
(538, 'Technogym', 'MM51', 'Biostrength Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM51.jpg'),
(539, 'Technogym', 'MM91', 'Biostrength Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM91.jpg'),
(540, 'Technogym', 'MM90', 'Biostrength Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM90.jpg'),
(541, 'Technogym', 'MM18', 'Biostrength Abductor', 'glutes', 'selectorized', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM18.jpg'),
(542, 'Technogym', 'MM17', 'Biostrength Adductor', 'legs', 'selectorized', 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM17.jpg'),
(543, 'Technogym', 'MM92', 'Biostrength Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM92.jpg'),
(544, 'Technogym', 'MM45', 'Biostrength Arm Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM45.jpg'),
(545, 'Technogym', 'MM58', 'Biostrength Lower Back', 'core', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM58.jpg'),
(546, 'Technogym', 'MM83', 'Biostrength Total Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MM83.jpg'),
(547, 'Technogym', 'M5800', 'Kinesis One', 'full_body', 'functional', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/M5800.jpg'),
(548, 'Technogym', 'MF25', 'Plurima Tower', 'full_body', 'functional', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MF25.jpg'),
(549, 'Technogym', 'MF30', 'Plurima Wall', 'full_body', 'functional', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/technogym/MF30.jpg');
