-- gym80 equipment catalog
-- Exported from Supabase DB on 2026-03-20
-- 140 records

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
-- gym80 SYGNUM (Selectorized)
(2, 'gym80', '3002', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3002.jpg'),
(3, 'gym80', '3005', 'Radial Gluteus', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3005.jpg'),
(4, 'gym80', '3006', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3006.jpg'),
(5, 'gym80', '3007', 'Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3007.jpg'),
(6, 'gym80', '3008', 'Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3008.jpg'),
(7, 'gym80', '3010', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3010.jpg'),
(8, 'gym80', '3011', 'Triceps Horizontal', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3011.jpg'),
(9, 'gym80', '3012', 'Pull Over Machine', 'chest', 'selectorized', 'pullover', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3012.jpg'),
(10, 'gym80', '3013', 'Standing Leg Curl', 'legs', 'selectorized', 'standing_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3013.jpg'),
(11, 'gym80', '3014', 'Chest Crossover Machine', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3014.jpg'),
(12, 'gym80', '3016', 'Seated Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3016.jpg'),
(13, 'gym80', '3017', 'Incline Chest Press', 'chest', 'selectorized', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3017.jpg'),
(14, 'gym80', '3018', 'Standing Calf', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3018.jpg'),
(15, 'gym80', '3020', 'Lat Pulldown Machine', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3020.jpg'),
(16, 'gym80', '3021', 'Butterfly with Pads', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3021.jpg'),
(17, 'gym80', '3022', 'Butterfly', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3022.jpg'),
(18, 'gym80', '3024', 'Twister', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3024.jpg'),
(19, 'gym80', '3025', 'Butterfly Reverse', 'shoulders', 'selectorized', 'rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3025.jpg'),
(20, 'gym80', '3027', 'Back Machine', 'back', 'selectorized', 'back_machine', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3027.jpg'),
(21, 'gym80', '3028', 'Abduction Machine', 'legs', 'selectorized', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3028.jpg'),
(22, 'gym80', '3029', 'Adductor Machine', 'legs', 'selectorized', 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3029.jpg'),
(23, 'gym80', '3030', 'Seated Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3030.jpg'),
(24, 'gym80', '3031', 'Lying Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3031.jpg'),
(25, 'gym80', '3032', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3032.jpg'),
(26, 'gym80', '3034', 'Lying Abdominal Machine', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3034.jpg'),
(27, 'gym80', '3036', 'Dip Machine', 'chest', 'selectorized', 'chest_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3036.jpg'),
(28, 'gym80', '3037', 'Special Abdominal Machine', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3037.jpg'),
(29, 'gym80', '3038', 'Lower Back Machine', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3038.jpg'),
(30, 'gym80', '3039', 'Seated Row (no chest support)', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3039.jpg'),
(31, 'gym80', '3040', 'Seated Row Machine', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3040.jpg'),
-- gym80 SYGNUM ISO
(32, 'gym80', '3047', 'Iso Lat', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3047.jpg'),
-- gym80 SYGNUM DUAL
(33, 'gym80', '3042', 'Dual Incline Chest Press', 'chest', 'selectorized', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3042.jpg'),
(34, 'gym80', '3043', 'Dual Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3043.jpg'),
(35, 'gym80', '3044', 'Dual Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3044.jpg'),
(36, 'gym80', '3045', 'Dual Seated Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3045.jpg'),
(37, 'gym80', '3046', 'Dual Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3046.jpg'),
-- gym80 CABLE ART
(38, 'gym80', '5101', 'Cable Art No.1 - Shoulder & Back', 'shoulders', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5101.jpg'),
(39, 'gym80', '5102', 'Cable Art No.2 - Latissimus & Trapezius', 'back', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5102.jpg'),
(40, 'gym80', '5103', 'Cable Art No.3 - Chest & Shoulder', 'chest', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5103.jpg'),
(41, 'gym80', '5104', 'Cable Art No.4 - Biceps & Triceps', 'arms', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5104.jpg'),
(42, 'gym80', '5105', 'Cable Art No.5 - Upper Body', 'chest', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5105.jpg'),
(43, 'gym80', '5106', 'Cable Art No.6 - Legs', 'legs', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5106.jpg'),
-- gym80 INNOVATION
(44, 'gym80', '5001', 'Innovation Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5001.jpg'),
(45, 'gym80', '5002', 'Innovation Glutes Machine', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5002.jpg'),
(46, 'gym80', '5003', 'Innovation Rowing Machine', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5003.jpg'),
(47, 'gym80', '5004', 'Innovation Curler', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5004.jpg'),
(48, 'gym80', '5006', 'Innovation Multi Extension Machine', 'back', 'selectorized', 'back_machine', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/5006.jpg'),
-- gym80 PURE KRAFT (Plate-Loaded)
(49, 'gym80', '4023', '45-Degree Linear Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4023.jpg'),
(50, 'gym80', '4038', 'Squat Machine', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4038.jpg'),
(51, 'gym80', '4159N', 'Hack Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4159n.jpg'),
(52, 'gym80', '4311', 'Lat Pulldown Dual', 'back', 'plate-loaded', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4311.jpg'),
(53, 'gym80', '4314', 'Seated Leg Press Dual', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4314.jpg'),
(54, 'gym80', '4317', 'Ab Swing', 'core', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4317.jpg'),
(55, 'gym80', '4318', 'Bent Over Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4318.jpg'),
(56, 'gym80', '4319', 'Low Row Dual', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4319.jpg'),
(57, 'gym80', '4320', 'Shoulder Press Dual', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4320.jpg'),
(58, 'gym80', '4321', 'Gluteus Kick Machine', 'legs', 'plate-loaded', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4321.jpg'),
(59, 'gym80', '4322', 'Seated Row Dual', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4322.jpg'),
(60, 'gym80', '4324', '45-Degree Pivot Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4324.jpg'),
(61, 'gym80', '4326', 'Chest Crossover Dual', 'chest', 'plate-loaded', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4326.jpg'),
(62, 'gym80', '4327', 'Power Row Dual', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4327.jpg'),
(63, 'gym80', '4328', 'Seated Chest Press Dual', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4328.jpg'),
(64, 'gym80', '4329N', 'Incline Chest Press Dual', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4329n.jpg'),
(65, 'gym80', '4332', 'Deadlift Rotating Grips Dual', 'back', 'plate-loaded', 'deadlift', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4332.jpg'),
(66, 'gym80', '4333', 'Deadlift Double Handle Grips Dual', 'back', 'plate-loaded', 'deadlift', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4333.jpg'),
(67, 'gym80', '4335', 'Triceps Dip Dual', 'arms', 'plate-loaded', 'tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4335.jpg'),
(68, 'gym80', '4336N', 'Leg Extension', 'legs', 'plate-loaded', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4336n.jpg'),
(69, 'gym80', '4337N', 'Lying Leg Curl', 'legs', 'plate-loaded', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4337n.jpg'),
(70, 'gym80', '4338N', 'Biceps Machine', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4338n.jpg'),
(71, 'gym80', '4339N', 'Triceps Extension', 'arms', 'plate-loaded', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4339n.jpg'),
(72, 'gym80', '4340', 'High Row Dual', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4340.jpg'),
(73, 'gym80', '4341', 'Chest Butterfly Dual', 'chest', 'plate-loaded', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4341.jpg'),
(74, 'gym80', '4342N', 'Rotating Abdominal Crunch', 'back', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4342n.jpg'),
(75, 'gym80', '4343', 'Abdominal Crunch', 'core', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4343.jpg'),
(76, 'gym80', '4344', 'Butterfly Reverse Dual', 'shoulders', 'plate-loaded', 'rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4344.jpg'),
(77, 'gym80', '4345', '55-Degree Standing Calf Raise', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4345.jpg'),
(78, 'gym80', '4346', 'Decline Chest Press Dual', 'chest', 'plate-loaded', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4346.jpg'),
(79, 'gym80', '4348', 'Tibia Dorsi Flexion', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4348.jpg'),
(80, 'gym80', '4350N', 'Pullover', 'back', 'plate-loaded', 'pullover', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4350n.jpg'),
(81, 'gym80', '4352', 'Booty Booster', 'legs', 'plate-loaded', 'hip_thrust', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4352.jpg'),
(82, 'gym80', '4353N', 'Pendulum Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4353n.jpg'),
(83, 'gym80', '4354', 'Vertical Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4354.jpg'),
(84, 'gym80', '4355', 'Biceps Curl Dual', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4355.jpg'),
(85, 'gym80', '4360', 'Belt Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4360.jpg'),
(86, 'gym80', '4372', 'Standing Multi-Joint', 'legs', 'plate-loaded', 'standing_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4372.jpg'),
(87, 'gym80', '4373', 'Standing Leg Curl', 'legs', 'plate-loaded', 'standing_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4373.jpg'),
(88, 'gym80', '4374', 'Standing Abduction', 'legs', 'plate-loaded', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4374.jpg'),
(89, 'gym80', '4379', 'Overhead Triceps', 'arms', 'plate-loaded', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4379.jpg'),
(90, 'gym80', '4382', 'Back Machine (rowing)', 'back', 'plate-loaded', 'back_machine', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4382.jpg'),
-- gym80 PURE KRAFT STRONG
(91, 'gym80', '4361', 'Strong Leg Press Dual', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4361.jpg'),
(92, 'gym80', '4362', 'Strong Decline Chest Press Dual', 'chest', 'plate-loaded', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4362.jpg'),
(93, 'gym80', '4363', 'Strong Shoulder Press Dual', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4363.jpg'),
(94, 'gym80', '4364', 'Strong Bench Press Dual', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4364.jpg'),
(95, 'gym80', '4365', 'Strong Incline Chest Press Dual', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4365.jpg'),
-- gym80 80CLASSICS
(96, 'gym80', '80CL0001', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0001.png'),
(97, 'gym80', '80CL0002', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0002.png'),
(98, 'gym80', '80CL0003', 'Radial Gluteus', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0003.png'),
(99, 'gym80', '80CL0004', 'Lower Back', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0004.png'),
(100, 'gym80', '80CL0006', 'Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0006.png'),
(101, 'gym80', '80CL0007', 'Special Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0007.png'),
(102, 'gym80', '80CL0008', 'Total Ab', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0008.png'),
(103, 'gym80', '80CL0009', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0009.png'),
(104, 'gym80', '80CL0010', 'Horizontal Triceps', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0010.png'),
(105, 'gym80', '80CL0011', 'Crossover', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0011.png'),
(106, 'gym80', '80CL0012', 'Deltoid Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0012.png'),
(107, 'gym80', '80CL0013', 'Seated Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0013.png'),
(108, 'gym80', '80CL0015', 'Standing Calf', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0015.png'),
(109, 'gym80', '80CL0016', 'Seated Row with Chest Pad', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0016.png'),
(110, 'gym80', '80CL0017', 'Butterfly with Handgrips', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0017.png'),
(111, 'gym80', '80CL0018', 'Butterfly Reverse', 'shoulders', 'selectorized', 'rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0018.png'),
(112, 'gym80', '80CL0019', 'Abduction Machine', 'legs', 'selectorized', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0019.png'),
(113, 'gym80', '80CL0020', 'Adduction Machine', 'legs', 'selectorized', 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0020.png'),
(114, 'gym80', '80CL0021', 'Seated Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0021.png'),
(115, 'gym80', '80CL0022', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0022.png'),
(116, 'gym80', '80CL0024', 'Lat Pulley', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0024.png'),
(117, 'gym80', '80CL0026', 'Standing Scott Curl', 'arms', 'selectorized', 'preacher_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0026.jpg'),
(118, 'gym80', '80CL0029', 'Total Hip', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/80CL0029.png'),
-- gym80 FTM
(119, 'gym80', '4401', 'FTM Deadlift Machine', 'back', 'selectorized', 'deadlift', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4401.jpg'),
(120, 'gym80', '4403', 'FTM Push & Pull Machine', 'chest', 'selectorized', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4403.jpg'),
-- gym80 PURE KRAFT (Plate-Loaded)
(300, 'gym80', '4002', 'Basic Multi Press Station', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4002.jpg'),
(301, 'gym80', '4036', 'Multipress Station', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4036.jpg'),
(302, 'gym80', '4040', 'Max Rack', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4040.jpg'),
(303, 'gym80', '4040 Basic', 'Basic Max Rack', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4040_Basic.jpg'),
-- gym80 SYGNUM (Selectorized)
(391, 'gym80', '3001', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/3001.jpg'),
-- gym80 PURE KRAFT (Plate-Loaded)
(392, 'gym80', '4018', 'T-Bar Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4018.jpg'),
(393, 'gym80', '4026', 'Seated Calf Raise', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4026.jpg'),
(394, 'gym80', '4307', 'Lying Abdominal', 'core', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4307.jpg'),
(395, 'gym80', '4325', 'Shoulder Lateral Raise Dual', 'shoulders', 'plate-loaded', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4325.jpg'),
(396, 'gym80', '4331', 'Bench Press Dual', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4331.jpg'),
(397, 'gym80', '4350', 'Pullover', 'chest', 'plate-loaded', 'pullover', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4350.jpg'),
(398, 'gym80', '4366', 'Biceps Overhead', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4366.jpg'),
(399, 'gym80', '4371', 'Neck Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4371.jpg'),
(400, 'gym80', '4375', 'Inverse Leg Curl', 'legs', 'plate-loaded', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4375.jpg'),
(401, 'gym80', '4376', 'Lying Inner Chest Dual', 'chest', 'plate-loaded', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4376.jpg'),
(402, 'gym80', '4380', 'Donkey Calf', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4380.jpg'),
(403, 'gym80', '4383', '55-Degree Rowing Machine', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4383.jpg'),
(404, 'gym80', '4384', 'Abduction 3D', 'legs', 'plate-loaded', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4384.jpg'),
(405, 'gym80', '4385', 'Standing Shoulder Lateral Raise', 'shoulders', 'plate-loaded', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4385.jpg'),
(406, 'gym80', '4386', 'Booty Booster Special', 'legs', 'plate-loaded', 'hip_thrust', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4386.jpg'),
(407, 'gym80', '4388', 'Viking Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gym80/4388.jpg')
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  name = EXCLUDED.name,
  muscle_group = EXCLUDED.muscle_group,
  equipment_type = EXCLUDED.equipment_type,
  exercise_type = EXCLUDED.exercise_type,
  image_url = EXCLUDED.image_url;
