-- Cybex equipment catalog
-- Exported from Supabase DB on 2026-03-20
-- 131 records (110 original + 21 PWR PLAY)

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
-- Cybex Eagle NX (Selectorized)
(186, 'Cybex', '20000', 'Eagle NX Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20000.png'),
(187, 'Cybex', '20010', 'Eagle NX Overhead Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20010.png'),
(188, 'Cybex', '20030', 'Eagle NX Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20030.png'),
(189, 'Cybex', '20040', 'Eagle NX Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20040.png'),
(190, 'Cybex', '20050', 'Eagle NX Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20050.png'),
(191, 'Cybex', '20060', 'Eagle NX Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20060.png'),
(192, 'Cybex', '20070', 'Eagle NX Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20070.png'),
(193, 'Cybex', '20080', 'Eagle NX Arm Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20080.png'),
(194, 'Cybex', '20090', 'Eagle NX Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20090.png'),
(195, 'Cybex', '20100', 'Eagle NX Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20100.png'),
(196, 'Cybex', '20120', 'Eagle NX Calf', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20120.png'),
(197, 'Cybex', '20130', 'Eagle NX Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20130.png'),
(198, 'Cybex', '20170', 'Eagle NX Glute', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20170.png'),
(199, 'Cybex', '20180', 'Eagle NX Hip Ab-Ad', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20180.png'),
(200, 'Cybex', '20190', 'Eagle NX Hip Torso', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/20190.png'),
-- Cybex Eagle (Discontinued)
(201, 'Cybex', '11000', 'Eagle Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11000.png'),
(202, 'Cybex', '11010', 'Eagle Overhead Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11010.png'),
(203, 'Cybex', '11020', 'Eagle Incline Pull', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11020.jpg'),
(204, 'Cybex', '11030', 'Eagle Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11030.png'),
(205, 'Cybex', '11040', 'Eagle Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11040.png'),
(206, 'Cybex', '11050', 'Eagle Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11050.png'),
(207, 'Cybex', '11060', 'Eagle Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11060.png'),
(208, 'Cybex', '11070', 'Eagle Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11070.png'),
(209, 'Cybex', '11080', 'Eagle Arm Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11080.png'),
(210, 'Cybex', '11090', 'Eagle Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11090.png'),
(211, 'Cybex', '11100', 'Eagle Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11100.png'),
(212, 'Cybex', '11110', 'Eagle Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11110.jpg'),
(213, 'Cybex', '11120', 'Eagle Calf Raise', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11120.png'),
(214, 'Cybex', '11130', 'Eagle Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11130.png'),
(215, 'Cybex', '11140', 'Eagle Prone Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11140.jpg'),
(216, 'Cybex', '11150', 'Eagle Incline Press', 'chest', 'selectorized', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11150.jpg'),
(217, 'Cybex', '11160', 'Eagle Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11160.jpg'),
(218, 'Cybex', '11170', 'Eagle Glute', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11170.jpg'),
(219, 'Cybex', '11180', 'Eagle Hip Abduction/Adduction', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11180.png'),
(220, 'Cybex', '11190', 'Eagle Torso Rotation', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/11190.png'),
-- Cybex VR3 (Selectorized)
(221, 'Cybex', '12000', 'VR3 Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12000.png'),
(222, 'Cybex', '12010', 'VR3 Overhead Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12010.webp'),
(223, 'Cybex', '12020', 'VR3 Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12020.webp'),
(224, 'Cybex', '12030', 'VR3 Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12030.webp'),
(225, 'Cybex', '12040', 'VR3 Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12040.webp'),
(226, 'Cybex', '12050', 'VR3 Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12050.webp'),
(227, 'Cybex', '12060', 'VR3 Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12060.webp'),
(228, 'Cybex', '12070', 'VR3 Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12070.webp'),
(229, 'Cybex', '12080', 'VR3 Arm Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12080.webp'),
(230, 'Cybex', '12090', 'VR3 Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12090.webp'),
(231, 'Cybex', '12100', 'VR3 Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12100.webp'),
(232, 'Cybex', '12120', 'VR3 Standing Calf', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12120.webp'),
(233, 'Cybex', '12190', 'VR3 Torso Rotation', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12190.webp'),
(234, 'Cybex', '12200', 'VR3 Hip Abduction', 'legs', 'selectorized', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12200.webp'),
(235, 'Cybex', '12210', 'VR3 Hip Adduction', 'legs', 'selectorized', 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/12210.webp'),
-- Cybex VR1 (Selectorized, Compact)
(236, 'Cybex', '13000', 'VR1 Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13000.png'),
(237, 'Cybex', '13010', 'VR1 Overhead Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13010.png'),
(238, 'Cybex', '13030', 'VR1 Row / Rear Delt', 'back', 'selectorized', 'seated_row,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13030.png'),
(239, 'Cybex', '13041', 'VR1 Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13041.png'),
(240, 'Cybex', '13050', 'VR1 Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13050.png'),
(241, 'Cybex', '13060', 'VR1 Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13060.png'),
(242, 'Cybex', '13075', 'VR1 Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13075.png'),
(243, 'Cybex', '13085', 'VR1 Arm Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13085.png'),
(244, 'Cybex', '13090', 'VR1 Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13090.png'),
(245, 'Cybex', '13100', 'VR1 Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13100.png'),
(246, 'Cybex', '13111', 'VR1 Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13111.png'),
(247, 'Cybex', '13120', 'VR1 Standing Calf', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13120.png'),
(248, 'Cybex', '13135', 'VR1 Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13135.png'),
(249, 'Cybex', '13170', 'VR1 Glute', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13170.png'),
(250, 'Cybex', '13180', 'VR1 Hip Ab-Ad', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13180.png'),
(251, 'Cybex', '13240', 'VR1 Multi-Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13240.png'),
(252, 'Cybex', '13250', 'VR1 Dual Lat/Row', 'back', 'selectorized', 'lat_pulldown,seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/13250.png'),
-- Cybex Ion Series (Selectorized)
(253, 'Cybex', 'CI-CP', 'Ion Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-CP.png'),
(254, 'Cybex', 'CI-SP', 'Ion Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-SP.png'),
(255, 'Cybex', 'CI-MP', 'Ion Multi Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-MP.png'),
(256, 'Cybex', 'CI-LP', 'Ion Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-LP.png'),
(257, 'Cybex', 'CI-LCE', 'Ion Leg Curl / Extension', 'legs', 'selectorized', 'leg_curl,leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-LCE.png'),
(258, 'Cybex', 'CI-SLCE', 'Ion Seated Leg Curl / Extension', 'legs', 'selectorized', 'leg_curl,leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-SLCE.png'),
(259, 'Cybex', 'CI-LPR', 'Ion Lat Pulldown / Low Row', 'back', 'selectorized', 'lat_pulldown,seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-LPR.png'),
(260, 'Cybex', 'CI-LAT', 'Ion Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-LAT.png'),
(261, 'Cybex', 'CI-ROW', 'Ion Seated Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-ROW.png'),
(262, 'Cybex', 'CI-PFR', 'Ion Pec Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-PFR.png'),
(263, 'Cybex', 'CI-BT', 'Ion Biceps / Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-BT.jpg'),
(264, 'Cybex', 'CI-HAA', 'Ion Hip Abductor / Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-HAA.png'),
(265, 'Cybex', 'CI-AB', 'Ion Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-AB.png'),
-- Cybex Bravo (Cable/Functional)
(266, 'Cybex', '8800', 'Bravo Advanced (Compact)', 'chest', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/8800.webp'),
(267, 'Cybex', '8810', 'Bravo Advanced (Tall)', 'chest', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/8810.png'),
(268, 'Cybex', '8830', 'Bravo Basic (Compact)', 'chest', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/8830.webp'),
(269, 'Cybex', '8840', 'Bravo Pro (Tall)', 'chest', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/8840.webp'),
-- Cybex Plate Loaded (5000 Series)
(270, 'Cybex', '5220', 'Plate Loaded Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5220.png'),
(271, 'Cybex', '5225', 'Plate Loaded Bench Press', 'chest', 'plate-loaded', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5225.jpg'),
(272, 'Cybex', '5226', 'Plate Loaded Advanced Pulldown', 'back', 'plate-loaded', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5226.jpg'),
(273, 'Cybex', '5227', 'Plate Loaded Converging Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5227.png'),
(274, 'Cybex', '5230', 'Plate Loaded Hack Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5230.jpg'),
(275, 'Cybex', '5235', 'Plate Loaded Squat Press', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5235.png'),
(276, 'Cybex', '5240', 'Plate Loaded Kneeling Leg Curl', 'legs', 'plate-loaded', 'kneeling_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5240.jpg'),
(277, 'Cybex', '5245', 'Plate Loaded Leg Extension', 'legs', 'plate-loaded', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5245.jpg'),
(278, 'Cybex', '5251', 'Plate Loaded Advanced Incline Press', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5251.jpg'),
(279, 'Cybex', '5252', 'Plate Loaded Converging Incline Press', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5252.jpg'),
(280, 'Cybex', '5255', 'Plate Loaded Rear Delt', 'shoulders', 'plate-loaded', 'rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5255.jpg'),
(281, 'Cybex', '5261', 'Plate Loaded Advanced Pulldown', 'back', 'plate-loaded', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5261.jpg'),
(282, 'Cybex', '5265', 'Plate Loaded Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5265.jpg'),
-- Cybex Big Iron (Racks)
(283, 'Cybex', '19000', 'Big Iron 9ft Half Rack', 'legs', 'rack', 'rack', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/19000.webp'),
(284, 'Cybex', '19010', 'Big Iron 8ft Half Rack', 'legs', 'rack', 'rack', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/19010.webp'),
(285, 'Cybex', '19040', 'Big Iron Power Rack', 'legs', 'rack', 'rack', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/19040.webp'),
-- Cybex Benches
(286, 'Cybex', '5410', 'Olympic Flat Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5410.webp'),
(287, 'Cybex', '5430', 'Flat Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5430.webp'),
(288, 'Cybex', '5435', 'Flat to Incline Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5435.webp'),
(290, 'Cybex', '5440', 'Adjustable Incline Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5440.jpg'),
(291, 'Cybex', '5460', 'Scott / Preacher Curl', 'arms', 'bench', 'preacher_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5460.png'),
(292, 'Cybex', '5502', 'Olympic Decline Bench', 'chest', 'bench', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5502.jpg'),
-- Cybex Plate Loaded (5000 Series)
(293, 'Cybex', '16210', 'Seated Calf', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/16210.png'),
-- Cybex Smith Press
(297, 'Cybex', '5341', 'Smith Press', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/5341.webp'),
-- Cybex Specialty
(298, 'Cybex', '16121', 'Plate Loaded Smith Press', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/16121.png'),
-- Cybex Ion Series (Selectorized)
(299, 'Cybex', 'CI-SM', 'Ion Series Smith Rack', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/CI-SM.png'),
-- Cybex PWR PLAY — Traditional Cable Stations
(408, 'Cybex', 'PP-AP', 'PWR Play Adjustable Pulley 2:1', 'full_body', 'cable', 'cable_multi', NULL),
(409, 'Cybex', 'PP-LP', 'PWR Play Lat Pull', 'back', 'cable', 'lat_pulldown', NULL),
(410, 'Cybex', 'PP-RW', 'PWR Play Low Row', 'back', 'cable', 'seated_row', NULL),
(411, 'Cybex', 'PP-TP', 'PWR Play Triceps Pushdown', 'arms', 'cable', 'tricep_extension', NULL),
(412, 'Cybex', 'PP-ACO', 'PWR Play Attached Cable Crossover', 'chest', 'cable', 'chest_fly,cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-ACO.png'),
(413, 'Cybex', 'PP-AXO', 'PWR Play Embedded Cable Crossover', 'chest', 'cable', 'chest_fly,cable_multi', NULL),
(414, 'Cybex', 'PP-ACO-FCS', 'PWR Play Free Standing Cable Crossover', 'chest', 'cable', 'chest_fly,cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-ACO-FCS.png'),
-- Cybex PWR PLAY — High Low / Crossover Stations
(415, 'Cybex', 'PP-FCO', 'PWR Play Attached High Low Crossover', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-FCO.png'),
(416, 'Cybex', 'PP-FXO', 'PWR Play Embedded High Low Crossover', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-FXO.png'),
(417, 'Cybex', 'PP-HL', 'PWR Play High Low Station', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-HL.png'),
-- Cybex PWR PLAY — PWR Stations
(418, 'Cybex', 'PP-AP41', 'PWR Play Adjustable Pulley 4:1', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-AP41.png'),
(419, 'Cybex', 'PP-ADC', 'PWR Play Dip Chin Assist', 'chest', 'cable', 'chest_dip,tricep_dip', NULL),
(420, 'Cybex', 'PP-LPD', 'PWR Play Dual Pulley Pulldown', 'back', 'cable', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-LPD.png'),
(421, 'Cybex', 'PP-RWD', 'PWR Play Dual Pulley Row', 'back', 'cable', 'seated_row', NULL),
(422, 'Cybex', 'PP-DPH', 'PWR Play Dual Pulley High', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-DPH.png'),
(423, 'Cybex', 'PP-DPL', 'PWR Play Dual Pulley Low', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/cybex/PP-DPL.png'),
-- Cybex PWR PLAY — PLAY Stations
(424, 'Cybex', 'PP-BX', 'PWR Play Boxing Station', 'full_body', 'cable', NULL, NULL),
(425, 'Cybex', 'PP-SB', 'PWR Play Stall Bars', 'full_body', 'cable', NULL, NULL),
(426, 'Cybex', 'PP-RPL', 'PWR Play Rope Pull', 'back', 'cable', 'cable_multi', NULL),
(427, 'Cybex', 'PP-RP', 'PWR Play Rope Pull Power Pivot', 'core', 'cable', 'cable_multi,torso_rotation', NULL),
(428, 'Cybex', 'PP-DIP', 'PWR Play Dip Station', 'chest', 'cable', 'chest_dip,tricep_dip', NULL)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  name = EXCLUDED.name,
  muscle_group = EXCLUDED.muscle_group,
  equipment_type = EXCLUDED.equipment_type,
  exercise_type = EXCLUDED.exercise_type,
  image_url = EXCLUDED.image_url;
