-- Life Fitness equipment catalog
-- Generated 2026-03-23
-- 92 records

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
(580, 'Life Fitness', 'SS-CP', 'Insignia Series Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-CP.jpg'),
(581, 'Life Fitness', 'SS-CPX', 'Insignia Series Dual Axis Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-CPX.jpg'),
(582, 'Life Fitness', 'SS-SP', 'Insignia Series Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-SP.jpg'),
(583, 'Life Fitness', 'SS-FLY', 'Insignia Series Pectoral Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(584, 'Life Fitness', 'SS-LR', 'Insignia Series Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-LR.jpg'),
(585, 'Life Fitness', 'SS-PD', 'Insignia Series Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-PD.jpg'),
(586, 'Life Fitness', 'SS-PDX', 'Insignia Series Dual Axis Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(587, 'Life Fitness', 'SS-RW', 'Insignia Series Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-RW.jpg'),
(588, 'Life Fitness', 'SS-BC', 'Insignia Series Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-BC.jpg'),
(589, 'Life Fitness', 'SS-BCD', 'Insignia Series Biceps Curl Dependent', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-BCD.jpg'),
(590, 'Life Fitness', 'SS-TE', 'Insignia Series Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-TE.jpg'),
(591, 'Life Fitness', 'SS-TP', 'Insignia Series Triceps Press', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-TP.jpg'),
(592, 'Life Fitness', 'SS-ADC', 'Insignia Series Assisted Dip / Chin', 'full_body', 'selectorized', 'chest_dip,lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-ADC.jpg'),
(593, 'Life Fitness', 'SS-AB', 'Insignia Series Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-AB.jpg'),
(594, 'Life Fitness', 'SS-ABD', 'Insignia Series Abdominal Advanced', 'core', 'selectorized', 'crunch', NULL),
(595, 'Life Fitness', 'SS-TR', 'Insignia Series Torso Rotation', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-TR.jpg'),
(596, 'Life Fitness', 'SS-BE', 'Insignia Series Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-BE.jpg'),
(597, 'Life Fitness', 'SS-LP', 'Insignia Series Arc Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(598, 'Life Fitness', 'SS-LE', 'Insignia Series Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-LE.jpg'),
(599, 'Life Fitness', 'SS-LC', 'Insignia Series Leg Curl', 'legs', 'selectorized', 'leg_curl', NULL),
(600, 'Life Fitness', 'SS-SLC', 'Insignia Series Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(601, 'Life Fitness', 'SS-CE', 'Insignia Series Calf Extension', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-CE.jpg'),
(602, 'Life Fitness', 'SS-GL', 'Insignia Series Glute', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-GL.jpg'),
(603, 'Life Fitness', 'IS-GLD', 'Insignia Series Glute Bridge', 'glutes', 'selectorized', 'hip_thrust', NULL),
(604, 'Life Fitness', 'SS-HAD', 'Insignia Series Hip Adduction', 'legs', 'selectorized', 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/SS-HAD.jpg'),
(605, 'Life Fitness', 'IS-HAA', 'Insignia Series Hip Abduction / Adduction', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/IS-HAA.jpg'),
(606, 'Life Fitness', 'SS-SHB', 'Insignia Series Sit/Stand Hip Abductor', 'legs', 'selectorized', 'hip_abduction', NULL),
(607, 'Life Fitness', 'FZCP', 'Signature Series Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/FZCP.jpg'),
(608, 'Life Fitness', 'FZSP', 'Signature Series Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/FZSP.jpg'),
(609, 'Life Fitness', 'FZPEC', 'Signature Series Pectoral Fly', 'chest', 'selectorized', 'chest_fly', NULL),
(610, 'Life Fitness', 'FZRW', 'Signature Series Row / Rear Delt', 'back', 'selectorized', 'seated_row,rear_delt', NULL),
(611, 'Life Fitness', 'FZPD', 'Signature Series Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(612, 'Life Fitness', 'FZBC', 'Signature Series Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(613, 'Life Fitness', 'FZTP', 'Signature Series Triceps Press', 'arms', 'selectorized', 'tricep_extension', NULL),
(614, 'Life Fitness', 'FZLR', 'Signature Series Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', NULL),
(615, 'Life Fitness', 'FZAB', 'Signature Series Abdominal', 'core', 'selectorized', 'crunch', NULL),
(616, 'Life Fitness', 'FZTR', 'Signature Series Torso Rotation', 'core', 'selectorized', 'torso_rotation', NULL),
(617, 'Life Fitness', 'FZBE', 'Signature Series Back Extension', 'back', 'selectorized', 'back_extension', NULL),
(618, 'Life Fitness', 'FZGL', 'Signature Series Glute', 'glutes', 'selectorized', 'glute_kickback', NULL),
(619, 'Life Fitness', 'FZLE', 'Signature Series Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(620, 'Life Fitness', 'FZSLC', 'Signature Series Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(621, 'Life Fitness', 'FZLC', 'Signature Series Prone Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', NULL),
(622, 'Life Fitness', 'FZSLP', 'Signature Series Seated Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(623, 'Life Fitness', 'FZCE', 'Signature Series Calf Extension', 'legs', 'selectorized', 'calf', NULL),
(624, 'Life Fitness', 'FZHAD', 'Signature Series Hip Adduction', 'legs', 'selectorized', 'hip_adduction', NULL),
(625, 'Life Fitness', 'FZHAB', 'Signature Series Hip Abduction', 'legs', 'selectorized', 'hip_abduction', NULL),
(626, 'Life Fitness', 'SPLCP', 'Signature PL Chest Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(627, 'Life Fitness', 'SPLIP', 'Signature PL Incline Press', 'chest', 'plate-loaded', 'incline_press', NULL),
(628, 'Life Fitness', 'SPLSP', 'Signature PL Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(629, 'Life Fitness', 'SPLPD', 'Signature PL Front Pulldown', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(630, 'Life Fitness', 'SPLHR', 'Signature PL High Row', 'back', 'plate-loaded', 'high_row', NULL),
(631, 'Life Fitness', 'SPLR', 'Signature PL Row', 'back', 'plate-loaded', 'seated_row', NULL),
(632, 'Life Fitness', 'SPLBC', 'Signature PL Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', NULL),
(633, 'Life Fitness', 'SPLSD', 'Signature PL Seated Dip', 'arms', 'plate-loaded', 'tricep_dip', NULL),
(634, 'Life Fitness', 'SPLLLP', 'Signature PL Linear Leg Press', 'legs', 'plate-loaded', 'leg_press', NULL),
(635, 'Life Fitness', 'SPLLE', 'Signature PL Leg Extension', 'legs', 'plate-loaded', 'leg_extension', NULL),
(636, 'Life Fitness', 'SPLKLC', 'Signature PL Kneeling Leg Curl', 'legs', 'plate-loaded', 'leg_curl', NULL),
(637, 'Life Fitness', 'SPLSM', 'Signature Smith Machine', 'full_body', 'smith', 'smith_machine', NULL),
(638, 'Life Fitness', 'OP-CP', 'Axiom Series Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-CP.jpg'),
(639, 'Life Fitness', 'OP-SP', 'Axiom Series Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-SP.jpg'),
(640, 'Life Fitness', 'OP-PD', 'Axiom Series Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-PD.jpg'),
(641, 'Life Fitness', 'OP-RW', 'Axiom Series Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(642, 'Life Fitness', 'OP-BC', 'Axiom Series Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-BC.jpg'),
(643, 'Life Fitness', 'OP-TE', 'Axiom Series Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-TE.jpg'),
(644, 'Life Fitness', 'OP-AB', 'Axiom Series Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-AB.jpg'),
(645, 'Life Fitness', 'OP-LP', 'Axiom Series Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(646, 'Life Fitness', 'OP-LE', 'Axiom Series Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-LE.jpg'),
(647, 'Life Fitness', 'OP-LC', 'Axiom Series Leg Curl', 'legs', 'selectorized', 'leg_curl', NULL),
(648, 'Life Fitness', 'OP-MP', 'Axiom Series Multi-Press', 'chest', 'selectorized', 'chest_press,incline_press,shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-MP.jpg'),
(649, 'Life Fitness', 'OP-FLY', 'Axiom Series Pec Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-FLY.jpg'),
(650, 'Life Fitness', 'OP-LR', 'Axiom Series Pulldown / Row', 'back', 'selectorized', 'lat_pulldown,seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-LR.jpg'),
(651, 'Life Fitness', 'OP-BT', 'Axiom Series Biceps / Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-BT.jpg'),
(652, 'Life Fitness', 'OP-ABBA', 'Axiom Series Abdominal / Back Extension', 'core', 'selectorized', 'crunch,back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-ABBA.jpg'),
(653, 'Life Fitness', 'OP-LCE', 'Axiom Series Leg Curl / Extension', 'legs', 'selectorized', 'leg_curl,leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-LCE.jpg'),
(654, 'Life Fitness', 'OP-HAA', 'Axiom Series Hip Abductor / Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-HAA.jpg'),
(655, 'Life Fitness', 'OP-SLC', 'Axiom Series Seated Leg Curl / Extension', 'legs', 'selectorized', 'seated_leg_curl,leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-SLC.jpg'),
(656, 'Life Fitness', 'OP-DAP', 'Axiom Series Dual Adjustable Pulley', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-DAP.jpg'),
(657, 'Life Fitness', 'OP-SM', 'Axiom Series Smith Rack', 'full_body', 'smith', 'smith_machine', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-SM.jpg'),
(658, 'Life Fitness', 'CMDAP', 'Signature Dual Adjustable Pulley', 'full_body', 'cable', 'cable_multi', NULL),
(659, 'Life Fitness', 'CMACO', 'Signature Adjustable Cable Crossover', 'full_body', 'cable', 'cable_multi', NULL),
(660, 'Life Fitness', 'SOFB', 'Signature Olympic Flat Bench', 'chest', 'bench', 'chest_press', NULL),
(661, 'Life Fitness', 'SOIB', 'Signature Olympic Incline Bench', 'chest', 'bench', 'incline_press', NULL),
(662, 'Life Fitness', 'SODB', 'Signature Olympic Decline Bench', 'chest', 'bench', 'decline_press', NULL),
(663, 'Life Fitness', 'SOMB', 'Signature Olympic Military Bench', 'shoulders', 'bench', 'shoulder_press', NULL),
(664, 'Life Fitness', 'SOSR', 'Signature Olympic Squat Rack', 'legs', 'rack', 'squat', NULL),
(665, 'Life Fitness', 'SMAB', 'Signature Multi-Adjustable Bench', 'full_body', 'bench', 'chest_press,incline_press', NULL),
(666, 'Life Fitness', 'SADB', 'Signature Adjustable Decline / Ab Bench', 'core', 'bench', 'crunch', NULL),
(667, 'Life Fitness', 'SAC', 'Signature Arm Curl Bench', 'arms', 'bench', 'preacher_curl', NULL),
(668, 'Life Fitness', 'SBWBE', 'Signature 45-Degree Back Extension', 'back', 'bench', 'back_extension', NULL),
(669, 'Life Fitness', 'SCDLR', 'Signature Chin / Dip / Leg Raise', 'full_body', 'rack', 'chest_dip', NULL),
(670, 'Life Fitness', 'OP-MAB', 'Axiom Multi-Adjustable Bench', 'full_body', 'bench', 'chest_press,incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-MAB.jpg'),
(671, 'Life Fitness', 'OP-DLR', 'Axiom Dip / Leg Raise', 'full_body', 'rack', 'chest_dip,crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/lifefitness/OP-DLR.jpg');
