-- Etenon Fitness equipment catalog
-- 254 records, IDs 900-1153
-- Generated from etenonfitness.com sitemap + CDN

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
(900, 'Etenon', 'M5003', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(901, 'Etenon', 'M5004', 'Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(902, 'Etenon', 'PC0101', 'Chest Vertical Press', 'chest', 'selectorized', 'chest_press', NULL),
(903, 'Etenon', 'PC0102', 'Dual Pec Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(904, 'Etenon', 'PC0104', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(905, 'Etenon', 'PC0105', 'Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', NULL),
(906, 'Etenon', 'PC0106', 'Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(907, 'Etenon', 'PC0107', 'Lat Pulldown Bar', 'back', 'selectorized', 'lat_pulldown', NULL),
(908, 'Etenon', 'PC0108', 'Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(909, 'Etenon', 'PC0109', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(910, 'Etenon', 'PC0110', 'Triceps Extension', 'arms', 'selectorized', 'tricep_extension', NULL),
(911, 'Etenon', 'PC0111', 'Dual Dip / Chin Assist', 'chest', 'selectorized', 'chest_dip,pull_up', NULL),
(912, 'Etenon', 'PC0112', 'Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(913, 'Etenon', 'PC0113', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(914, 'Etenon', 'PC0114', 'Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(915, 'Etenon', 'PC0115', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', NULL),
(916, 'Etenon', 'PC0116', 'Abductor', 'legs', 'selectorized', 'hip_abduction', NULL),
(917, 'Etenon', 'PC0117', 'Aductor', 'legs', 'selectorized', 'hip_adduction', NULL),
(918, 'Etenon', 'PC0118', 'Standing Calf Raise', 'legs', 'selectorized', 'calf', NULL),
(919, 'Etenon', 'PC0120', 'Multi-Hip', 'legs', 'selectorized', 'glute_kickback', NULL),
(920, 'Etenon', 'PC0123', 'Low Row', 'back', 'selectorized', 'low_row', NULL),
(921, 'Etenon', 'PC0131', 'Dual Cuadriceps Seated Leg Curl', 'legs', 'selectorized', 'leg_extension,leg_curl', NULL),
(922, 'Etenon', 'PC0132', 'Dual Abductor / Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', NULL),
(923, 'Etenon', 'PC0133', 'High Pulley Y Baja', 'back', 'cable', 'cable_multi', NULL),
(924, 'Etenon', 'PC0134', 'Dual Biceps Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', NULL),
(925, 'Etenon', 'PC0135', 'Dual Chest Press Hombro', 'chest', 'selectorized', 'chest_press,shoulder_press', NULL),
(926, 'Etenon', 'PC0136', 'Dual Ab Crunch / Back Extension', 'core', 'selectorized', 'crunch,back_extension', NULL),
(927, 'Etenon', 'PC0195', 'Lateral Raise Laterales', 'shoulders', 'selectorized', 'lateral_raise', NULL),
(928, 'Etenon', 'PC0925', 'Functional Trainer', 'back', 'cable', 'cable_multi', NULL),
(929, 'Etenon', 'PC0970', 'Multifunction', 'full_body', 'cable', 'cable_multi', NULL),
(930, 'Etenon', 'PC1001B', 'High Pulley Baja', 'back', 'cable', 'cable_multi', NULL),
(931, 'Etenon', 'PC1001C', 'Puente De Poleas Dominadas', 'back', 'selectorized', 'pull_up', NULL),
(932, 'Etenon', 'PC2001', 'Vertical Press Convergente', 'chest', 'selectorized', 'chest_press', NULL),
(933, 'Etenon', 'PC2002', 'Seated Row Convergente', 'back', 'selectorized', 'seated_row', NULL),
(934, 'Etenon', 'PC2003', 'Shoulder Press Convergente', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(935, 'Etenon', 'PC2005', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(936, 'Etenon', 'PC2007', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(937, 'Etenon', 'PC2008', 'Triceps Extension', 'arms', 'selectorized', 'tricep_extension', NULL),
(938, 'Etenon', 'PC2009', 'Abdominal Crunch', 'core', 'selectorized', 'crunch', NULL),
(939, 'Etenon', 'PC2010', 'Lumbar', 'back', 'selectorized', 'back_extension', NULL),
(940, 'Etenon', 'PC2011', 'Seated Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(941, 'Etenon', 'PC2012', 'Dual Vuelo Hombro Pecho', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(942, 'Etenon', 'PC2014', 'Assisted Pull-Ups', 'back', 'selectorized', 'pull_up', NULL),
(943, 'Etenon', 'PC2016', 'Dual Abductor / Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', NULL),
(944, 'Etenon', 'PC2018', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', NULL),
(945, 'Etenon', 'PC2020', 'Glute Kickback', 'legs', 'selectorized', 'glute_kickback', NULL),
(946, 'Etenon', 'PC2021', 'Dual Pecho Hombros', 'chest', 'selectorized', 'chest_press,shoulder_press', NULL),
(947, 'Etenon', 'PC2022', 'Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', NULL),
(948, 'Etenon', 'PC2023', 'Neck Flexion', 'core', 'selectorized', 'crunch', NULL),
(949, 'Etenon', 'PC2024', 'Multi-Hip', 'legs', 'selectorized', 'glute_kickback', NULL),
(950, 'Etenon', 'PC2025', 'Dual Femoral Extensiones', 'legs', 'selectorized', 'leg_extension,leg_curl', NULL),
(951, 'Etenon', 'PC2027', 'Dual Biceps Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', NULL),
(952, 'Etenon', 'PC2029', 'Ab Crunch / Back Extension', 'core', 'selectorized', 'crunch,back_extension', NULL),
(953, 'Etenon', 'PC2030', 'Dual Calf / Squat', 'legs', 'selectorized', 'calf,squat', NULL),
(954, 'Etenon', 'PC2031', 'Pec Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(955, 'Etenon', 'PC2032', 'Dual High Pulley Baja', 'back', 'cable', 'cable_multi', NULL),
(956, 'Etenon', 'PC2033', 'Dual Polea Biceps Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', NULL),
(957, 'Etenon', 'PC2034', 'Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(958, 'Etenon', 'PC2038', 'Torso Rotation', 'core', 'selectorized', 'torso_rotation', NULL),
(959, 'Etenon', 'PC2066', 'Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(960, 'Etenon', 'PC2201', 'Chest Press', 'chest', 'selectorized', 'chest_press', NULL),
(961, 'Etenon', 'PC2202', 'Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(962, 'Etenon', 'PC2203', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(963, 'Etenon', 'PC2205', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(964, 'Etenon', 'PC2207', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(965, 'Etenon', 'PC2211', 'Dual Seated Leg Press Jaca', 'legs', 'selectorized', 'leg_press,squat', NULL),
(966, 'Etenon', 'PC2213', 'High Pulley', 'back', 'cable', 'cable_multi', NULL),
(967, 'Etenon', 'PC2214', 'Dual Dominadas Fondos Asistidos', 'back', 'selectorized', 'pull_up', NULL),
(968, 'Etenon', 'PC2216', 'Dual Abductor / Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', NULL),
(969, 'Etenon', 'PC2218', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', NULL),
(970, 'Etenon', 'PC2220', 'Glute Kickback', 'legs', 'selectorized', 'glute_kickback', NULL),
(971, 'Etenon', 'PC2221', 'Dual Press Pecho Hombro', 'chest', 'selectorized', 'chest_press,shoulder_press', NULL),
(972, 'Etenon', 'PC2224', 'Glute Drive / Hip Thrust', 'legs', 'selectorized', 'hip_thrust', NULL),
(973, 'Etenon', 'PC2225', 'Dual Cuadriceps Lying Leg Curl', 'legs', 'selectorized', 'leg_extension,leg_curl', NULL),
(974, 'Etenon', 'PC2226', 'Pullover', 'back', 'selectorized', 'pullover', NULL),
(975, 'Etenon', 'PC2231', 'Dual Pec Fly Deltoides', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(976, 'Etenon', 'PC2232', 'Adjustable Pulley', 'back', 'cable', 'cable_multi', NULL),
(977, 'Etenon', 'PC2251', 'Doble Adjustable Pulley', 'back', 'cable', 'cable_multi', NULL),
(978, 'Etenon', 'PC2252', 'Dual Functional Trainer', 'full_body', 'cable', 'cable_multi', NULL),
(979, 'Etenon', 'PC2280', 'Dual Functional Cable Trainer', 'full_body', 'cable', 'cable_multi', NULL),
(980, 'Etenon', 'PC2281', 'Dual Lat Pulldown Seated Row', 'back', 'selectorized', 'lat_pulldown', NULL),
(981, 'Etenon', 'PC5003', 'Converging Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(982, 'Etenon', 'PC5008', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(983, 'Etenon', 'PC5009', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', NULL),
(984, 'Etenon', 'PC6001', 'Vertical Press Convergente', 'chest', 'selectorized', 'chest_press', NULL),
(985, 'Etenon', 'PC6002', 'Pec Fly', 'chest', 'selectorized', 'chest_fly', NULL),
(986, 'Etenon', 'PC6003', 'Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(987, 'Etenon', 'PC6004', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(988, 'Etenon', 'PC6006', 'Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(989, 'Etenon', 'PC6007', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(990, 'Etenon', 'PC6008', 'Triceps Dip', 'arms', 'selectorized', 'tricep_dip', NULL),
(991, 'Etenon', 'PC6009', 'Seated Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(992, 'Etenon', 'PC6010', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(993, 'Etenon', 'PC6012', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', NULL),
(994, 'Etenon', 'PC6013', 'Dual Pec Fly Deltoides', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(995, 'Etenon', 'PC6016', 'Abdominal Crunch', 'core', 'selectorized', 'crunch', NULL),
(996, 'Etenon', 'PC6019', 'Dual Abductor / Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', NULL),
(997, 'Etenon', 'PC6022', 'Dual Biceps Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', NULL),
(998, 'Etenon', 'PC6023', 'Dual Cuadriceps Seated Leg Curl', 'legs', 'selectorized', 'leg_extension,leg_curl', NULL),
(999, 'Etenon', 'PC6051', 'Assisted Pull-Ups', 'back', 'selectorized', 'pull_up', NULL),
(1000, 'Etenon', 'PC6052', 'Cable Crossover', 'back', 'cable', 'cable_multi', NULL),
(1001, 'Etenon', 'PC6074', 'Leg Press 45', 'legs', 'selectorized', 'leg_press', NULL),
(1002, 'Etenon', 'PC6091', 'Dual High Pulley Remo', 'back', 'cable', 'cable_multi', NULL),
(1003, 'Etenon', 'PC7001', 'Chest Press', 'chest', 'selectorized', 'chest_press', NULL),
(1004, 'Etenon', 'PC7002', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(1005, 'Etenon', 'PC7003', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(1006, 'Etenon', 'PC7004', 'Triceps Dip', 'arms', 'selectorized', 'tricep_dip', NULL),
(1007, 'Etenon', 'PC7005', 'High Pulley', 'back', 'cable', 'cable_multi', NULL),
(1008, 'Etenon', 'PC7006', 'Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(1009, 'Etenon', 'PC7007', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(1010, 'Etenon', 'PC7008', 'Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(1011, 'Etenon', 'PC7009', 'Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(1012, 'Etenon', 'PC7010', 'Glute Kickback', 'legs', 'selectorized', 'glute_kickback', NULL),
(1013, 'Etenon', 'PL1008', 'Prensa', 'legs', 'plate-loaded', 'leg_press', NULL),
(1014, 'Etenon', 'PL1009', 'Gemelo', 'legs', 'plate-loaded', 'calf', NULL),
(1015, 'Etenon', 'PL1011', 'Leg Extension', 'legs', 'plate-loaded', 'leg_extension', NULL),
(1016, 'Etenon', 'PL1018', 'Leg Press Uni Bi Lateral', 'legs', 'plate-loaded', 'leg_press', NULL),
(1017, 'Etenon', 'PL1021', 'Front Deep Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1018, 'Etenon', 'PL1022', 'Belt Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1019, 'Etenon', 'PL1023', 'Glute Kickback', 'legs', 'plate-loaded', 'glute_kickback', NULL),
(1020, 'Etenon', 'PL1024', 'Glute Machine', 'back', 'plate-loaded', 'pull_up', NULL),
(1021, 'Etenon', 'PL1025', 'Hip Thrust', 'legs', 'plate-loaded', 'hip_thrust', NULL),
(1022, 'Etenon', 'PL1026', 'Hip Thrust', 'legs', 'plate-loaded', 'hip_thrust', NULL),
(1023, 'Etenon', 'PL1027', 'Deadlift', 'back', 'plate-loaded', 'deadlift', NULL),
(1024, 'Etenon', 'PL1028', 'Leg Press Horizontal Uni Bi Lateral', 'legs', 'plate-loaded', 'leg_press', NULL),
(1025, 'Etenon', 'PL1029', 'Hip Thrust', 'legs', 'plate-loaded', 'hip_thrust', NULL),
(1026, 'Etenon', 'PL1030', 'Dual Cuadriceps Lying Leg Curl', 'legs', 'plate-loaded', 'leg_extension,leg_curl', NULL),
(1027, 'Etenon', 'PL25', '002 Lying Leg Curl Unilateral', 'legs', 'plate-loaded', 'lying_leg_curl', NULL),
(1028, 'Etenon', 'PL25053', 'T-Bar Row Sin Apoyo Al Pecho', 'back', 'plate-loaded', 'seated_row', NULL),
(1029, 'Etenon', 'PL2506', 'Vertical Leg Press Elite', 'legs', 'plate-loaded', 'leg_press', NULL),
(1030, 'Etenon', 'PL25102', 'Pec Fly Inclinadas Pro', 'chest', 'plate-loaded', 'chest_fly', NULL),
(1031, 'Etenon', 'PL25103', 'Chest Press Horizontal Con Regulacion', 'chest', 'plate-loaded', 'chest_press', NULL),
(1032, 'Etenon', 'PL2515', 'Horizontal Leg Press Unilateral', 'legs', 'plate-loaded', 'leg_press', NULL),
(1033, 'Etenon', 'PL2520', 'Power Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1034, 'Etenon', 'PL2521', 'Power Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1035, 'Etenon', 'PL2522', 'Triceps Extension De Pie', 'arms', 'plate-loaded', 'tricep_extension', NULL),
(1036, 'Etenon', 'PL2526', 'Squat High Pull', 'legs', 'plate-loaded', 'squat', NULL),
(1037, 'Etenon', 'PL2527', 'Low Row Agarre Supino', 'back', 'plate-loaded', 'low_row', NULL),
(1038, 'Etenon', 'PL2528', 'Multi Low Row Y Deadlift Mp', 'back', 'plate-loaded', 'low_row', NULL),
(1039, 'Etenon', 'PL2531', 'Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', NULL),
(1040, 'Etenon', 'PL2532', 'Forearm Machine', 'arms', 'plate-loaded', 'bicep_curl', NULL),
(1041, 'Etenon', 'PL2536', 'Triceps Dip', 'arms', 'plate-loaded', 'tricep_dip', NULL),
(1042, 'Etenon', 'PL2537', 'Chest Fly', 'chest', 'plate-loaded', 'chest_fly', NULL),
(1043, 'Etenon', 'PL2538', 'Standing Lateral Raise', 'shoulders', 'plate-loaded', 'lateral_raise', NULL),
(1044, 'Etenon', 'PL2540', 'Chest Vertical Press Con Regulacion', 'chest', 'plate-loaded', 'chest_press', NULL),
(1045, 'Etenon', 'PL2541', 'Chest Press Horizontal', 'chest', 'plate-loaded', 'chest_press', NULL),
(1046, 'Etenon', 'PL2542', 'Chest Vertical Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(1047, 'Etenon', 'PL2543', 'Chest Incline Press', 'chest', 'plate-loaded', 'incline_press', NULL),
(1048, 'Etenon', 'PL2544', 'Chest Decline Press', 'chest', 'plate-loaded', 'decline_press', NULL),
(1049, 'Etenon', 'PL2545', 'Pec Fly Inclinadas', 'chest', 'plate-loaded', 'chest_fly', NULL),
(1050, 'Etenon', 'PL2546', 'Super Incline Press', 'chest', 'plate-loaded', 'incline_press', NULL),
(1051, 'Etenon', 'PL2547', 'Chest Vertical Press Abierto', 'chest', 'plate-loaded', 'chest_press', NULL),
(1052, 'Etenon', 'PL25507', 'Pendulum Squat Pro', 'legs', 'plate-loaded', 'squat', NULL),
(1053, 'Etenon', 'PL2551', 'Reverse Lat Pulldown', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(1054, 'Etenon', 'PL25515', 'Seated Calf Raise', 'legs', 'plate-loaded', 'calf', NULL),
(1055, 'Etenon', 'PL2552', 'Cross Lat Pulldown', 'back', 'cable', 'cable_multi', NULL),
(1056, 'Etenon', 'PL2554', 'High Pulley', 'back', 'cable', 'cable_multi', NULL),
(1057, 'Etenon', 'PL2555', 'Low Row Agarre Prono', 'back', 'plate-loaded', 'seated_row', NULL),
(1058, 'Etenon', 'PL2558', 'Pullover', 'back', 'plate-loaded', 'pullover', NULL),
(1059, 'Etenon', 'PL2559', 'Super Row', 'back', 'plate-loaded', 'seated_row', NULL),
(1060, 'Etenon', 'PL2560', 'Dual Reverse Lat Pulldown Chest Incline Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(1061, 'Etenon', 'PL2561', 'Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(1062, 'Etenon', 'PL2562', 'Behind Neck Press', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(1063, 'Etenon', 'PL2563', 'Shoulder Press Con Regulacion', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(1064, 'Etenon', 'PL2564', 'Chest Incline Press Con Regulacion', 'chest', 'plate-loaded', 'incline_press', NULL),
(1065, 'Etenon', 'PL2567', 'Vertical Leg Press', 'legs', 'plate-loaded', 'leg_press', NULL),
(1066, 'Etenon', 'PL2571', 'V-Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1067, 'Etenon', 'PL2572', 'Hack Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1068, 'Etenon', 'PL2580', 'Banco Sissy Squat', 'legs', 'bench', 'squat', NULL),
(1069, 'Etenon', 'PL2581', 'Adjustable Hyperextension Pro', 'back', 'bench', 'back_extension', NULL),
(1070, 'Etenon', 'PL2582', 'Belt Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1071, 'Etenon', 'PL2584', 'Lat Pulldown Con Barra', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(1072, 'Etenon', 'PL2590', 'Inclined Row Con Apoyo', 'back', 'plate-loaded', 'seated_row', NULL),
(1073, 'Etenon', 'PL2591', 'Shoulder Press De Pie Lat Pulldown', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(1074, 'Etenon', 'PL2592', 'Standing Row Sin Apoyo Al Pecho', 'back', 'plate-loaded', 'seated_row', NULL),
(1075, 'Etenon', 'PL2595', 'Glute Kickback Prono', 'legs', 'plate-loaded', 'glute_kickback', NULL),
(1076, 'Etenon', 'PL2596', 'Seated Glute / Abductor', 'legs', 'plate-loaded', 'hip_abduction,glute_kickback', NULL),
(1077, 'Etenon', 'PL2597', 'Inclined Row', 'back', 'plate-loaded', 'seated_row', NULL),
(1078, 'Etenon', 'PL3001', 'Chest Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(1079, 'Etenon', 'PL3002', 'Super Row', 'back', 'plate-loaded', 'seated_row', NULL),
(1080, 'Etenon', 'PL3003', 'Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(1081, 'Etenon', 'PL3006', 'Lat Pulldown', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(1082, 'Etenon', 'PL3008', 'Leg Press', 'legs', 'plate-loaded', 'leg_press', NULL),
(1083, 'Etenon', 'PL3010', 'Glute Kickback Prono', 'legs', 'plate-loaded', 'glute_kickback', NULL),
(1084, 'Etenon', 'PL3013', 'Dual Cuadriceps Lying Leg Curl', 'legs', 'plate-loaded', 'leg_extension,leg_curl', NULL),
(1085, 'Etenon', 'PL3015', 'Squat / Lunge', 'legs', 'plate-loaded', 'squat', NULL),
(1086, 'Etenon', 'PL3016', 'Abductor', 'legs', 'plate-loaded', 'hip_abduction', NULL),
(1087, 'Etenon', 'PL4001', 'Incline Press', 'chest', 'plate-loaded', 'incline_press', NULL),
(1088, 'Etenon', 'PL4002', 'Low Row', 'back', 'plate-loaded', 'low_row', NULL),
(1089, 'Etenon', 'PL4003', 'Lat Pulldown', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(1090, 'Etenon', 'PL4004', 'Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(1091, 'Etenon', 'PL4005', 'Incline Leg Press 45O Palanca', 'legs', 'plate-loaded', 'leg_press', NULL),
(1092, 'Etenon', 'PL4007', 'Vertical Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(1093, 'Etenon', 'PL4008', 'Decline Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(1094, 'Etenon', 'PL4009', 'Dorian Row', 'back', 'plate-loaded', 'seated_row', NULL),
(1095, 'Etenon', 'PL4012', 'Triceps Dip', 'arms', 'plate-loaded', 'tricep_dip', NULL),
(1096, 'Etenon', 'PL4013', 'Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', NULL),
(1097, 'Etenon', 'PL4019', 'Abductor De Pie', 'legs', 'plate-loaded', 'hip_abduction', NULL),
(1098, 'Etenon', 'PL4021', 'High Pulley Circular', 'back', 'cable', 'cable_multi', NULL),
(1099, 'Etenon', 'PL4023', 'Standing Hip Thrust', 'legs', 'plate-loaded', 'hip_thrust', NULL),
(1100, 'Etenon', 'PL4024', 'Belt Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1101, 'Etenon', 'PL4027', 'Calf / Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1102, 'Etenon', 'PL4028', 'Glute Lunge', 'legs', 'plate-loaded', 'glute_kickback', NULL),
(1103, 'Etenon', 'PL4029', 'Pullover', 'back', 'plate-loaded', 'pullover', NULL),
(1104, 'Etenon', 'PL8040', 'Deadlift', 'back', 'plate-loaded', 'deadlift', NULL),
(1105, 'Etenon', 'PL8041', 'Remo', 'back', 'plate-loaded', 'seated_row', NULL),
(1106, 'Etenon', 'PL8042', 'Chest Vertical Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(1107, 'Etenon', 'PL8043', 'Leg Press', 'legs', 'plate-loaded', 'leg_press', NULL),
(1108, 'Etenon', 'PL8044', 'Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', NULL),
(1109, 'Etenon', 'PL8048', 'Triceps Dip', 'arms', 'plate-loaded', 'tricep_dip', NULL),
(1110, 'Etenon', 'PL8049', 'Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(1111, 'Etenon', 'PL8052', 'Lat Pulldown Lateral', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(1112, 'Etenon', 'PL8053', 'Triceps Extension', 'arms', 'plate-loaded', 'tricep_extension', NULL),
(1113, 'Etenon', 'PL8055', 'Incline Press', 'chest', 'plate-loaded', 'incline_press', NULL),
(1114, 'Etenon', 'PL8056', 'Lying Leg Curl', 'legs', 'plate-loaded', 'lying_leg_curl', NULL),
(1115, 'Etenon', 'PTT0119', 'V-Squat Dual Elite', 'legs', 'plate-loaded', 'squat', NULL),
(1116, 'Etenon', 'PTT0120', 'Dual Incline Leg Press 45O Jaca', 'legs', 'plate-loaded', 'leg_press,squat', NULL),
(1117, 'Etenon', 'PTT0122', 'Incline Leg Press 45O Elite', 'legs', 'plate-loaded', 'leg_press', NULL),
(1118, 'Etenon', 'PTT0201F', 'Flat Bench', 'chest', 'bench', 'bench', NULL),
(1119, 'Etenon', 'PTT0204F', 'Adjustable Bench', 'chest', 'bench', 'bench', NULL),
(1120, 'Etenon', 'PTT0205F', 'Banco Utility Seat', 'chest', 'bench', 'bench', NULL),
(1121, 'Etenon', 'PTT0206F', 'Preacher Curl Bench', 'arms', 'bench', 'bicep_curl', NULL),
(1122, 'Etenon', 'PTT0208F', 'Banco Shoulder Press', 'shoulders', 'bench', 'shoulder_press', NULL),
(1123, 'Etenon', 'PTT0209F', 'Flat Press Bench', 'chest', 'bench', 'chest_press', NULL),
(1124, 'Etenon', 'PTT0210F', 'Incline Press', 'chest', 'bench', 'incline_press', NULL),
(1125, 'Etenon', 'PTT0211F', 'Decline Press Bench', 'chest', 'bench', 'decline_press', NULL),
(1126, 'Etenon', 'PTT0215F', 'Dip / Ab Station', 'chest', 'bench', 'chest_dip', NULL),
(1127, 'Etenon', 'PTT0218F', 'Ab Bench 90°', 'core', 'bench', 'crunch', NULL),
(1128, 'Etenon', 'PTT0219F', 'Dip / Chin Assist Y Abdominales', 'back', 'bench', 'pull_up', NULL),
(1129, 'Etenon', 'PTT0220F', 'Hyperextension 45°', 'back', 'bench', 'back_extension', NULL),
(1130, 'Etenon', 'PTT0224F', 'Dual Adjustable Hyperextension', 'back', 'bench', 'back_extension', NULL),
(1131, 'Etenon', 'PTT0227F', 'Stretch Bench', 'full_body', 'bench', 'bench', NULL),
(1132, 'Etenon', 'PTT0228F', 'Adjustable Bench Declinado', 'chest', 'bench', 'bench', NULL),
(1133, 'Etenon', 'PTT0229', 'Sissy Squat Bench', 'legs', 'bench', 'squat', NULL),
(1134, 'Etenon', 'PTT0231F', 'T-Bar Row', 'back', 'bench', 'seated_row', NULL),
(1135, 'Etenon', 'PTT0232F', 'Seated Calf Raise', 'legs', 'bench', 'calf', NULL),
(1136, 'Etenon', 'PTT0235', 'Banco Prone Row', 'back', 'bench', 'seated_row', NULL),
(1137, 'Etenon', 'PTT0241', 'T-Bar Row', 'back', 'bench', 'seated_row', NULL),
(1138, 'Etenon', 'PTT0242', 'Press Bench', 'chest', 'bench', 'chest_press', NULL),
(1139, 'Etenon', 'PTT0244', 'Adjustable Bench Mini', 'chest', 'bench', 'bench', NULL),
(1140, 'Etenon', 'PTT0278', 'Etenon Jaula De Sentadilla Ptt0278 Plataforma Ptt0296', 'legs', 'bench', 'squat', NULL),
(1141, 'Etenon', 'PTT0317', 'V-Squat Pro', 'legs', 'plate-loaded', 'squat', NULL),
(1142, 'Etenon', 'R5501', 'Leg Extension Unilateral', 'legs', 'plate-loaded', 'leg_extension', NULL),
(1143, 'Etenon', 'R5502', 'Standing Leg Curl Unilateral', 'legs', 'plate-loaded', 'lying_leg_curl', NULL),
(1144, 'Etenon', 'R5503', 'Lying Leg Curl Unilateral', 'legs', 'plate-loaded', 'lying_leg_curl', NULL),
(1145, 'Etenon', 'R5504', 'Incline Leg Press Super Xl Unilateral', 'legs', 'plate-loaded', 'leg_press', NULL),
(1146, 'Etenon', 'R5505', 'Leg Press Sentado', 'legs', 'plate-loaded', 'leg_press', NULL),
(1147, 'Etenon', 'R5506', 'Adductor', 'legs', 'plate-loaded', 'hip_adduction', NULL),
(1148, 'Etenon', 'R5507', 'Abductor', 'legs', 'plate-loaded', 'hip_abduction', NULL),
(1149, 'Etenon', 'R5508', 'Hip Thrust', 'legs', 'plate-loaded', 'hip_thrust', NULL),
(1150, 'Etenon', 'R5509', 'Belt Squat', 'legs', 'plate-loaded', 'squat', NULL),
(1151, 'Etenon', 'R5510', 'Dual Abductor / Adductor', 'legs', 'plate-loaded', 'hip_abduction,hip_adduction', NULL),
(1152, 'Etenon', 'R5511', 'Incline Leg Press Super Xl', 'legs', 'plate-loaded', 'leg_press', NULL),
(1153, 'Etenon', 'R5512', 'Pendulum Squat', 'legs', 'plate-loaded', 'squat', NULL)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  name = EXCLUDED.name,
  muscle_group = EXCLUDED.muscle_group,
  equipment_type = EXCLUDED.equipment_type,
  exercise_type = EXCLUDED.exercise_type,
  image_url = EXCLUDED.image_url;