-- Precor equipment catalog
-- Exported from Supabase DB on 2026-03-20
-- 68 records

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
-- Precor Discovery Selectorized (DSL)
(121, 'Precor', 'DSL0204', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0204.png'),
(122, 'Precor', 'DSL0208', 'Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0208.png'),
(123, 'Precor', 'DSL0215', 'Seated Dip', 'chest', 'selectorized', 'chest_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0215.png'),
(124, 'Precor', 'DSL0310', 'Seated Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0310.png'),
(125, 'Precor', 'DSL0313', 'Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0313.png'),
(126, 'Precor', 'DSL0314', 'Diverging Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0314.png'),
(127, 'Precor', 'DSL0315', 'Rotary Torso', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0315.png'),
(128, 'Precor', 'DSL0324', 'Diverging Low Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0324.jpg'),
(129, 'Precor', 'DSL0404', 'Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0404.png'),
(130, 'Precor', 'DSL0414', 'Converging Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0414.png'),
(131, 'Precor', 'DSL0500', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0500.jpg'),
(132, 'Precor', 'DSL0504', 'Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0504.png'),
(133, 'Precor', 'DSL0505', 'Pec Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0505.png'),
(134, 'Precor', 'DSL0515', 'Converging Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0515.png'),
(135, 'Precor', 'DSL0602', 'Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0602.png'),
(136, 'Precor', 'DSL0605', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0605.png'),
(137, 'Precor', 'DSL0606', 'Prone Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0606.png'),
(138, 'Precor', 'DSL0618', 'Glute Extension', 'legs', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0618.png'),
(139, 'Precor', 'DSL0619', 'Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0619.png'),
(140, 'Precor', 'DSL0621', 'Inner/Outer Thigh', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0621.png'),
(141, 'Precor', 'DSL0623', 'Seated Calf Extension', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0623.png'),
(142, 'Precor', 'DSL0712', 'Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0712.jpg'),
(143, 'Precor', 'DSL0714', 'Abdominal Crunch', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DSL0714.png'),
-- Precor Discovery Plate Loaded (DPL)
(144, 'Precor', 'DPL0305', 'Lat Pulldown', 'back', 'plate-loaded', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0305.png'),
(145, 'Precor', 'DPL0309', 'Seated Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0309.png'),
(146, 'Precor', 'DPL0311', 'Incline Lever Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0311.png'),
(147, 'Precor', 'DPL0520', 'Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0520.png'),
(148, 'Precor', 'DPL0540', 'Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0540.png'),
(149, 'Precor', 'DPL0541', 'Incline Press', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0541.png'),
(150, 'Precor', 'DPL0550', 'Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0550.png'),
(151, 'Precor', 'DPL0560', 'Leg Extension', 'legs', 'plate-loaded', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0560.png'),
(152, 'Precor', 'DPL0561', 'Leg Curl', 'legs', 'plate-loaded', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0561.png'),
(153, 'Precor', 'DPL0601', 'Angled Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0601.png'),
(154, 'Precor', 'DPL0603', 'Hack Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0603.png'),
(155, 'Precor', 'DPL0624', 'Squat Machine', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0624.png'),
-- Precor Resolute Selectorized (RSL)
(156, 'Precor', 'RSL0204', 'Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0204.png'),
(157, 'Precor', 'RSL0208', 'Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0208.png'),
(158, 'Precor', 'RSL0215', 'Dip', 'chest', 'selectorized', 'chest_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0215.png'),
(159, 'Precor', 'RSL0310', 'Diverging Seated Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0310.png'),
(160, 'Precor', 'RSL0313', 'Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0313.png'),
(161, 'Precor', 'RSL0314', 'Diverging Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0314.png'),
(162, 'Precor', 'RSL0315', 'Rotary Torso', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0315.png'),
(163, 'Precor', 'RSL0414', 'Converging Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0414.png'),
(164, 'Precor', 'RSL0504', 'Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0504.png'),
(165, 'Precor', 'RSL0505', 'Pec Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0505.png'),
(166, 'Precor', 'RSL0515', 'Converging Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0515.png'),
(167, 'Precor', 'RSL0602', 'Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0602.png'),
(168, 'Precor', 'RSL0605', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0605.png'),
(169, 'Precor', 'RSL0606', 'Prone Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0606.png'),
(170, 'Precor', 'RSL0619', 'Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0619.png'),
(171, 'Precor', 'RSL0714', 'Abdominal Crunch', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/RSL0714.png'),
-- Precor Discovery Benches & Racks (DBR)
(172, 'Precor', 'DBR0101', 'Flat Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0101.png'),
(173, 'Precor', 'DBR0113', 'Adjustable Decline Bench', 'chest', 'bench', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0113.png'),
(174, 'Precor', 'DBR0119', 'Multi-Adjustable Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0119.png'),
(175, 'Precor', 'DBR0202', 'Preacher Curl Bench', 'arms', 'bench', 'preacher_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0202.png'),
(176, 'Precor', 'DBR0312', 'Back Extension Bench', 'back', 'bench', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0312.png'),
(177, 'Precor', 'DBR0408', 'Olympic Flat Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0408.png'),
(178, 'Precor', 'DBR0409', 'Olympic Incline Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0409.png'),
(179, 'Precor', 'DBR0411', 'Olympic Decline Bench', 'chest', 'bench', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0411.png'),
(180, 'Precor', 'DBR0507', 'Olympic Shoulder Press Bench', 'shoulders', 'bench', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0507.png'),
(181, 'Precor', 'DBR0610', 'Power Rack', 'legs', 'rack', 'rack', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0610.png'),
(182, 'Precor', 'DBR0611', 'Half Rack', 'legs', 'rack', 'rack', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0611.png'),
(183, 'Precor', 'DBR0702', 'Vertical Knee-Up', 'core', 'rack', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0702.png'),
(184, 'Precor', 'DBR0712', 'Glute Bridge Bench', 'legs', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DBR0712.png'),
-- Precor FTS (Cable/Functional)
(185, 'Precor', 'FTS', 'Functional Training System Glide', 'chest', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/FTS.png'),
-- Precor Discovery Plate Loaded (DPL)
(304, 'Precor', 'DPL0802', 'Discovery Series Smith Machine', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/DPL0802.webp'),
-- Precor Vitality Series
(305, 'Precor', 'VBR6802', 'Vitality Series Smith Machine', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/VBR6802.png'),
-- Precor Icarian
(306, 'Precor', 'Icarian', 'Icarian Linear Counter Balanced Smith Machine', 'full_body', NULL, 'smith_machine,squat,shoulder_press,chest_press,incline_press,lunge,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/precor/Icarian.jpg')
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  name = EXCLUDED.name,
  muscle_group = EXCLUDED.muscle_group,
  equipment_type = EXCLUDED.equipment_type,
  exercise_type = EXCLUDED.exercise_type,
  image_url = EXCLUDED.image_url;
