-- Hammer Strength equipment catalog
-- Exported from Supabase DB on 2026-03-20
-- 82 records

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
-- Hammer Strength Plate-Loaded
(307, 'Hammer Strength', 'PL-ISO-BP', 'Iso-Lateral Bench Press', 'chest', NULL, 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ISO-BP.png'),
(308, 'Hammer Strength', 'PL-ILIP', 'Iso-Lateral Incline Press', 'chest', NULL, 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILIP.png'),
(309, 'Hammer Strength', 'PL-ILDP', 'Iso-Lateral Decline Press', 'chest', NULL, 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILDP.png'),
(310, 'Hammer Strength', 'PL-ILWC', 'Iso-Lateral Wide Chest', 'chest', NULL, 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILWC.png'),
(311, 'Hammer Strength', 'PL-ILRO', 'Iso-Lateral Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILRO.png'),
(312, 'Hammer Strength', 'PL-ILLR', 'Iso-Lateral Low Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILLR.png'),
(313, 'Hammer Strength', 'PL-ILDY', 'Iso-Lateral D.Y. Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILDY.png'),
(314, 'Hammer Strength', 'IL-PD', 'Iso-Lateral Front Lat Pulldown', 'back', NULL, 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/IL-PD.png'),
(315, 'Hammer Strength', 'PL-TBR', 'Plate-Loaded T-Bar Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-TBR.png'),
(316, 'Hammer Strength', 'PL-PO', 'Plate-Loaded Pullover', 'back', NULL, 'pullover', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-PO.png'),
(317, 'Hammer Strength', 'PL-ILSP', 'Iso-Lateral Shoulder Press', 'shoulders', NULL, 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILSP.png'),
(318, 'Hammer Strength', 'PL-ILLP', 'Iso-Lateral Leg Press', 'legs', NULL, 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILLP.png'),
(319, 'Hammer Strength', 'PL-ILLE', 'Iso-Lateral Leg Extension', 'legs', NULL, 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILLE.png'),
(320, 'Hammer Strength', 'PL-ILLC', 'Iso-Lateral Leg Curl', 'legs', NULL, 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILLC.png'),
(321, 'Hammer Strength', 'PL-SLC', 'Iso-Lateral Seated Leg Curl', 'legs', NULL, 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SLC.png'),
(322, 'Hammer Strength', 'PL-ILKLC', 'Iso-Lateral Kneeling Leg Curl', 'legs', NULL, 'kneeling_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILKLC.png'),
(323, 'Hammer Strength', 'PL-LHS', 'Plate-Loaded Linear Hack Squat', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-LHS.png'),
(324, 'Hammer Strength', 'PL-VS', 'Plate-Loaded V-Squat', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-VS.png'),
(325, 'Hammer Strength', 'PL-BS', 'Plate-Loaded Belt Squat', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-BS.png'),
(326, 'Hammer Strength', 'PL-GD', 'Plate-Loaded Glute Drive', 'legs', NULL, 'hip_thrust', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-GD.png'),
(327, 'Hammer Strength', 'PL-SCR', 'Plate-Loaded Seated Calf Raise', 'legs', NULL, 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SCR.png'),
(328, 'Hammer Strength', 'PL-SHC', 'Plate-Loaded Super Horizontal Calf', 'legs', NULL, 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SHC.png'),
(329, 'Hammer Strength', 'PL-VSM', 'Plate-Loaded Vertical Smith Machine', 'full_body', NULL, 'smith_machine', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-VSM.png'),
(330, 'Hammer Strength', 'PL-PXS', 'Plate-Loaded Pendulum Squat', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-PXS.png'),
-- Hammer Strength HD Elite
(331, 'Hammer Strength', 'HS-CP', 'Select Chest Press', 'chest', NULL, 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-CP.jpg'),
(332, 'Hammer Strength', 'HS-PEC', 'Select Pectoral Fly', 'chest', NULL, 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-PEC.jpg'),
(333, 'Hammer Strength', 'HS-FLY', 'Select Pectoral Fly / Rear Deltoid', 'chest', NULL, 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-FLY.jpg'),
(334, 'Hammer Strength', 'HS-PD', 'Select Lat Pulldown', 'back', NULL, 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-PD.jpg'),
(335, 'Hammer Strength', 'HS-RW', 'Select Seated Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-RW.jpg'),
(336, 'Hammer Strength', 'HS-BE', 'Select Back Extension', 'back', NULL, 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-BE.jpg'),
(337, 'Hammer Strength', 'HS-SP', 'Select Shoulder Press', 'shoulders', NULL, 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-SP.jpg'),
(338, 'Hammer Strength', 'HS-LR', 'Select Lateral Raise', 'shoulders', NULL, 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-LR.jpg'),
(339, 'Hammer Strength', 'HS-BC', 'Select Biceps Curl', 'arms', NULL, 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-BC.jpg'),
(340, 'Hammer Strength', 'HS-TE', 'Select Triceps Extension', 'arms', NULL, 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-TE.jpg'),
(341, 'Hammer Strength', 'HS-ABC', 'Select Abdominal Crunch', 'core', NULL, 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-ABC.jpg'),
(342, 'Hammer Strength', 'HS-SLP', 'Select Seated Leg Press', 'legs', NULL, 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-SLP.jpg'),
(343, 'Hammer Strength', 'HS-LE', 'Select Leg Extension', 'legs', NULL, 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-LE.jpg'),
(344, 'Hammer Strength', 'HS-LC', 'Select Leg Curl', 'legs', NULL, 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-LC.jpg'),
(345, 'Hammer Strength', 'HS-SLC', 'Select Seated Leg Curl', 'legs', NULL, 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-SLC.jpg'),
(346, 'Hammer Strength', 'HS-HAB', 'Select Hip Abduction', 'legs', NULL, 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-HAB.jpg'),
(347, 'Hammer Strength', 'HS-HAD', 'Select Hip Adduction', 'legs', NULL, 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-HAD.jpg'),
(348, 'Hammer Strength', 'HS-HG', 'Select Hip and Glute', 'legs', NULL, 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-HG.jpg'),
(349, 'Hammer Strength', 'HS-HC', 'Select Horizontal Calf', 'legs', NULL, 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-HC.jpg'),
(350, 'Hammer Strength', 'HS-SC', 'Select Standing Calf', 'legs', NULL, 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-SC.jpg'),
-- Hammer Strength MTS (Selectorized)
(351, 'Hammer Strength', 'MTSCP', 'MTS Iso-Lateral Chest Press', 'chest', NULL, 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSCP.jpg'),
(352, 'Hammer Strength', 'MTSIP', 'MTS Iso-Lateral Incline Press', 'chest', NULL, 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSIP.jpg'),
(353, 'Hammer Strength', 'MTSDP', 'MTS Iso-Lateral Decline Press', 'chest', NULL, 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSDP.jpg'),
(354, 'Hammer Strength', 'MTSRW', 'MTS Iso-Lateral Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSRW.jpg'),
(355, 'Hammer Strength', 'MTSHR', 'MTS Iso-Lateral High Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSHR.jpg'),
(356, 'Hammer Strength', 'MTSFPD', 'MTS Iso-Lateral Front Pulldown', 'back', NULL, 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSFPD.jpg'),
(357, 'Hammer Strength', 'MTSSP', 'MTS Iso-Lateral Shoulder Press', 'shoulders', NULL, 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSSP.png'),
(358, 'Hammer Strength', 'MTSBC', 'MTS Iso-Lateral Biceps Curl', 'arms', NULL, 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSBC.jpg'),
(359, 'Hammer Strength', 'MTSTE', 'MTS Iso-Lateral Triceps Extension', 'arms', NULL, 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSTE.png'),
(360, 'Hammer Strength', 'MTSAC', 'MTS Abdominal Crunch', 'core', NULL, 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSAC.jpg'),
(361, 'Hammer Strength', 'MTSLE', 'MTS Iso-Lateral Leg Extension', 'legs', NULL, 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSLE.jpg'),
(362, 'Hammer Strength', 'MTSKLC', 'MTS Iso-Lateral Kneeling Leg Curl', 'legs', NULL, 'kneeling_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSKLC.jpg'),
(363, 'Hammer Strength', 'MTSVS', 'MTS V-Squat', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/MTSVS.jpg'),
-- Hammer Strength Plate-Loaded
(364, 'Hammer Strength', 'PL-ILHBP', 'Iso-Lateral Horizontal Bench Press', 'chest', NULL, 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILHBP.png'),
(365, 'Hammer Strength', 'PL-ILSIP', 'Iso-Lateral Super Incline Press', 'chest', NULL, 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILSIP.png'),
(366, 'Hammer Strength', 'PL-SF', 'Plate-Loaded Super Fly', 'chest', NULL, 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SF.png'),
(367, 'Hammer Strength', 'PL-SD', 'Plate-Loaded Seated Dip', 'chest', NULL, 'chest_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SD.png'),
(368, 'Hammer Strength', 'PL-ILHR', 'Iso-Lateral High Row', 'back', NULL, 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILHR.png'),
(369, 'Hammer Strength', 'PL-ILWPD', 'Iso-Lateral Wide Pulldown', 'back', NULL, 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILWPD.png'),
(370, 'Hammer Strength', 'PL-LR', 'Plate-Loaded Lateral Raise', 'shoulders', NULL, 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-LR.png'),
(371, 'Hammer Strength', 'PL-SB', 'Plate-Loaded Seated Biceps Curl', 'arms', NULL, 'preacher_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SB.png'),
(372, 'Hammer Strength', 'PL-LLP', 'Plate-Loaded Linear Leg Press', 'legs', NULL, 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-LLP.png'),
(373, 'Hammer Strength', 'PL-LE', 'Plate-Loaded Leg Extension', 'legs', NULL, 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-LE.png'),
(374, 'Hammer Strength', 'PL-GHR', 'Glute Ham Reverse Hyper', 'back', NULL, 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-GHR.png'),
(375, 'Hammer Strength', 'PL-AC', 'Plate-Loaded Abdominal Oblique Crunch', 'core', NULL, 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-AC.png'),
-- Hammer Strength Smith Machine
(376, 'Hammer Strength', 'SM', 'Smith Machine', 'full_body', NULL, 'smith_machine', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/SM.png'),
-- Hammer Strength HD Elite
(377, 'Hammer Strength', 'HS-FPD', 'Select Fixed Pulldown', 'back', NULL, 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/HS-FPD.jpg'),
-- Hammer Strength Plate-Loaded
(378, 'Hammer Strength', 'PL-GR', 'Plate-Loaded Gripper', 'arms', NULL, 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-GR.png'),
(379, 'Hammer Strength', 'PL-SSS', 'Plate-Loaded Seated/Standing Shrug', 'back', NULL, 'deadlift', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SSS.png'),
(380, 'Hammer Strength', 'PL-4WN', 'Plate-Loaded 4-Way Neck', 'shoulders', NULL, NULL, 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-4WN.png'),
(381, 'Hammer Strength', 'PL-SSP', 'Plate-Loaded Super Squat Press', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-SSP.png'),
(382, 'Hammer Strength', 'PL-ANH', 'Plate-Loaded Assisted Nordic Ham', 'legs', NULL, 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ANH.png'),
(383, 'Hammer Strength', 'PL-TDF', 'Plate-Loaded Tibia Dorsi-Flexion', 'legs', NULL, 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-TDF.png'),
-- Hammer Strength Ground Base
(384, 'Hammer Strength', 'GB-J', 'Ground Base Jammer', 'chest', NULL, 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/GB-J.png'),
(385, 'Hammer Strength', 'GB-CT', 'Ground Base Combo Twist', 'core', NULL, 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/GB-CT.png'),
(386, 'Hammer Strength', 'GB-SHP', 'Ground Base Squat/High Pull', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/GB-SHP.png'),
(387, 'Hammer Strength', 'GB-MS', 'Ground Base Multi-Squat', 'legs', NULL, 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/GB-MS.png'),
-- Hammer Strength Plate-Loaded
(388, 'Hammer Strength', 'PL-ILCB', 'Iso-Lateral Chest/Back', 'chest', NULL, 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/hammer/PL-ILCB.png')
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  name = EXCLUDED.name,
  muscle_group = EXCLUDED.muscle_group,
  equipment_type = EXCLUDED.equipment_type,
  exercise_type = EXCLUDED.exercise_type,
  image_url = EXCLUDED.image_url;
