-- Gymleco equipment catalog (108 machines)
-- Generated from Supabase DB

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
  (1408, 'Gymleco', '010', 'Seated Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/010.jpg'),
  (1409, 'Gymleco', '011', 'Iso Lateral Pulldown', 'back', 'plate-loaded', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/011.webp'),
  (1410, 'Gymleco', '012', 'Iso Lateral Low Row', 'back', 'plate-loaded', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/012.jpg'),
  (1411, 'Gymleco', '013', 'Iso Lateral High Row', 'back', 'plate-loaded', 'high_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/013.jpg'),
  (1412, 'Gymleco', '017', 'D.Y. Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/017.png'),
  (1413, 'Gymleco', '020', 'Lateral Incline Bench Press', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/020.jpg'),
  (1414, 'Gymleco', '021', 'Seated Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/021.png'),
  (1415, 'Gymleco', '022', 'ISO Lateral Bench Press, Horizontal', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/022.jpg'),
  (1416, 'Gymleco', '023', 'Incline Pec Fly', 'chest', 'plate-loaded', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/023.jpg'),
  (1417, 'Gymleco', '027', 'Decline Chest Press', 'chest', 'plate-loaded', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/027.png'),
  (1418, 'Gymleco', '028', 'Standing Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/028.png'),
  (1419, 'Gymleco', '029', 'Incline Press / Chest Flyes', 'chest', 'plate-loaded', 'incline_press,chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/029.png'),
  (1420, 'Gymleco', '030', 'Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/030.jpg'),
  (1421, 'Gymleco', '031', 'Shoulder Rotation', 'shoulders', 'plate-loaded', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/031.png'),
  (1422, 'Gymleco', '032', 'Upright Row', 'shoulders', 'plate-loaded', 'lateral_raise,shrug', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/032.jpg'),
  (1423, 'Gymleco', '038', 'Viking Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/038.jpg'),
  (1424, 'Gymleco', '040', 'Leg Extension', 'legs', 'plate-loaded', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/040.png'),
  (1425, 'Gymleco', '041', 'Leg Curl, Seated', 'legs', 'plate-loaded', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/041.jpg'),
  (1426, 'Gymleco', '042', 'Standing Leg Curl', 'legs', 'plate-loaded', 'standing_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/042.jpg'),
  (1427, 'Gymleco', '043', 'Hip Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/043.jpg'),
  (1428, 'Gymleco', '044', 'V-Squat, Plate Loaded', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/044.png'),
  (1429, 'Gymleco', '045', 'Pendulum Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/045.jpg'),
  (1430, 'Gymleco', '046', 'Donkey Raise', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/046.jpg'),
  (1431, 'Gymleco', '047', 'Tibia Dorsi Flexion', 'legs', 'plate-loaded', 'tibial_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/047.jpg'),
  (1432, 'Gymleco', '050', 'Biceps Curl Machine', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/050.jpg'),
  (1433, 'Gymleco', '051', 'Iso Lateral Triceps', 'arms', 'plate-loaded', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/051.jpg'),
  (1434, 'Gymleco', '055', 'Dip Press', 'arms', 'plate-loaded', 'tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/055.jpg'),
  (1435, 'Gymleco', '060', 'Glute Kickback', 'glutes', 'plate-loaded', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/060.jpg'),
  (1436, 'Gymleco', '061', 'Reverse Hyper', 'back', 'plate-loaded', 'reverse_hyper', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/061.jpg'),
  (1437, 'Gymleco', '062', 'Standing Abductor, Plate Loaded', 'legs', 'plate-loaded', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/062.jpg'),
  (1438, 'Gymleco', '063', 'Reverse Hyper Pendulum', 'back', 'plate-loaded', 'reverse_hyper', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/063.jpg'),
  (1439, 'Gymleco', '066', 'Hip Thrust', 'glutes', 'plate-loaded', 'hip_thrust', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/066.jpg'),
  (1440, 'Gymleco', '070', 'Seated Abs Machine', 'core', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/070.jpg'),
  (1441, 'Gymleco', '072', 'Ab Roll Up', 'core', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/072.jpg'),
  (1442, 'Gymleco', '082', 'Belt Squat Machine', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/082.jpg'),
  (1443, 'Gymleco', '083', 'Deadlift / Squat Machine', 'legs', 'plate-loaded', 'squat,deadlift', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/083.jpg'),
  (1444, 'Gymleco', '115', 'T-Bar Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/115.jpg'),
  (1445, 'Gymleco', '116', 'Incline T-Bar Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/116.jpg'),
  (1446, 'Gymleco', '145', 'Seated Calf Press', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/145.jpg'),
  (1447, 'Gymleco', '167', 'Glute Bridge', 'glutes', 'plate-loaded', 'hip_thrust', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/167.png'),
  (1448, 'Gymleco', '210', 'Seated Row', 'back', 'cable', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/210.jpg'),
  (1449, 'Gymleco', '211', 'Lateral Pulldown', 'back', 'cable', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/211.jpg'),
  (1450, 'Gymleco', '211R', 'Lateral Pulldown, Adjustable', 'back', 'cable', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/211R.jpg'),
  (1451, 'Gymleco', '214', 'Lateral Pulldown/Seated Row', 'back', 'cable', 'lat_pulldown,seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/214.jpg'),
  (1452, 'Gymleco', '215', 'Four Station Multi Gym', 'back', 'cable', 'lat_pulldown,seated_row,chest_dip,tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/215.jpg'),
  (1453, 'Gymleco', '215K', 'Multi Gym / Four Station with Cable Cross', 'back', 'cable', 'lat_pulldown,seated_row,chest_fly,cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/215K.png'),
  (1454, 'Gymleco', '225', 'Cable Crossover Multi Gym', 'chest', 'cable', 'chest_fly,cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/225.png'),
  (1455, 'Gymleco', '225B', 'Half Cable Cross', 'chest', 'cable', 'chest_fly,cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/225B.png'),
  (1456, 'Gymleco', '226', 'Dual Adjustable Pulley', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/226.png'),
  (1457, 'Gymleco', '243', 'Leg Press 45°', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/243.png'),
  (1458, 'Gymleco', '244', 'Hacklift', 'legs', 'plate-loaded', 'hack_squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/244.png'),
  (1459, 'Gymleco', '245', 'Leg Press / Hacklift', 'legs', 'plate-loaded', 'leg_press,hack_squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/245.jpg'),
  (1460, 'Gymleco', '251', 'Triceps Pushdown', 'arms', 'cable', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/251.jpg'),
  (1461, 'Gymleco', '255', 'Biceps Curl / Triceps Extension', 'arms', 'cable', 'bicep_curl,tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/255.png'),
  (1462, 'Gymleco', '280', 'Smith Machine', 'full_body', 'smith', 'smith_machine,squat,shoulder_press,chest_press,incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/280.jpg'),
  (1463, 'Gymleco', '281', 'Smith Machine with Counterweight', 'full_body', 'smith', 'smith_machine,squat,shoulder_press,chest_press,incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/281.webp'),
  (1464, 'Gymleco', '285', 'Multi Smith Machine', 'full_body', 'smith', 'smith_machine,squat,shoulder_press,chest_press,incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/285.jpg'),
  (1465, 'Gymleco', '310', 'Seated Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/310.jpg'),
  (1466, 'Gymleco', '311', 'Iso Lateral Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/311.jpg'),
  (1467, 'Gymleco', '312', 'Iso Lateral Low Row', 'back', 'selectorized', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/312.webp'),
  (1468, 'Gymleco', '314', 'Chins / Dips', 'back', 'selectorized', 'lat_pulldown,chest_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/314.png'),
  (1469, 'Gymleco', '320', 'Incline Chest Press', 'chest', 'selectorized', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/320.webp'),
  (1470, 'Gymleco', '321', 'Seated Wide Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/321.png'),
  (1471, 'Gymleco', '323', 'Seated Pec Deck', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/323.jpg'),
  (1472, 'Gymleco', '324', 'Pullover', 'back', 'selectorized', 'pullover', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/324.jpg'),
  (1473, 'Gymleco', '326', 'Standing Pec Fly', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/326.png'),
  (1474, 'Gymleco', '330', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/330.jpg'),
  (1475, 'Gymleco', '331', 'Shoulder Rotation', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/331.jpg'),
  (1476, 'Gymleco', '333', 'Rear Deltoid Shoulder', 'shoulders', 'selectorized', 'rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/333.jpg'),
  (1477, 'Gymleco', '334', 'Standing Side Lateral', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/334.png'),
  (1478, 'Gymleco', '335', 'Rear Deltoid / Pec Deck', 'shoulders', 'selectorized', 'rear_delt,chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/335.jpg'),
  (1479, 'Gymleco', '336', 'Shoulder Front Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/336.png'),
  (1480, 'Gymleco', '340', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/340.png'),
  (1481, 'Gymleco', '340R', 'Leg Extension, Adjustable', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/340R.png'),
  (1482, 'Gymleco', '341', 'Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/341.jpg'),
  (1483, 'Gymleco', '342', 'Lying Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/342.jpg'),
  (1484, 'Gymleco', '342R', 'Lying Leg Curl, Adjustable', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/342R.jpg'),
  (1485, 'Gymleco', '343', 'Seated Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/343.png'),
  (1486, 'Gymleco', '344', 'Horizontal Lying Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/344.png'),
  (1487, 'Gymleco', '345', 'Seated Calf Press', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/345.jpg'),
  (1488, 'Gymleco', '347', 'Standing Calf Press', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/347.png'),
  (1489, 'Gymleco', '348', 'Seated Calf Press 45°', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/348.jpg'),
  (1490, 'Gymleco', '349', 'Leg Extension / Leg Curl', 'legs', 'selectorized', 'leg_extension,seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/349.png'),
  (1491, 'Gymleco', '350', 'Biceps Curl Machine', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/350.jpg'),
  (1492, 'Gymleco', '351', 'Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/351.jpg'),
  (1493, 'Gymleco', '354', 'Dips Press / Shoulder Pull', 'arms', 'selectorized', 'tricep_dip,shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/354.jpg'),
  (1494, 'Gymleco', '355', 'Biceps / Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/355.jpg'),
  (1495, 'Gymleco', '360', 'Gluteus, One Leg Kick', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/360.jpg'),
  (1496, 'Gymleco', '362', 'Standing Abductor', 'legs', 'selectorized', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/362.jpg'),
  (1497, 'Gymleco', '364', 'Adductor / Abductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/364.jpg'),
  (1498, 'Gymleco', '365A', 'Lumbar / Abdominal', 'back', 'selectorized', 'crunch,back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/365A.jpg'),
  (1499, 'Gymleco', '365B', 'Lumbar / Abdominal with Armrest', 'back', 'selectorized', 'crunch,back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/365B.jpg'),
  (1500, 'Gymleco', '369', 'Multihip', 'legs', 'selectorized', 'hip_abduction,glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/369.webp'),
  (1501, 'Gymleco', '370', 'Seated Abs Machine', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/370.jpg'),
  (1502, 'Gymleco', '375', 'Torso Rotation', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/375.jpg'),
  (1503, 'Gymleco', '376', 'Knee Standing Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/376.jpg'),
  (1504, 'Gymleco', '725', 'Cable Cross, Adjustable 2×75 kg', 'chest', 'cable', 'chest_fly,cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/725.jpg'),
  (1505, 'Gymleco', '726', 'Dual Adjustable Pulley 2×75 kg', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/726.jpg'),
  (1506, 'Gymleco', '911', 'Pulldown / Shoulder Press', 'back', 'selectorized', 'lat_pulldown,shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/911.png'),
  (1507, 'Gymleco', '921', 'Chest Press / Back', 'chest', 'selectorized', 'chest_press,seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/921.jpg'),
  (1508, 'Gymleco', '935', 'Pec Deck / Rear Deltoid Shoulder', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/935.jpg'),
  (1509, 'Gymleco', '944', 'Squats / Hacklift', 'legs', 'selectorized', 'squat,hack_squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/944.jpg'),
  (1510, 'Gymleco', '949', 'Leg Extension / Leg Curl', 'legs', 'selectorized', 'leg_extension,leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/949.jpg'),
  (1511, 'Gymleco', '954', 'Shoulder Lift / Dips', 'shoulders', 'selectorized', 'shoulder_press,tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/954.jpg'),
  (1512, 'Gymleco', '955', 'Biceps / Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/955.jpg'),
  (1513, 'Gymleco', '964', 'Abductor / Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/964.png'),
  (1514, 'Gymleco', '965', 'Abs / Lower Back', 'core', 'selectorized', 'crunch,back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/965.png'),
  (1515, 'Gymleco', '975', 'Waist Rotator', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/gymleco/975.png')
ON CONFLICT (id) DO NOTHING;
