INSERT INTO equipment_catalog (brand, model, name, muscle_group, equipment_type) VALUES
-- Precor Discovery Selectorized (DSL)
('Precor', 'DSL0204', 'Biceps Curl', 'arms', 'selectorized'),
('Precor', 'DSL0208', 'Triceps Extension', 'arms', 'selectorized'),
('Precor', 'DSL0215', 'Seated Dip', 'chest', 'selectorized'),
('Precor', 'DSL0310', 'Seated Row', 'back', 'selectorized'),
('Precor', 'DSL0313', 'Back Extension', 'back', 'selectorized'),
('Precor', 'DSL0314', 'Diverging Lat Pulldown', 'back', 'selectorized'),
('Precor', 'DSL0315', 'Rotary Torso', 'core', 'selectorized'),
('Precor', 'DSL0324', 'Diverging Low Row', 'back', 'selectorized'),
('Precor', 'DSL0404', 'Chest Press', 'chest', 'selectorized'),
('Precor', 'DSL0414', 'Converging Chest Press', 'chest', 'selectorized'),
('Precor', 'DSL0500', 'Shoulder Press', 'shoulders', 'selectorized'),
('Precor', 'DSL0504', 'Lateral Raise', 'shoulders', 'selectorized'),
('Precor', 'DSL0505', 'Pec Fly / Rear Delt', 'chest', 'selectorized'),
('Precor', 'DSL0515', 'Converging Shoulder Press', 'shoulders', 'selectorized'),
('Precor', 'DSL0602', 'Leg Press', 'legs', 'selectorized'),
('Precor', 'DSL0605', 'Leg Extension', 'legs', 'selectorized'),
('Precor', 'DSL0606', 'Prone Leg Curl', 'legs', 'selectorized'),
('Precor', 'DSL0618', 'Glute Extension', 'legs', 'selectorized'),
('Precor', 'DSL0619', 'Seated Leg Curl', 'legs', 'selectorized'),
('Precor', 'DSL0621', 'Inner/Outer Thigh', 'legs', 'selectorized'),
('Precor', 'DSL0623', 'Seated Calf Extension', 'legs', 'selectorized'),
('Precor', 'DSL0712', 'Abdominal', 'core', 'selectorized'),
('Precor', 'DSL0714', 'Abdominal Crunch', 'core', 'selectorized'),
-- Precor Discovery Plate Loaded (DPL)
('Precor', 'DPL0305', 'Lat Pulldown', 'back', 'plate-loaded'),
('Precor', 'DPL0309', 'Seated Row', 'back', 'plate-loaded'),
('Precor', 'DPL0311', 'Incline Lever Row', 'back', 'plate-loaded'),
('Precor', 'DPL0520', 'Biceps Curl', 'arms', 'plate-loaded'),
('Precor', 'DPL0540', 'Chest Press', 'chest', 'plate-loaded'),
('Precor', 'DPL0541', 'Incline Press', 'chest', 'plate-loaded'),
('Precor', 'DPL0550', 'Shoulder Press', 'shoulders', 'plate-loaded'),
('Precor', 'DPL0560', 'Leg Extension', 'legs', 'plate-loaded'),
('Precor', 'DPL0561', 'Leg Curl', 'legs', 'plate-loaded'),
('Precor', 'DPL0601', 'Angled Leg Press', 'legs', 'plate-loaded'),
('Precor', 'DPL0603', 'Hack Squat', 'legs', 'plate-loaded'),
('Precor', 'DPL0624', 'Squat Machine', 'legs', 'plate-loaded'),
-- Precor Resolute Selectorized (RSL)
('Precor', 'RSL0204', 'Biceps Curl', 'arms', 'selectorized'),
('Precor', 'RSL0208', 'Triceps Extension', 'arms', 'selectorized'),
('Precor', 'RSL0215', 'Dip', 'chest', 'selectorized'),
('Precor', 'RSL0310', 'Diverging Seated Row', 'back', 'selectorized'),
('Precor', 'RSL0313', 'Back Extension', 'back', 'selectorized'),
('Precor', 'RSL0314', 'Diverging Lat Pulldown', 'back', 'selectorized'),
('Precor', 'RSL0315', 'Rotary Torso', 'core', 'selectorized'),
('Precor', 'RSL0414', 'Converging Chest Press', 'chest', 'selectorized'),
('Precor', 'RSL0504', 'Lateral Raise', 'shoulders', 'selectorized'),
('Precor', 'RSL0505', 'Pec Fly / Rear Delt', 'chest', 'selectorized'),
('Precor', 'RSL0515', 'Converging Shoulder Press', 'shoulders', 'selectorized'),
('Precor', 'RSL0602', 'Leg Press', 'legs', 'selectorized'),
('Precor', 'RSL0605', 'Leg Extension', 'legs', 'selectorized'),
('Precor', 'RSL0606', 'Prone Leg Curl', 'legs', 'selectorized'),
('Precor', 'RSL0619', 'Seated Leg Curl', 'legs', 'selectorized'),
('Precor', 'RSL0714', 'Abdominal Crunch', 'core', 'selectorized'),
-- Precor Discovery Benches & Racks (DBR)
('Precor', 'DBR0101', 'Flat Bench', 'chest', 'bench'),
('Precor', 'DBR0113', 'Adjustable Decline Bench', 'chest', 'bench'),
('Precor', 'DBR0119', 'Multi-Adjustable Bench', 'chest', 'bench'),
('Precor', 'DBR0202', 'Preacher Curl Bench', 'arms', 'bench'),
('Precor', 'DBR0312', 'Back Extension Bench', 'back', 'bench'),
('Precor', 'DBR0408', 'Olympic Flat Bench', 'chest', 'bench'),
('Precor', 'DBR0409', 'Olympic Incline Bench', 'chest', 'bench'),
('Precor', 'DBR0411', 'Olympic Decline Bench', 'chest', 'bench'),
('Precor', 'DBR0507', 'Olympic Shoulder Press Bench', 'shoulders', 'bench'),
('Precor', 'DBR0610', 'Power Rack', 'legs', 'rack'),
('Precor', 'DBR0611', 'Half Rack', 'legs', 'rack'),
('Precor', 'DBR0702', 'Vertical Knee-Up', 'core', 'rack'),
('Precor', 'DBR0712', 'Glute Bridge Bench', 'legs', 'bench'),
-- Precor FTS
('Precor', 'FTS', 'Functional Training System Glide', 'chest', 'cable')
ON CONFLICT DO NOTHING;
