INSERT INTO equipment_catalog (brand, model, name, muscle_group, equipment_type) VALUES
-- gym80 SYGNUM (Selectorized)
('gym80', '3001', 'Leg Extension', 'legs', 'selectorized'),
('gym80', '3002', 'Seated Leg Curl', 'legs', 'selectorized'),
('gym80', '3005', 'Radial Gluteus', 'legs', 'selectorized'),
('gym80', '3006', 'Lying Leg Curl', 'legs', 'selectorized'),
('gym80', '3007', 'Back Extension', 'back', 'selectorized'),
('gym80', '3008', 'Abdominal', 'core', 'selectorized'),
('gym80', '3010', 'Biceps Curl', 'arms', 'selectorized'),
('gym80', '3011', 'Triceps Horizontal', 'arms', 'selectorized'),
('gym80', '3012', 'Pull Over Machine', 'chest', 'selectorized'),
('gym80', '3013', 'Leg Curl', 'legs', 'selectorized'),
('gym80', '3014', 'Chest Crossover Machine', 'chest', 'selectorized'),
('gym80', '3016', 'Seated Chest Press', 'chest', 'selectorized'),
('gym80', '3017', 'Incline Chest Press', 'chest', 'selectorized'),
('gym80', '3018', 'Standing Calf', 'legs', 'selectorized'),
('gym80', '3020', 'Lat Pulldown Machine', 'back', 'selectorized'),
('gym80', '3021', 'Butterfly with Pads', 'chest', 'selectorized'),
('gym80', '3022', 'Butterfly', 'chest', 'selectorized'),
('gym80', '3024', 'Twister', 'core', 'selectorized'),
('gym80', '3025', 'Butterfly Reverse', 'shoulders', 'selectorized'),
('gym80', '3027', 'Back Machine', 'back', 'selectorized'),
('gym80', '3028', 'Abduction Machine', 'legs', 'selectorized'),
('gym80', '3029', 'Adductor Machine', 'legs', 'selectorized'),
('gym80', '3030', 'Seated Leg Press', 'legs', 'selectorized'),
('gym80', '3031', 'Lying Leg Press', 'legs', 'selectorized'),
('gym80', '3032', 'Shoulder Press', 'shoulders', 'selectorized'),
('gym80', '3034', 'Lying Abdominal Machine', 'core', 'selectorized'),
('gym80', '3036', 'Dip Machine', 'chest', 'selectorized'),
('gym80', '3037', 'Special Abdominal Machine', 'core', 'selectorized'),
('gym80', '3038', 'Lower Back Machine', 'back', 'selectorized'),
('gym80', '3039', 'Seated Row (no chest support)', 'back', 'selectorized'),
('gym80', '3040', 'Seated Row Machine', 'back', 'selectorized'),
('gym80', '3047', 'Iso Lat', 'back', 'selectorized'),
-- gym80 SYGNUM DUAL
('gym80', '3042', 'Dual Incline Chest Press', 'chest', 'selectorized'),
('gym80', '3043', 'Dual Shoulder Press', 'shoulders', 'selectorized'),
('gym80', '3044', 'Dual Lat Pulldown', 'back', 'selectorized'),
('gym80', '3045', 'Dual Seated Row', 'back', 'selectorized'),
('gym80', '3046', 'Dual Leg Press', 'legs', 'selectorized'),
-- gym80 CABLE ART
('gym80', '5101', 'Cable Art No.1 - Shoulder & Back', 'shoulders', 'cable'),
('gym80', '5102', 'Cable Art No.2 - Latissimus & Trapezius', 'back', 'cable'),
('gym80', '5103', 'Cable Art No.3 - Chest & Shoulder', 'chest', 'cable'),
('gym80', '5104', 'Cable Art No.4 - Biceps & Triceps', 'arms', 'cable'),
('gym80', '5105', 'Cable Art No.5 - Upper Body', 'chest', 'cable'),
('gym80', '5106', 'Cable Art No.6 - Legs', 'legs', 'cable'),
-- gym80 INNOVATION
('gym80', '5001', 'Innovation Leg Press', 'legs', 'selectorized'),
('gym80', '5002', 'Innovation Glutes Machine', 'legs', 'selectorized'),
('gym80', '5003', 'Innovation Rowing Machine', 'back', 'selectorized'),
('gym80', '5004', 'Innovation Curler', 'arms', 'selectorized'),
('gym80', '5006', 'Innovation Multi Extension Machine', 'back', 'selectorized'),
-- gym80 PURE KRAFT (Plate-Loaded)
('gym80', '4018', 'T-Bar Row', 'back', 'plate-loaded'),
('gym80', '4023', '45-Degree Linear Leg Press', 'legs', 'plate-loaded'),
('gym80', '4026', 'Seated Calf Raise', 'legs', 'plate-loaded'),
('gym80', '4038', 'Squat Machine', 'legs', 'plate-loaded'),
('gym80', '4159N', 'Hack Squat', 'legs', 'plate-loaded'),
('gym80', '4307', 'Lying Abdominal', 'core', 'plate-loaded'),
('gym80', '4311', 'Lat Pulldown Dual', 'back', 'plate-loaded'),
('gym80', '4314', 'Seated Leg Press Dual', 'legs', 'plate-loaded'),
('gym80', '4317', 'Ab Swing', 'core', 'plate-loaded'),
('gym80', '4318', 'Bent Over Row', 'back', 'plate-loaded'),
('gym80', '4319', 'Low Row Dual', 'back', 'plate-loaded'),
('gym80', '4320', 'Shoulder Press Dual', 'shoulders', 'plate-loaded'),
('gym80', '4321', 'Gluteus Kick Machine', 'legs', 'plate-loaded'),
('gym80', '4322', 'Seated Row Dual', 'back', 'plate-loaded'),
('gym80', '4324', '45-Degree Pivot Leg Press', 'legs', 'plate-loaded'),
('gym80', '4325', 'Shoulder Lateral Raise Dual', 'shoulders', 'plate-loaded'),
('gym80', '4326', 'Chest Crossover Dual', 'chest', 'plate-loaded'),
('gym80', '4327', 'Power Row Dual', 'back', 'plate-loaded'),
('gym80', '4328', 'Seated Chest Press Dual', 'chest', 'plate-loaded'),
('gym80', '4329N', 'Incline Chest Press Dual', 'chest', 'plate-loaded'),
('gym80', '4331', 'Bench Press Dual', 'chest', 'plate-loaded'),
('gym80', '4332', 'Deadlift Rotating Grips Dual', 'back', 'plate-loaded'),
('gym80', '4333', 'Deadlift Double Handle Grips Dual', 'back', 'plate-loaded'),
('gym80', '4335', 'Triceps Dip Dual', 'arms', 'plate-loaded'),
('gym80', '4336N', 'Leg Extension', 'legs', 'plate-loaded'),
('gym80', '4337N', 'Lying Leg Curl', 'legs', 'plate-loaded'),
('gym80', '4338N', 'Biceps Machine', 'arms', 'plate-loaded'),
('gym80', '4339N', 'Triceps Extension', 'arms', 'plate-loaded'),
('gym80', '4340', 'High Row Dual', 'back', 'plate-loaded'),
('gym80', '4341', 'Chest Butterfly Dual', 'chest', 'plate-loaded'),
('gym80', '4342N', 'Rotating Abdominal Crunch', 'core', 'plate-loaded'),
('gym80', '4343', 'Abdominal Crunch', 'core', 'plate-loaded'),
('gym80', '4344', 'Butterfly Reverse Dual', 'shoulders', 'plate-loaded'),
('gym80', '4345', '55-Degree Standing Calf Raise', 'legs', 'plate-loaded'),
('gym80', '4346', 'Decline Chest Press Dual', 'chest', 'plate-loaded'),
('gym80', '4348', 'Tibia Dorsi Flexion', 'legs', 'plate-loaded'),
('gym80', '4350', 'Pullover', 'chest', 'plate-loaded'),
('gym80', '4350N', 'Pullover', 'chest', 'plate-loaded'),
('gym80', '4352', 'Booty Booster', 'legs', 'plate-loaded'),
('gym80', '4353N', 'Pendulum Squat', 'legs', 'plate-loaded'),
('gym80', '4354', 'Vertical Leg Press', 'legs', 'plate-loaded'),
('gym80', '4355', 'Biceps Curl Dual', 'arms', 'plate-loaded'),
('gym80', '4360', 'Belt Squat', 'legs', 'plate-loaded'),
('gym80', '4366', 'Biceps Overhead', 'arms', 'plate-loaded'),
('gym80', '4371', 'Neck Press', 'shoulders', 'plate-loaded'),
('gym80', '4372', 'Standing Multi-Joint', 'legs', 'plate-loaded'),
('gym80', '4373', 'Standing Leg Curl', 'legs', 'plate-loaded'),
('gym80', '4374', 'Standing Abduction', 'legs', 'plate-loaded'),
('gym80', '4375', 'Inverse Leg Curl', 'legs', 'plate-loaded'),
('gym80', '4376', 'Lying Inner Chest Dual', 'chest', 'plate-loaded'),
('gym80', '4379', 'Overhead Triceps', 'arms', 'plate-loaded'),
('gym80', '4380', 'Donkey Calf', 'legs', 'plate-loaded'),
('gym80', '4383', '55-Degree Rowing Machine', 'back', 'plate-loaded'),
('gym80', '4384', 'Abduction 3D', 'legs', 'plate-loaded'),
('gym80', '4385', 'Standing Shoulder Lateral Raise', 'shoulders', 'plate-loaded'),
('gym80', '4386', 'Booty Booster Special', 'legs', 'plate-loaded'),
('gym80', '4388', 'Viking Press', 'shoulders', 'plate-loaded'),
-- gym80 PURE KRAFT STRONG
('gym80', '4361', 'Strong Leg Press Dual', 'legs', 'plate-loaded'),
('gym80', '4362', 'Strong Decline Chest Press Dual', 'chest', 'plate-loaded'),
('gym80', '4363', 'Strong Shoulder Press Dual', 'shoulders', 'plate-loaded'),
('gym80', '4364', 'Strong Bench Press Dual', 'chest', 'plate-loaded'),
('gym80', '4365', 'Strong Incline Chest Press Dual', 'chest', 'plate-loaded'),
-- gym80 80CLASSICS
('gym80', '80CL0001', 'Lying Leg Curl', 'legs', 'selectorized'),
('gym80', '80CL0002', 'Seated Leg Curl', 'legs', 'selectorized'),
('gym80', '80CL0003', 'Radial Gluteus', 'legs', 'selectorized'),
('gym80', '80CL0004', 'Lower Back', 'back', 'selectorized'),
('gym80', '80CL0006', 'Abdominal', 'core', 'selectorized'),
('gym80', '80CL0007', 'Special Abdominal', 'core', 'selectorized'),
('gym80', '80CL0008', 'Total Ab', 'core', 'selectorized'),
('gym80', '80CL0009', 'Biceps Curl', 'arms', 'selectorized'),
('gym80', '80CL0010', 'Horizontal Triceps', 'arms', 'selectorized'),
('gym80', '80CL0011', 'Crossover', 'chest', 'selectorized'),
('gym80', '80CL0012', 'Deltoid Raise', 'shoulders', 'selectorized'),
('gym80', '80CL0013', 'Seated Chest Press', 'chest', 'selectorized'),
('gym80', '80CL0015', 'Standing Calf', 'legs', 'selectorized'),
('gym80', '80CL0016', 'Seated Row with Chest Pad', 'back', 'selectorized'),
('gym80', '80CL0017', 'Butterfly with Handgrips', 'chest', 'selectorized'),
('gym80', '80CL0018', 'Butterfly Reverse', 'shoulders', 'selectorized'),
('gym80', '80CL0019', 'Abduction Machine', 'legs', 'selectorized'),
('gym80', '80CL0020', 'Adduction Machine', 'legs', 'selectorized'),
('gym80', '80CL0021', 'Seated Leg Press', 'legs', 'selectorized'),
('gym80', '80CL0022', 'Shoulder Press', 'shoulders', 'selectorized'),
('gym80', '80CL0024', 'Lat Pulley', 'back', 'selectorized'),
('gym80', '80CL0026', 'Standing Scott Curl', 'arms', 'selectorized'),
('gym80', '80CL0029', 'Total Hip', 'legs', 'selectorized'),
-- gym80 FTM
('gym80', '4401', 'FTM Deadlift Machine', 'back', 'selectorized'),
('gym80', '4403', 'FTM Push & Pull Machine', 'chest', 'selectorized')
ON CONFLICT DO NOTHING;
