INSERT INTO equipment_catalog (brand, model, name, muscle_group, equipment_type) VALUES
-- Cybex Eagle NX (Selectorized)
('Cybex', '20000', 'Eagle NX Chest Press', 'chest', 'selectorized'),
('Cybex', '20010', 'Eagle NX Overhead Press', 'shoulders', 'selectorized'),
('Cybex', '20030', 'Eagle NX Row', 'back', 'selectorized'),
('Cybex', '20040', 'Eagle NX Leg Press', 'legs', 'selectorized'),
('Cybex', '20050', 'Eagle NX Leg Extension', 'legs', 'selectorized'),
('Cybex', '20060', 'Eagle NX Seated Leg Curl', 'legs', 'selectorized'),
('Cybex', '20070', 'Eagle NX Arm Curl', 'arms', 'selectorized'),
('Cybex', '20080', 'Eagle NX Arm Extension', 'arms', 'selectorized'),
('Cybex', '20090', 'Eagle NX Abdominal', 'core', 'selectorized'),
('Cybex', '20100', 'Eagle NX Back Extension', 'back', 'selectorized'),
('Cybex', '20120', 'Eagle NX Calf', 'legs', 'selectorized'),
('Cybex', '20130', 'Eagle NX Lat Pulldown', 'back', 'selectorized'),
('Cybex', '20170', 'Eagle NX Glute', 'legs', 'selectorized'),
('Cybex', '20180', 'Eagle NX Hip Ab-Ad', 'legs', 'selectorized'),
('Cybex', '20190', 'Eagle NX Hip Torso', 'core', 'selectorized'),
-- Cybex Eagle (Discontinued)
('Cybex', '11000', 'Eagle Chest Press', 'chest', 'selectorized'),
('Cybex', '11010', 'Eagle Overhead Press', 'shoulders', 'selectorized'),
('Cybex', '11020', 'Eagle Incline Pull', 'back', 'selectorized'),
('Cybex', '11030', 'Eagle Row', 'back', 'selectorized'),
('Cybex', '11040', 'Eagle Leg Press', 'legs', 'selectorized'),
('Cybex', '11050', 'Eagle Leg Extension', 'legs', 'selectorized'),
('Cybex', '11060', 'Eagle Seated Leg Curl', 'legs', 'selectorized'),
('Cybex', '11070', 'Eagle Arm Curl', 'arms', 'selectorized'),
('Cybex', '11080', 'Eagle Arm Extension', 'arms', 'selectorized'),
('Cybex', '11090', 'Eagle Abdominal', 'core', 'selectorized'),
('Cybex', '11100', 'Eagle Back Extension', 'back', 'selectorized'),
('Cybex', '11110', 'Eagle Fly / Rear Delt', 'chest', 'selectorized'),
('Cybex', '11120', 'Eagle Calf Raise', 'legs', 'selectorized'),
('Cybex', '11130', 'Eagle Lat Pulldown', 'back', 'selectorized'),
('Cybex', '11140', 'Eagle Prone Leg Curl', 'legs', 'selectorized'),
('Cybex', '11150', 'Eagle Incline Press', 'chest', 'selectorized'),
('Cybex', '11160', 'Eagle Lateral Raise', 'shoulders', 'selectorized'),
('Cybex', '11170', 'Eagle Glute', 'legs', 'selectorized'),
('Cybex', '11180', 'Eagle Hip Abduction/Adduction', 'legs', 'selectorized'),
('Cybex', '11190', 'Eagle Torso Rotation', 'core', 'selectorized'),
-- Cybex VR3 (Selectorized)
('Cybex', '12000', 'VR3 Chest Press', 'chest', 'selectorized'),
('Cybex', '12010', 'VR3 Overhead Press', 'shoulders', 'selectorized'),
('Cybex', '12020', 'VR3 Lat Pulldown', 'back', 'selectorized'),
('Cybex', '12030', 'VR3 Row', 'back', 'selectorized'),
('Cybex', '12040', 'VR3 Leg Press', 'legs', 'selectorized'),
('Cybex', '12050', 'VR3 Leg Extension', 'legs', 'selectorized'),
('Cybex', '12060', 'VR3 Seated Leg Curl', 'legs', 'selectorized'),
('Cybex', '12070', 'VR3 Arm Curl', 'arms', 'selectorized'),
('Cybex', '12080', 'VR3 Arm Extension', 'arms', 'selectorized'),
('Cybex', '12090', 'VR3 Abdominal', 'core', 'selectorized'),
('Cybex', '12100', 'VR3 Back Extension', 'back', 'selectorized'),
('Cybex', '12120', 'VR3 Standing Calf', 'legs', 'selectorized'),
('Cybex', '12190', 'VR3 Torso Rotation', 'core', 'selectorized'),
('Cybex', '12200', 'VR3 Hip Abduction', 'legs', 'selectorized'),
('Cybex', '12210', 'VR3 Hip Adduction', 'legs', 'selectorized'),
-- Cybex VR1 (Selectorized, Compact)
('Cybex', '13000', 'VR1 Chest Press', 'chest', 'selectorized'),
('Cybex', '13010', 'VR1 Overhead Press', 'shoulders', 'selectorized'),
('Cybex', '13030', 'VR1 Row / Rear Delt', 'back', 'selectorized'),
('Cybex', '13041', 'VR1 Leg Press', 'legs', 'selectorized'),
('Cybex', '13050', 'VR1 Leg Extension', 'legs', 'selectorized'),
('Cybex', '13060', 'VR1 Seated Leg Curl', 'legs', 'selectorized'),
('Cybex', '13075', 'VR1 Arm Curl', 'arms', 'selectorized'),
('Cybex', '13085', 'VR1 Arm Extension', 'arms', 'selectorized'),
('Cybex', '13090', 'VR1 Abdominal', 'core', 'selectorized'),
('Cybex', '13100', 'VR1 Back Extension', 'back', 'selectorized'),
('Cybex', '13111', 'VR1 Fly / Rear Delt', 'chest', 'selectorized'),
('Cybex', '13120', 'VR1 Standing Calf', 'legs', 'selectorized'),
('Cybex', '13135', 'VR1 Lat Pulldown', 'back', 'selectorized'),
('Cybex', '13170', 'VR1 Glute', 'legs', 'selectorized'),
('Cybex', '13180', 'VR1 Hip Ab-Ad', 'legs', 'selectorized'),
('Cybex', '13240', 'VR1 Multi-Press', 'chest', 'selectorized'),
('Cybex', '13250', 'VR1 Dual Lat/Row', 'back', 'selectorized'),
-- Cybex Ion Series (Selectorized)
('Cybex', 'CI-CP', 'Ion Chest Press', 'chest', 'selectorized'),
('Cybex', 'CI-SP', 'Ion Shoulder Press', 'shoulders', 'selectorized'),
('Cybex', 'CI-MP', 'Ion Multi Press', 'chest', 'selectorized'),
('Cybex', 'CI-LP', 'Ion Leg Press', 'legs', 'selectorized'),
('Cybex', 'CI-LCE', 'Ion Leg Curl / Extension', 'legs', 'selectorized'),
('Cybex', 'CI-SLCE', 'Ion Seated Leg Curl / Extension', 'legs', 'selectorized'),
('Cybex', 'CI-LPR', 'Ion Lat Pulldown / Low Row', 'back', 'selectorized'),
('Cybex', 'CI-LAT', 'Ion Lat Pulldown', 'back', 'selectorized'),
('Cybex', 'CI-ROW', 'Ion Seated Row', 'back', 'selectorized'),
('Cybex', 'CI-PFR', 'Ion Pec Fly / Rear Delt', 'chest', 'selectorized'),
('Cybex', 'CI-BT', 'Ion Biceps / Triceps', 'arms', 'selectorized'),
('Cybex', 'CI-HAA', 'Ion Hip Abductor / Adductor', 'legs', 'selectorized'),
('Cybex', 'CI-AB', 'Ion Abdominal', 'core', 'selectorized'),
-- Cybex Bravo (Cable/Functional)
('Cybex', '8800', 'Bravo Advanced (Compact)', 'chest', 'cable'),
('Cybex', '8810', 'Bravo Advanced (Tall)', 'chest', 'cable'),
('Cybex', '8830', 'Bravo Basic (Compact)', 'chest', 'cable'),
('Cybex', '8840', 'Bravo Pro (Tall)', 'chest', 'cable'),
-- Cybex Plate Loaded (5000 Series)
('Cybex', '5220', 'Plate Loaded Shoulder Press', 'shoulders', 'plate-loaded'),
('Cybex', '5225', 'Plate Loaded Bench Press', 'chest', 'plate-loaded'),
('Cybex', '5226', 'Plate Loaded Advanced Pulldown', 'back', 'plate-loaded'),
('Cybex', '5227', 'Plate Loaded Converging Chest Press', 'chest', 'plate-loaded'),
('Cybex', '5230', 'Plate Loaded Hack Squat', 'legs', 'plate-loaded'),
('Cybex', '5235', 'Plate Loaded Squat Press', 'legs', 'plate-loaded'),
('Cybex', '5240', 'Plate Loaded Kneeling Leg Curl', 'legs', 'plate-loaded'),
('Cybex', '5245', 'Plate Loaded Leg Extension', 'legs', 'plate-loaded'),
('Cybex', '5251', 'Plate Loaded Advanced Incline Press', 'chest', 'plate-loaded'),
('Cybex', '5252', 'Plate Loaded Converging Incline Press', 'chest', 'plate-loaded'),
('Cybex', '5255', 'Plate Loaded Rear Delt', 'shoulders', 'plate-loaded'),
('Cybex', '5261', 'Plate Loaded Advanced Pulldown', 'back', 'plate-loaded'),
('Cybex', '5265', 'Plate Loaded Row', 'back', 'plate-loaded'),
-- Cybex Big Iron (Racks)
('Cybex', '19000', 'Big Iron 9ft Half Rack', 'legs', 'rack'),
('Cybex', '19010', 'Big Iron 8ft Half Rack', 'legs', 'rack'),
('Cybex', '19040', 'Big Iron Power Rack', 'legs', 'rack'),
-- Cybex Benches
('Cybex', '5410', 'Olympic Flat Bench', 'chest', 'bench'),
('Cybex', '5430', 'Flat Bench', 'chest', 'bench'),
('Cybex', '5435', 'Flat to Incline Bench', 'chest', 'bench'),
('Cybex', '5437', 'Adjustable Bench', 'chest', 'bench'),
('Cybex', '5440', 'Adjustable Incline Bench', 'chest', 'bench'),
('Cybex', '5460', 'Scott / Preacher Curl', 'arms', 'bench'),
('Cybex', '5502', 'Olympic Decline Bench', 'chest', 'bench'),
('Cybex', '16210', 'Seated Calf', 'legs', 'plate-loaded')
ON CONFLICT DO NOTHING;
