-- Impulse equipment catalog
-- Exported on 2026-03-24
-- 58 records: 30 IT95 (selectorized) + 28 SL (plate-loaded)

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
-- Impulse IT95 Series (Selectorized)
(1154, 'Impulse', 'IT9501', 'Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9501.jpg'),
(1155, 'Impulse', 'IT9502', 'Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9502.jpg'),
(1156, 'Impulse', 'IT9503', 'Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9503.jpg'),
(1157, 'Impulse', 'IT9504', 'Pectoral', 'chest', 'selectorized', 'chest_fly', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9504.jpg'),
(1158, 'Impulse', 'IT9505', 'Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9505.jpg'),
(1159, 'Impulse', 'IT9506', 'Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9506.jpg'),
(1160, 'Impulse', 'IT9508', 'Abductor/Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9508.jpg'),
(1161, 'Impulse', 'IT9509', 'Total Hip', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9509.jpg'),
(1162, 'Impulse', 'IT9510', 'Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9510.jpg'),
(1163, 'Impulse', 'IT9512', 'Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9512.jpg'),
(1164, 'Impulse', 'IT9514', 'Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9514.jpg'),
(1165, 'Impulse', 'IT9515', 'Pec Fly/Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9515.jpg'),
(1166, 'Impulse', 'IT9516', 'Calf Raise', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9516.jpg'),
(1167, 'Impulse', 'IT9517', 'Seated Dip', 'chest', 'selectorized', 'chest_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9517.jpg'),
(1168, 'Impulse', 'IT9518', 'Torso Rotation', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9518.jpg'),
(1169, 'Impulse', 'IT9519', 'Vertical Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9519.jpg'),
(1170, 'Impulse', 'IT9520', 'Weight Assisted Chin/Dip', 'chest', 'selectorized', 'chest_dip,lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9520.jpg'),
(1171, 'Impulse', 'IT9521', 'Prone Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9521.jpg'),
(1172, 'Impulse', 'IT9522', 'Lat Pulldown/Vertical Row', 'back', 'selectorized', 'lat_pulldown,seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9522.jpg'),
(1173, 'Impulse', 'IT9524', 'Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9524.jpg'),
(1174, 'Impulse', 'IT9526', 'Glute', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9526.jpg'),
(1175, 'Impulse', 'IT9528', 'Leg Extension/Leg Curl', 'legs', 'selectorized', 'leg_extension,seated_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9528.jpg'),
(1176, 'Impulse', 'IT9529', 'Multi Press', 'chest', 'selectorized', 'chest_press,shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9529.jpg'),
(1177, 'Impulse', 'IT9530', 'Dual Adjustable Pulley', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9530.png'),
(1178, 'Impulse', 'IT9532', 'Back Extension', 'back', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9532.jpg'),
(1179, 'Impulse', 'IT9533', 'Bicep Curl/Tricep Extension', 'arms', 'selectorized', 'bicep_curl,tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9533.jpg'),
(1180, 'Impulse', 'IT9534', 'Abdominal/Back Extension', 'core', 'selectorized', 'crunch,back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9534.jpg'),
(1181, 'Impulse', 'IT9537', 'Standing Multi Flight Machine', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9537.png'),
(1182, 'Impulse', 'IT9538', 'Hip Thrust', 'glutes', 'selectorized', 'hip_thrust', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9538.png'),
(1183, 'Impulse', 'IT9539', 'Horizontal Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/IT9539.jpg'),
-- Impulse SL Series (Plate-loaded)
(1184, 'Impulse', 'SL7001', 'Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7001.jpg'),
(1185, 'Impulse', 'SL7002', 'Pulldown', 'back', 'plate-loaded', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7002.jpg'),
(1186, 'Impulse', 'SL7003', 'Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7003.jpg'),
(1187, 'Impulse', 'SL7004', 'Low Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7004.jpg'),
(1188, 'Impulse', 'SL7005', 'Incline Press', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7005.jpg'),
(1189, 'Impulse', 'SL7006', 'Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7006.jpg'),
(1190, 'Impulse', 'SL7007', 'Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7007.jpg'),
(1191, 'Impulse', 'SL7008', 'Rear Kick', 'glutes', 'plate-loaded', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7008.jpg'),
(1192, 'Impulse', 'SL7013', 'Glute Ham Developer', 'back', 'plate-loaded', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7013.jpg'),
(1193, 'Impulse', 'SL7017', 'Seated Calf Raise', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7017.jpg'),
(1194, 'Impulse', 'SL7018', 'Arm Curl', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7018.jpg'),
(1195, 'Impulse', 'SL7019', 'Incline Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7019.jpg'),
(1196, 'Impulse', 'SL7020', 'Reverse Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7020.jpg'),
(1197, 'Impulse', 'SL7021', 'Hack Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7021.jpg'),
(1198, 'Impulse', 'SL7023', 'Bicep Curl', 'arms', 'plate-loaded', 'preacher_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7023.jpg'),
(1199, 'Impulse', 'SL7024', 'Tricep Dip', 'arms', 'plate-loaded', 'tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7024.jpg'),
(1200, 'Impulse', 'SL7025', 'Leg Extension', 'legs', 'plate-loaded', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7025.jpg'),
(1201, 'Impulse', 'SL7026', 'Standing Leg Curl', 'legs', 'plate-loaded', 'standing_leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7026.jpg'),
(1202, 'Impulse', 'SL7032', 'Standing Calf', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7032.jpg'),
(1203, 'Impulse', 'SL7034', 'Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7034.jpg'),
(1204, 'Impulse', 'SL7036', 'Abdominals', 'core', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7036.jpg'),
(1205, 'Impulse', 'SL7038', 'Total Hip', 'legs', 'plate-loaded', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7038.jpg'),
(1206, 'Impulse', 'SL7039', 'Standing Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7039.jpg'),
(1207, 'Impulse', 'SL7042', 'Smith Machine', 'full_body', 'plate-loaded', 'smith_machine', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7042.jpg'),
(1208, 'Impulse', 'SL7046', 'Lateral Super Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7046.jpg'),
(1209, 'Impulse', 'SL7047', 'Multi Hyper Extension', 'back', 'plate-loaded', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7047.jpg'),
(1210, 'Impulse', 'SL7055', 'Belt Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7055.jpg'),
(1211, 'Impulse', 'SL7057', 'Pendulum Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/impulse/SL7057.png')
ON CONFLICT (id) DO UPDATE SET
  brand=EXCLUDED.brand, model=EXCLUDED.model, name=EXCLUDED.name,
  muscle_group=EXCLUDED.muscle_group, equipment_type=EXCLUDED.equipment_type,
  exercise_type=EXCLUDED.exercise_type, image_url=EXCLUDED.image_url;
