-- Matrix Fitness equipment catalog
-- Created 2026-03-23
-- 96 records: Ultra (19), Versa Singles (14), Versa Dual (6), Aura (18), Magnum PL (17), Magnum Benches (9), Varsity PL (6), Cable/Functional (7)

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES
-- Matrix Ultra Series (G7-S) — Premium Selectorized, 19 machines
(800, 'Matrix', 'G7-S12', 'Ultra Pectoral Fly', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(801, 'Matrix', 'G7-S13', 'Ultra Converging Chest Press', 'chest', 'selectorized', 'chest_press', NULL),
(802, 'Matrix', 'G7-S21', 'Ultra Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', NULL),
(803, 'Matrix', 'G7-S23', 'Ultra Converging Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(804, 'Matrix', 'G7-S33', 'Ultra Diverging Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(805, 'Matrix', 'G7-S34', 'Ultra Diverging Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(806, 'Matrix', 'G7-S40', 'Ultra Independent Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(807, 'Matrix', 'G7-S42', 'Ultra Triceps Press', 'arms', 'selectorized', 'tricep_extension', NULL),
(808, 'Matrix', 'G7-S51', 'Ultra Abdominal Crunch', 'core', 'selectorized', 'crunch', NULL),
(809, 'Matrix', 'G7-S52', 'Ultra Back Extension', 'back', 'selectorized', 'back_extension', NULL),
(810, 'Matrix', 'G7-S55', 'Ultra Rotary Torso', 'core', 'selectorized', 'torso_rotation', NULL),
(811, 'Matrix', 'G7-S70', 'Ultra Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(812, 'Matrix', 'G7-S71', 'Ultra Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(813, 'Matrix', 'G7-S72', 'Ultra Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(814, 'Matrix', 'G7-S73', 'Ultra Prone Leg Curl', 'legs', 'selectorized', 'lying_leg_curl', NULL),
(815, 'Matrix', 'G7-S74', 'Ultra Hip Adductor', 'legs', 'selectorized', 'hip_adduction', NULL),
(816, 'Matrix', 'G7-S75', 'Ultra Hip Abductor', 'legs', 'selectorized', 'hip_abduction', NULL),
(817, 'Matrix', 'G7-S77', 'Ultra Calf Extension', 'legs', 'selectorized', 'calf', NULL),
(818, 'Matrix', 'G7-S78', 'Ultra Glute', 'legs', 'selectorized', 'glute_kickback', NULL),
-- Matrix Versa Series (VS-S) — Single Stations, 14 machines
(819, 'Matrix', 'VS-S13', 'Versa Converging Chest Press', 'chest', 'selectorized', 'chest_press', NULL),
(820, 'Matrix', 'VS-S22', 'Versa Pectoral Fly / Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(821, 'Matrix', 'VS-S23', 'Versa Converging Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(822, 'Matrix', 'VS-S33', 'Versa Diverging Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(823, 'Matrix', 'VS-S34', 'Versa Diverging Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(824, 'Matrix', 'VS-S40', 'Versa Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(825, 'Matrix', 'VS-S42', 'Versa Triceps Press', 'arms', 'selectorized', 'tricep_extension', NULL),
(826, 'Matrix', 'VS-S52', 'Versa Back Extension', 'back', 'selectorized', 'back_extension', NULL),
(827, 'Matrix', 'VS-S53', 'Versa Abdominal', 'core', 'selectorized', 'crunch', NULL),
(828, 'Matrix', 'VS-S70', 'Versa Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(829, 'Matrix', 'VS-S71', 'Versa Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(830, 'Matrix', 'VS-S72', 'Versa Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(831, 'Matrix', 'VS-S74', 'Versa Hip Ab/Adductor', 'legs', 'selectorized', 'hip_abduction,hip_adduction', NULL),
(832, 'Matrix', 'VS-S78', 'Versa Glute', 'legs', 'selectorized', 'glute_kickback', NULL),
-- Matrix Versa Dual Series (VS-S) — Combo Stations, 6 machines
(833, 'Matrix', 'VS-S131', 'Versa Dual Multi Press', 'chest', 'selectorized', 'chest_press,incline_press,shoulder_press', NULL),
(834, 'Matrix', 'VS-S331', 'Versa Dual Lat Pulldown / Seated Row', 'back', 'selectorized', 'lat_pulldown,seated_row', NULL),
(835, 'Matrix', 'VS-S401', 'Versa Dual Bicep / Tricep', 'arms', 'selectorized', 'bicep_curl,tricep_extension', NULL),
(836, 'Matrix', 'VS-S531', 'Versa Dual Ab / Low Back', 'core', 'selectorized', 'crunch,back_extension', NULL),
(837, 'Matrix', 'VS-S601', 'Versa Dual Chin / Dip Assist', 'chest', 'selectorized', 'chest_dip', NULL),
(838, 'Matrix', 'VS-S711', 'Versa Dual Leg Extension / Leg Curl', 'legs', 'selectorized', 'leg_extension,seated_leg_curl', NULL),
-- Matrix Aura Series (G3-S) — Classic Selectorized, 18 machines
(839, 'Matrix', 'G3-S13', 'Aura Converging Chest Press', 'chest', 'selectorized', 'chest_press', NULL),
(840, 'Matrix', 'G3-S21', 'Aura Lateral Raise', 'shoulders', 'selectorized', 'lateral_raise', NULL),
(841, 'Matrix', 'G3-S22', 'Aura Rear Delt / Pec Fly', 'chest', 'selectorized', 'chest_fly,rear_delt', NULL),
(842, 'Matrix', 'G3-S23', 'Aura Converging Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', NULL),
(843, 'Matrix', 'G3-S31', 'Aura Seated Row', 'back', 'selectorized', 'seated_row', NULL),
(844, 'Matrix', 'G3-S33', 'Aura Diverging Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', NULL),
(845, 'Matrix', 'G3-S40', 'Aura Biceps Curl', 'arms', 'selectorized', 'bicep_curl', NULL),
(846, 'Matrix', 'G3-S42', 'Aura Triceps Extension', 'arms', 'selectorized', 'tricep_extension', NULL),
(847, 'Matrix', 'G3-S51', 'Aura Abdominal Crunch', 'core', 'selectorized', 'crunch', NULL),
(848, 'Matrix', 'G3-S52', 'Aura Back Extension', 'back', 'selectorized', 'back_extension', NULL),
(849, 'Matrix', 'G3-S60', 'Aura Dip / Chin Assist', 'chest', 'selectorized', 'chest_dip', NULL),
(850, 'Matrix', 'G3-S70', 'Aura Leg Press', 'legs', 'selectorized', 'leg_press', NULL),
(851, 'Matrix', 'G3-S71', 'Aura Leg Extension', 'legs', 'selectorized', 'leg_extension', NULL),
(852, 'Matrix', 'G3-S72', 'Aura Seated Leg Curl', 'legs', 'selectorized', 'seated_leg_curl', NULL),
(853, 'Matrix', 'G3-S74', 'Aura Hip Adductor', 'legs', 'selectorized', 'hip_adduction', NULL),
(854, 'Matrix', 'G3-S75', 'Aura Hip Abductor', 'legs', 'selectorized', 'hip_abduction', NULL),
(855, 'Matrix', 'G3-S76', 'Aura Rotary Hip', 'legs', 'selectorized', 'hip_abduction,hip_adduction', NULL),
(856, 'Matrix', 'G3-S78', 'Aura Glute', 'legs', 'selectorized', 'glute_kickback', NULL),
-- Matrix Magnum Plate-Loaded (MG-PL) — 16 machines
(857, 'Matrix', 'MG-PL12', 'Magnum Vertical Bench Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(858, 'Matrix', 'MG-PL13', 'Magnum Supine Bench Press', 'chest', 'plate-loaded', 'chest_press', NULL),
(859, 'Matrix', 'MG-PL14', 'Magnum Incline Bench Press', 'chest', 'plate-loaded', 'incline_press', NULL),
(860, 'Matrix', 'MG-PL15', 'Magnum Vertical Decline Bench Press', 'chest', 'plate-loaded', 'decline_press', NULL),
(861, 'Matrix', 'MG-PL23', 'Magnum Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', NULL),
(862, 'Matrix', 'MG-PL33', 'Magnum Lat Pulldown', 'back', 'plate-loaded', 'lat_pulldown', NULL),
(863, 'Matrix', 'MG-PL34', 'Magnum Seated Row', 'back', 'plate-loaded', 'seated_row', NULL),
(864, 'Matrix', 'MG-PL38', 'Magnum Low Row', 'back', 'plate-loaded', 'seated_row', NULL),
(865, 'Matrix', 'MG-PL50', 'Magnum Ab Crunch Bench', 'core', 'plate-loaded', 'crunch', NULL),
(866, 'Matrix', 'MG-PL62', 'Magnum Smith Machine', 'full_body', 'plate-loaded', 'smith_machine,squat,shoulder_press,chest_press,incline_press', NULL),
(867, 'Matrix', 'MG-PL70', 'Magnum 45-Degree Leg Press', 'legs', 'plate-loaded', 'leg_press', NULL),
(868, 'Matrix', 'MG-PL71', 'Magnum Hack Squat', 'legs', 'plate-loaded', 'squat', NULL),
(869, 'Matrix', 'MG-PL76', 'Magnum Standing Calf', 'legs', 'plate-loaded', 'calf', NULL),
(870, 'Matrix', 'MG-PL77', 'Magnum Seated Calf', 'legs', 'plate-loaded', 'calf', NULL),
(871, 'Matrix', 'MG-PL78', 'Magnum Glute Trainer', 'legs', 'plate-loaded', 'glute_kickback', NULL),
(872, 'Matrix', 'MG-PL79', 'Magnum Squat / Lunge', 'legs', 'plate-loaded', 'squat', NULL),
-- Matrix Varsity Plate-Loaded (VY) — 6 machines
(873, 'Matrix', 'VY-M49', 'Varsity Angled Smith Machine', 'full_body', 'plate-loaded', 'smith_machine,squat,shoulder_press,chest_press,incline_press', NULL),
(874, 'Matrix', 'VY-400', 'Varsity Perfect Squat', 'legs', 'plate-loaded', 'squat', NULL),
(875, 'Matrix', 'VY-401', 'Varsity Leg Extension', 'legs', 'plate-loaded', 'leg_extension', NULL),
(876, 'Matrix', 'VY-402', 'Varsity Prone Leg Curl', 'legs', 'plate-loaded', 'lying_leg_curl', NULL),
(877, 'Matrix', 'VY-431', 'Varsity Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', NULL),
(878, 'Matrix', 'VY-432', 'Varsity Triceps Extension', 'arms', 'plate-loaded', 'tricep_extension', NULL),
-- Matrix Magnum Plate-Loaded (additional)
(881, 'Matrix', 'MG-405', 'Magnum Reverse Back Extension', 'back', 'plate-loaded', 'back_extension', NULL),
(882, 'Matrix', 'MG-A417', 'Magnum Incline Bench Press', 'chest', 'plate-loaded', 'incline_press', NULL),
-- Matrix Cable / Functional — 7 machines
(879, 'Matrix', 'G3-MSFT3', 'Aura Functional Trainer', 'full_body', 'cable', 'cable_multi', NULL),
(880, 'Matrix', 'VS-VFT', 'Versa Functional Trainer', 'full_body', 'cable', 'cable_multi', NULL),
(883, 'Matrix', 'G3-MS20', 'Aura Adjustable Cable Crossover', 'full_body', 'cable', 'cable_multi', NULL),
(884, 'Matrix', 'G3-MS50', 'Aura 4-Stack Multi-Station', 'full_body', 'cable', 'cable_multi', NULL),
(885, 'Matrix', 'G3-MS80', 'Aura 8-Stack Multi-Station', 'full_body', 'cable', 'cable_multi', NULL),
(886, 'Matrix', 'VY-6044', 'Varsity Functional Trainer 2:1', 'full_body', 'cable', 'cable_multi', NULL),
(887, 'Matrix', 'VY-6047', 'Varsity Functional Trainer 4:1', 'full_body', 'cable', 'cable_multi', NULL),
-- Matrix Magnum Benches (MG-A series) — 8 machines
(888, 'Matrix', 'MG-A59', 'Magnum Flat Bench', 'chest', 'bench', 'bench', NULL),
(889, 'Matrix', 'MG-A62', 'Magnum Preacher Curl', 'arms', 'bench', 'preacher_curl', NULL),
(890, 'Matrix', 'MG-A77', 'Magnum Adjustable Ab Bench', 'core', 'bench', 'crunch', NULL),
(891, 'Matrix', 'MG-A78', 'Magnum Olympic Flat Bench', 'chest', 'bench', 'bench', NULL),
(892, 'Matrix', 'MG-A85', 'Magnum Multi-Adjustable Bench', 'chest', 'bench', 'bench', NULL),
(893, 'Matrix', 'MG-A86', 'Magnum Multi-Adjustable Bench w/Decline', 'chest', 'bench', 'decline_press', NULL),
(894, 'Matrix', 'MG-A93', 'Magnum Back Extension Bench', 'back', 'bench', 'back_extension', NULL),
(895, 'Matrix', 'MG-A695', 'Magnum Flat-to-Incline Bench', 'chest', 'bench', 'bench', NULL)
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  name = EXCLUDED.name,
  muscle_group = EXCLUDED.muscle_group,
  equipment_type = EXCLUDED.equipment_type,
  exercise_type = EXCLUDED.exercise_type,
  image_url = COALESCE(EXCLUDED.image_url, equipment_catalog.image_url);
