-- Nautilus equipment catalog
-- 104 records: Instinct (26), Inspiration (20), Impact (22), ONE (13), Leverage (11), Plate-loaded (4), HumanSport (8)
-- Images sourced from BigCommerce CDN (ardentfitness) and Shopify CDN (showmeweights)

INSERT INTO equipment_catalog (id, brand, model, name, muscle_group, equipment_type, exercise_type, image_url) VALUES

-- ===== INSTINCT SERIES (Selectorized) =====
(1212, 'Nautilus', '9NL-S2100', 'Instinct Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S2100.jpg'),
(1213, 'Nautilus', '9NL-D2120', 'Instinct Dual Multi-Press', 'chest', 'selectorized', 'incline_press,chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D2120.jpg'),
(1214, 'Nautilus', '9NL-D2110', 'Instinct Dual Pec Fly/Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D2110.jpg'),
(1215, 'Nautilus', '9NL-S4100', 'Instinct Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S4100.jpg'),
(1216, 'Nautilus', '9NL-S3310', 'Instinct Lat Pull Down', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S3310.jpg'),
(1217, 'Nautilus', '9NL-S3320', 'Instinct Vertical Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S3320.jpg'),
(1218, 'Nautilus', '9NL-D3340', 'Instinct Dual Lat Pulldown/Vertical Row', 'back', 'selectorized', 'lat_pulldown,seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D3340.jpg'),
(1219, 'Nautilus', '9NL-S5100', 'Instinct Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S5100.jpg'),
(1220, 'Nautilus', '9NL-S5110', 'Instinct Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S5110.jpg'),
(1221, 'Nautilus', '9NL-D5120', 'Instinct Dual Biceps/Triceps', 'arms', 'selectorized', 'bicep_curl,tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D5120.jpg'),
(1222, 'Nautilus', '9NL-D1013', 'Instinct Dual Leg Press/Calf', 'legs', 'selectorized', 'leg_press,calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D1013.jpg'),
(1223, 'Nautilus', '9NL-S1010', 'Instinct Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S1010.jpg'),
(1224, 'Nautilus', '9NL-S1011', 'Instinct Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S1011.jpg'),
(1225, 'Nautilus', '9NL-D1014', 'Instinct Dual Leg Extension/Leg Curl', 'legs', 'selectorized', 'leg_extension,leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D1014.jpg'),
(1226, 'Nautilus', '9NL-D1015', 'Instinct Dual Inner/Outer Thigh', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D1015.jpg'),
(1227, 'Nautilus', '9NL-S1012', 'Instinct Glute Press', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S1012.jpg'),
(1228, 'Nautilus', '9NL-S6300', 'Instinct Rotary Torso', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-S6300.jpg'),
(1229, 'Nautilus', '9NL-D6330', 'Instinct Dual Abdominal/Lower Back', 'core', 'selectorized', 'crunch,back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D6330.jpg'),
(1230, 'Nautilus', '9NL-D2002', 'Instinct Dual Adjustable Pulley', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NL-D2002.jpg'),

-- Instinct Benches
(1231, 'Nautilus', '9NN-B7503', 'Instinct Olympic Flat Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NN-B7503.jpg'),
(1232, 'Nautilus', '9NN-B7201', 'Instinct Olympic Incline Bench', 'chest', 'bench', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NN-B7201.jpg'),
(1233, 'Nautilus', '9NN-B7501', 'Instinct Multi-Adjustable Bench', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NN-B7501.jpg'),
(1234, 'Nautilus', '9NN-B7506', 'Instinct Multi-Adjustable Bench 100', 'chest', 'bench', 'bench', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NN-B7506.jpg'),
(1235, 'Nautilus', '9NN-B7502', 'Instinct 45° Back Extension', 'core', 'bench', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NN-B7502.jpg'),
(1236, 'Nautilus', '9NN-B7200', 'Instinct Adjustable Abdominal Decline Bench', 'core', 'bench', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NN-B7200.jpg'),
(1237, 'Nautilus', '9NN-B7505', 'Instinct Ab Bench', 'core', 'bench', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NN-B7505.jpg'),

-- ===== INSPIRATION SERIES (Selectorized) =====
(1238, 'Nautilus', 'IPVP3', 'Inspiration Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPVP3.jpg'),
(1239, 'Nautilus', 'IPPF3', 'Inspiration Pec Fly/Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPPF3.jpg'),
(1240, 'Nautilus', '9-IPPO3', 'Inspiration Pull Over', 'chest', 'selectorized', 'pullover', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9-IPPO3.jpg'),
(1241, 'Nautilus', 'IPSP3', 'Inspiration Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPSP3.jpg'),
(1242, 'Nautilus', 'IPDR3', 'Inspiration Deltoid Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPDR3.jpg'),
(1243, 'Nautilus', 'IPPD3', 'Inspiration Lat Pull Down', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPPD3.jpg'),
(1244, 'Nautilus', 'IPVR3', 'Inspiration Vertical Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPVR3.jpg'),
(1245, 'Nautilus', 'IPBC3', 'Inspiration Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPBC3.jpg'),
(1246, 'Nautilus', 'IPBA3', 'Inspiration Bilateral Arm Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPBA3.jpg'),
(1247, 'Nautilus', 'IPTE3', 'Inspiration Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPTE3.jpg'),
(1248, 'Nautilus', 'IPTD4', 'Inspiration Tricep Dip', 'arms', 'selectorized', 'tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPTD4.jpg'),
(1249, 'Nautilus', 'IPLP3', 'Inspiration Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPLP3.jpg'),
(1250, 'Nautilus', 'IPLE33', 'Inspiration Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPLE33.jpg'),
(1251, 'Nautilus', 'IPLC3', 'Inspiration Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPLC3.jpg'),
(1252, 'Nautilus', 'IPAA4', 'Inspiration Abduction/Adduction', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPAA4.jpg'),
(1253, 'Nautilus', 'IPGM3', 'Inspiration Glute Press', 'glutes', 'selectorized', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPGM3.jpg'),
(1254, 'Nautilus', 'IPAC3', 'Inspiration Abdominal Crunch', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPAC3.jpg'),
(1255, 'Nautilus', 'IPBE3', 'Inspiration Back Extension', 'core', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPBE3.jpg'),
(1256, 'Nautilus', 'IPRT5', 'Inspiration Rotary Torso', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPRT5.jpg'),
(1257, 'Nautilus', 'NP-D9302', 'Inspiration Dual Adjustable Pulley', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/NP-D9302.jpg'),

-- ===== IMPACT SERIES (Selectorized) =====
(1258, 'Nautilus', '9NA-S4301', 'Impact Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S4301.jpg'),
(1259, 'Nautilus', '9NA-S2301', 'Impact Incline Press', 'chest', 'selectorized', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S2301.jpg'),
(1260, 'Nautilus', '9NA-S4304', 'Impact Pec Fly/Rear Delt', 'chest', 'selectorized', 'chest_fly,rear_delt', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S4304.jpg'),
(1261, 'Nautilus', '9NA-S4307', 'Impact Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S4307.jpg'),
(1262, 'Nautilus', '9NA-S4302', 'Impact Deltoid Raise', 'shoulders', 'selectorized', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S4302.jpg'),
(1263, 'Nautilus', '9NA-S3305', 'Impact Lat Pull Down', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S3305.jpg'),
(1264, 'Nautilus', '9NA-S3303', 'Impact Fixed Lat Pull Down', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S3303.jpg'),
(1265, 'Nautilus', '9NA-S3301', 'Impact Vertical Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S3301.jpg'),
(1266, 'Nautilus', '9NA-S3306', 'Impact Low Row', 'back', 'selectorized', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S3306.jpg'),
(1267, 'Nautilus', '9NA-S3302', 'Impact Low Back', 'core', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S3302.jpg'),
(1268, 'Nautilus', '9NA-S5301', 'Impact Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S5301.jpg'),
(1269, 'Nautilus', '9NA-S5302', 'Impact Triceps Extension', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S5302.jpg'),
(1270, 'Nautilus', '9NA-S5303', 'Impact Dip Machine', 'arms', 'selectorized', 'tricep_dip', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S5303.jpg'),
(1271, 'Nautilus', '9NA-S6334', 'Impact Chin Dip Assist', 'arms', 'selectorized', 'tricep_dip,lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S6334.jpg'),
(1272, 'Nautilus', '9NA-S1305', 'Impact Seated Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S1305.jpg'),
(1273, 'Nautilus', '9NA-S1312', 'Impact Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S1312.jpg'),
(1274, 'Nautilus', '9NA-S1313', 'Impact Seated Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S1313.jpg'),
(1275, 'Nautilus', '9NA-S1311', 'Impact Kneeling Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S1311.jpg'),
(1276, 'Nautilus', '9NA-S1307', 'Impact Abductor', 'legs', 'selectorized', 'hip_abduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S1307.jpg'),
(1277, 'Nautilus', '9NA-S1308', 'Impact Adductor', 'legs', 'selectorized', 'hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S1308.jpg'),
(1278, 'Nautilus', '9NA-S1309', 'Impact Standing Calf', 'legs', 'selectorized', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S1309.jpg'),
(1279, 'Nautilus', '9NA-S6301', 'Impact Abdominal', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NA-S6301.jpg'),

-- ===== ONE SERIES (Selectorized) =====
(1280, 'Nautilus', 'S6CP', 'ONE Chest Press', 'chest', 'selectorized', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6CP.png'),
(1281, 'Nautilus', 'S6SP', 'ONE Shoulder Press', 'shoulders', 'selectorized', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6SP.jpg'),
(1282, 'Nautilus', 'S6LATP', 'ONE Lat Pulldown', 'back', 'selectorized', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6LATP.jpg'),
(1283, 'Nautilus', 'S6MR', 'ONE Row', 'back', 'selectorized', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6MR.png'),
(1284, 'Nautilus', 'S6BC', 'ONE Biceps Curl', 'arms', 'selectorized', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6BC.jpg'),
(1285, 'Nautilus', 'S6TP', 'ONE Triceps Press', 'arms', 'selectorized', 'tricep_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6TP.png'),
(1286, 'Nautilus', 'S6LP', 'ONE Leg Press', 'legs', 'selectorized', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6LP.png'),
(1287, 'Nautilus', 'S6LE', 'ONE Leg Extension', 'legs', 'selectorized', 'leg_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6LE.png'),
(1288, 'Nautilus', 'S6LC', 'ONE Seated Leg Curl', 'legs', 'selectorized', 'leg_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6LC.png'),
(1289, 'Nautilus', 'S6AA', 'ONE Hip Abduction/Adduction', 'legs', 'selectorized', 'hip_abduction,hip_adduction', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6AA.png'),
(1290, 'Nautilus', 'S6AB', 'ONE Abdominal Crunch', 'core', 'selectorized', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6AB.png'),
(1291, 'Nautilus', 'S6LB', 'ONE Low Back', 'core', 'selectorized', 'back_extension', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6LB.png'),
(1292, 'Nautilus', 'S6RT', 'ONE Rotary Torso', 'core', 'selectorized', 'torso_rotation', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/S6RT.jpg'),

-- ===== LEVERAGE SERIES (Plate-loaded) =====
(1293, 'Nautilus', '9NP-L2002', 'Leverage Chest Press', 'chest', 'plate-loaded', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L2002.jpg'),
(1294, 'Nautilus', '9NP-L2003', 'Leverage Incline Press', 'chest', 'plate-loaded', 'incline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L2003.jpg'),
(1295, 'Nautilus', '9NP-L2004', 'Leverage Decline Press', 'chest', 'plate-loaded', 'decline_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L2004.jpg'),
(1296, 'Nautilus', '9NP-L4002', 'Leverage Shoulder Press', 'shoulders', 'plate-loaded', 'shoulder_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L4002.jpg'),
(1297, 'Nautilus', '9NP-L3003', 'Leverage Lat Pull Down', 'back', 'plate-loaded', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L3003.jpg'),
(1298, 'Nautilus', '9NP-L3005', 'Leverage High Row', 'back', 'plate-loaded', 'high_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L3005.jpg'),
(1299, 'Nautilus', '9NP-L3004', 'Leverage Low Row', 'back', 'plate-loaded', 'low_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L3004.jpg'),
(1300, 'Nautilus', '9NP-L3140', 'Leverage Incline Lever Row', 'back', 'plate-loaded', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L3140.jpg'),
(1301, 'Nautilus', '9NP-L3006', 'Leverage Deadlift Shrug', 'back', 'plate-loaded', 'shrug', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L3006.jpg'),
(1302, 'Nautilus', '9NP-L5002', 'Leverage Biceps Curl', 'arms', 'plate-loaded', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L5002.jpg'),
(1303, 'Nautilus', '9NP-L5003', 'Leverage Abdominal Crunch', 'core', 'plate-loaded', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L5003.jpg'),

-- ===== PLATE-LOADED (non-Leverage) =====
(1304, 'Nautilus', '9NP-L1130', 'Hack Squat', 'legs', 'plate-loaded', 'squat', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L1130.jpg'),
(1305, 'Nautilus', '9NP-L1141', 'Angled Leg Press', 'legs', 'plate-loaded', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L1141.jpg'),
(1306, 'Nautilus', '9NP-L1110', 'Tilt Seat Calf', 'legs', 'plate-loaded', 'calf', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L1110.jpg'),
(1307, 'Nautilus', '9NP-L1131', 'Glute Drive', 'glutes', 'plate-loaded', 'glute_kickback', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/9NP-L1131.jpg'),

-- ===== HUMANSPORT SERIES (Cable) =====
(1308, 'Nautilus', 'HSSC3', 'HumanSport Shoulder Chest', 'chest', 'cable', 'chest_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/HSSC3.jpg'),
(1309, 'Nautilus', 'HSTD3', 'HumanSport Total Delts', 'shoulders', 'cable', 'lateral_raise', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/HSTD3.jpg'),
(1310, 'Nautilus', 'HSLP3', 'HumanSport Lat Pulley', 'back', 'cable', 'lat_pulldown', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/HSLP3.jpg'),
(1311, 'Nautilus', 'HSPL3', 'HumanSport Pull Lift', 'back', 'cable', 'seated_row', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/HSPL3.jpg'),
(1312, 'Nautilus', 'HSAC3', 'HumanSport Arm Crunch', 'arms', 'cable', 'bicep_curl', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/HSAC3.jpg'),
(1313, 'Nautilus', 'HSTL3', 'HumanSport Total Legs', 'legs', 'cable', 'leg_press', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/HSTL3.jpg'),
(1314, 'Nautilus', 'IPAC5', 'HumanSport Abdominal Crunch', 'core', 'cable', 'crunch', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/IPAC5.jpg'),
(1315, 'Nautilus', 'HSFT3', 'HumanSport Freedom Trainer', 'full_body', 'cable', 'cable_multi', 'https://mqyfdbfdeuwojgexhwpy.supabase.co/storage/v1/object/public/equipment-images/nautilus/HSFT3.jpg')

ON CONFLICT (id) DO UPDATE SET
    brand = EXCLUDED.brand,
    model = EXCLUDED.model,
    name = EXCLUDED.name,
    muscle_group = EXCLUDED.muscle_group,
    equipment_type = EXCLUDED.equipment_type,
    exercise_type = EXCLUDED.exercise_type,
    image_url = EXCLUDED.image_url;
